### ISSUE TITLE
Web2Print Problem - help -

### ISSUE THREAD

**Issue by FlorianCart** [pimcore/pimcore#1003]
Hi guys,

I have a little question about Web2Print, because I have a little problem.
My boss asks me to print document with wkhtmltopdf or pdfreactor.
So I just follow the doc, but I have a problem with default code.
  
### Code example 
```php
 public function containerAction()
    {
        $document = $this->getParam("document");
        $allChildren = $document->getAllChildren();

        $this->view->allChildren = $allChildren;

    }
```
And if I try : 
```php
 Exception
Call to undefined method getAllChildren in class Pimcore\Model\Document\Printpage
```
Second try. If i use defaultAction other problem : 
```php
Fatal error:  Uncaught exception 'Exception' with message 'No 'php' executable found, please install the application or add it to the PATH (in system settings or to your PATH environment variable' in C:\xampp\htdocs\pimcore\lib\Pimcore\Tool\Console.php:125
Stack trace:
#0 C:\xampp\htdocs\pimcore\lib\Pimcore\Tool\Console.php(191): Pimcore\Tool\Console::getExecutable('php', true)
#1 C:\xampp\htdocs\pimcore\lib\Pimcore\Web2Print\Processor.php(71): Pimcore\Tool\Console::getPhpCli()
#2 C:\xampp\htdocs\pimcore\models\Document\PrintAbstract.php(78): Pimcore\Web2Print\Processor->preparePdfGeneration(12, Array)
#3 C:\xampp\htdocs\pimcore\lib\Pimcore\Controller\Action\Admin\Printpage.php(194): Pimcore\Model\Document\PrintAbstract->generatePdf(Array)
#4 C:\xampp\htdocs\vendor\zendframework\zendframework1\library\Zend\Controller\Action.php(516): Pimcore\Controller\Action\Admin\Printpage->startPdfGenerationAction()
#5 C:\xampp\htdocs\vendor\zendframework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controll in C:\xampp\htdocs\pimcore\lib\Pimcore\Tool\Console.php on line 125


```
I just need to know if it's normal ? Because My only request is to print doc with pdf format.
Or need to know if I'm just bad with this function.
Sorry For my english.

Florian Cart

**Comment by solverat** [comment]
i think this is not an issue. please use the google forum for questions like that:

https://groups.google.com/forum/m/#!forum/pimcore

**Comment by FlorianCart** [comment]
I put it on.
