### ISSUE TITLE
Sanity Check -> version with id  not found

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#1026]
Sanity Check throws a lot of Exception when versions are disabled. 

```
core.EMERGENCY: exception 'Exception' with message 'version with id  not found' in /var/www/html/pimcore/pimcore/models/Version/Dao.php:34 
 
Stack trace: 
 
#0 /var/www/html/pimcore/pimcore/models/Version.php(91): Pimcore\Model\Version\Dao->getById(NULL) 
#1 /var/www/html/pimcore/pimcore/models/Object/Concrete/Dao.php(388): Pimcore\Model\Version::getById(NULL) 
#2 [internal function]: Pimcore\Model\Object\Concrete\Dao->getLatestVersion(true) 
#3 /var/www/html/pimcore/pimcore/lib/Pimcore/Model/AbstractModel.php(257): call_user_func_array(Array, Array) 
#4 /var/www/html/pimcore/pimcore/models/Object/AbstractObject.php(1193): Pimcore\Model\AbstractModel->__call('getLatestVersio...', Array) 
#5 /var/www/html/pimcore/pimcore/models/Element/Service.php(400): Pimcore\Model\Object\AbstractObject->__call('getLatestVersio...', Array) 
#6 /var/www/html/pimcore/pimcore/models/Element/Service.php(400): Pimcore\Model\Object\Order->getLatestVersion(true) 
#7 /var/www/html/pimcore/pimcore/models/Element/Service.php(368): Pimcore\Model\Element\Service::performSanityCheck(Object(Pimcore\Model\Object\Order)) 
#8 [internal function]: Pimcore\Model\Element\Service::runSanityCheck() 
#9 /var/www/html/pimcore/pimcore/models/Schedule/Maintenance/Job.php(69): call_user_func_array(Array, Array) 
#10 /var/www/html/pimcore/pimcore/models/Schedule/Manager/Procedural.php(103): Pimcore\Model\Schedule\Maintenance\Job->execute() 
#11 /var/www/html/pimcore/pimcore/lib/Pimcore/Console/Command/MaintenanceCommand.php(77): Pimcore\Model\Schedule\Manager\Procedural->run() 
#12 /var/www/html/pimcore/vendor/symfony/console/Command/Command.php(256): Pimcore\Console\Command\MaintenanceCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#13 /var/www/html/pimcore/vendor/symfony/console/Application.php(834): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#14 /var/www/html/pimcore/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Console\Command\MaintenanceCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#15 /var/www/html/pimcore/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#16 /var/www/html/pimcore/pimcore/cli/console.php(23): Symfony\Component\Console\Application->run(NULL) #17 {main} {"origin":"Pimcore\\Model\\AbstractModel->__call() on line 261
```

The problem is the $force variable, it tries to fetch a version even if the result from the database command is null

```php
public function getLatestVersion($force = false)
    {
        $versionData = $this->db->fetchRow("SELECT id,date FROM versions WHERE cid = ? AND ctype='object' ORDER BY `id` DESC LIMIT 1", $this->model->getId()); //Returns null, because no version exists in db

        if (($versionData["id"] && $versionData["date"] > $this->model->getModificationDate()) || $force) {
            $version = Model\Version::getById($versionData["id"]);

            return $version;
        }

        return;
    }
```

**Comment by weisswurstkanone** [comment]
thx.

build 3999

**Comment by weisswurstkanone** [comment]
changed for assets and documents as well

**Comment by dpfaffenbauer** [comment]
thanks 👍
