### ISSUE TITLE
Assets\Images: Edit pictures with integrated editor

### ISSUE THREAD

**Issue by aarongerig** [pimcore/pimcore#1028]
### Expected behavior 
I get an issue when editing a picture in the integrated image editor.
Whenever I crop and save an image, pimcore creates an new version of the image.

**Asset in Editmode**
![asset_in_editmode](https://cloud.githubusercontent.com/assets/17384333/20173953/db765362-a73b-11e6-8845-e6678b3ea558.png)

This is the expected behaviour.

**Original Version**
![asset_original_version](https://cloud.githubusercontent.com/assets/17384333/20173951/db753946-a73b-11e6-88c8-dad720be649d.png)
**Edited Version**
![asset_edited_version](https://cloud.githubusercontent.com/assets/17384333/20173954/db7b67e4-a73b-11e6-972e-e456777c409f.png)

Now it should display the cropped image correctly in both backend and frontend.

### Actual behavior
Unfortunately I does not display the image at all anymore (backend and frontend)!

**Backend**
![asset_preview_after_edit](https://cloud.githubusercontent.com/assets/17384333/20173950/db743460-a73b-11e6-8917-d64c72081769.png)
**Frontend**
![asset_after_edit_in_frontend](https://cloud.githubusercontent.com/assets/17384333/20173952/db757e06-a73b-11e6-8167-9438a4a06bf5.png)
  

### Steps to reproduce  
– Upload any picture you like
– Open it from the Assets panel
– Go to editmode and crop your image
– Confirm your crop on the top right
– Save your newly cropped image on the top right
– Save your Assts with «Save and publish»

**Comment by brusch** [comment]
Everything works as expected, I'm not able to reproduce the problem. 
Can you reproduce the problem on demo.pimcore.org? (https://www.pimcore.org/demo).

**Comment by aarongerig** [comment]
True, on demo.pimcore.org it works. My pimcore instance is on v4.3.1 build 3961, demo.pimcore.org is on v4.3.1 build 3998. Are we missing some tools on our server?

![tools](https://cloud.githubusercontent.com/assets/17384333/20176915/5ce8e9c4-a74a-11e6-8480-71b33fcc5e42.png)

**Comment by brusch** [comment]
No, the marked tools are not mandatory. 
Maybe something else. Try it again with the latest build, if it still doesn't work, check the logs.

**Comment by aarongerig** [comment]
Nope, still seems to be a problem.
In my log file it throws this Imagick Exception:

```log
[2016-11-10 14:00:00] core.DEBUG: Successfully got data for key pimcore_asset_1 from cache {"origin":"Pimcore\\Cache::load() on line 296","memory":"  2 MB"} []
[2016-11-10 14:00:00] core.DEBUG: Successfully got data for key pimcore_asset_properties_244 from cache {"origin":"Pimcore\\Cache::load() on line 296","memory":"  2 MB"} []
[2016-11-10 14:00:00] core.DEBUG: Key pimcore_system_resource_columns_assets doesn't exist in cache {"origin":"Pimcore\\Cache::load() on line 298","memory":"  2 MB"} []
[2016-11-10 14:00:00] core.DEBUG: Key pimcore_system_resource_columns_versions doesn't exist in cache {"origin":"Pimcore\\Cache::load() on line 298","memory":"  3 MB"} []
[2016-11-10 14:00:00] core.ERROR: Couldn't create thumbnail of image /Riwag_Tuere_Holz_Fertigungstiefe.jpg {"origin":"Pimcore\\Model\\Asset\\Image\\Thumbnail->generate() on line 147","memory":"  3 MB"} []
[2016-11-10 14:00:00] core.ERROR: ImagickException: Unable to set image alpha channel in /var/www/vhosts/my.domain.com/httpdocs/pimcore/lib/Pimcore/Image/Adapter/Imagick.php:186 Stack trace: #0 /var/www/vhosts/my.domain.com/httpdocs/pimcore/lib/Pimcore/Image/Adapter/Imagick.php(186): Imagick->setimagealphachannel(11) #1 /var/www/vhosts/my.domain.com/httpdocs/pimcore/models/Asset/Image/Thumbnail/Processor.php(320): Pimcore\Image\Adapter\Imagick->save('/var/www/vhosts...', 'pjpeg', 60) #2 /var/www/vhosts/my.domain.com/httpdocs/pimcore/models/Asset/Image/Thumbnail.php(144): Pimcore\Model\Asset\Image\Thumbnail\Processor::process(Object(Pimcore\Model\Asset\Image), Object(Pimcore\Model\Asset\Image\Thumbnail\Config), '/var/www/vhosts...', false, true, false) #3 /var/www/vhosts/my.domain.com/httpdocs/pimcore/models/Asset/Image/Thumbnail.php(120): Pimcore\Model\Asset\Image\Thumbnail->generate(false) #4 /var/www/vhosts/my.domain.com/httpdocs/pimcore/models/Asset/Image.php(69): Pimcore\Model\Asset\Image\Thumbnail->getFileSystemPath() #5 /var/www/vhosts/my.domain.com/httpdocs/pimcore/models/Asset.php(474): Pimcore\Model\Asset\Image->update() #6 /var/www/vhosts/my.domain.com/httpdocs/pimcore/modules/admin/controllers/AssetController.php(1156): Pimcore\Model\Asset->save() #7 /var/www/vhosts/my.domain.com/httpdocs/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): Admin_AssetController->imageEditorSaveAction() #8 /var/www/vhosts/my.domain.com/httpdocs/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('imageEditorSave...') #9 /var/www/vhosts/my.domain.com/httpdocs/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) #10 /var/www/vhosts/my.domain.com/httpdocs/pimcore/lib/Pimcore.php(256): Zend_Controller_Front->dispatch() #11 /var/www/vhosts/my.domain.com/httpdocs/index.php(14): Pimcore::run() #12 {main} {"origin":"Pimcore\\Model\\Asset\\Image\\Thumbnail->generate() on line 148","memory":"  3 MB"} []
[2016-11-10 14:00:00] core.INFO: clear cache tags: asset_244,asset_properties,output {"origin":"Pimcore\\Cache::clearTags() on line 659","memory":"  3 MB"} []
```

**Comment by brusch** [comment]
Seems to be an Imagick issue, with Imagick 3.4.2 and ImageMagick 6.8.9-9 Q16 everything works as expected. 
Which versions of PHP, Imagick and ImageMagick are you using?

**Comment by aarongerig** [comment]
PHP 7.0.12
Imagick 3.4.1
ImageMagick 6.6.9-7 2016-06-01 Q16

Are your mentioned versions reverse compatible with pimcore 1, 2 and 3?
Otherwise we have to setup a new server only for pimcore 4.

**Comment by brusch** [comment]
As far as I know this should be the case, but we don't have dedicated test-cases for that.
