### ISSUE TITLE
[Bug]: ExtensionManagerController NullOutput error

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#10759]
### Expected behavior

-

### Actual behavior

I've installed CoreShop in a Pimcore 10.2 project. Opening the Bundles & bricks page throws an error. 

```
Message: Attempted to call an undefined method named "fetch" of class "Symfony\Component\Console\Output\NullOutput".
Trace: 
in /app/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/ExtensionManager/ExtensionManagerController.php:495
#0 /app/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/ExtensionManager/ExtensionManagerController.php(412): Pimcore\Bundle\AdminBundle\Controller\ExtensionManager\ExtensionManagerController->getInstallerOutput(Object(CoreShop\Bundle\CoreBundle\CoreShopCoreBundle))
#1 /app/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/ExtensionManager/ExtensionManagerController.php(315): Pimcore\Bundle\AdminBundle\Controller\ExtensionManager\ExtensionManagerController->buildBundleInfo(Object(CoreShop\Bundle\CoreBundle\CoreShopCoreBundle))
#2 /app/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/ExtensionManager/ExtensionManagerController.php(78): Pimcore\Bundle\AdminBundle\Controller\ExtensionManager\ExtensionManagerController->getBundleList()
#3 /app/vendor/symfony/http-kernel/HttpKernel.php(156): Pimcore\Bundle\AdminBundle\Controller\ExtensionManager\ExtensionManagerController->getExtensionsAction()
#4 /app/vendor/symfony/http-kernel/HttpKernel.php(78): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /app/vendor/symfony/http-kernel/Kernel.php(199): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /app/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#7 {main}
```

$output is type hinted as BufferedOutput, but it looks like it can also return a NullOutput, which doesn't provide the fetch() method. I'm not sure if this is an install error and "should not happen", but it would be better to check the $output instance.

https://github.com/pimcore/pimcore/blob/4550a053fac47a1d2c0406bf15c9799ef078bbb7/bundles/AdminBundle/Controller/ExtensionManager/ExtensionManagerController.php#L491

### Steps to reproduce

In my case the error occured after installing CoreShop, but I have no idea if it's related to this.

**Comment by dpfaffenbauer** [comment]
CoreShop Installer returns `NullOutput` for `Pimcore\Extension\Bundle\Installer\InstallerInterface` cause Pimcore allows it. It worked fine for Pimcore pre X and should also work for Pimcore >= X.
