### ISSUE TITLE
WebsiteSetting / getByName

### ISSUE THREAD

**Issue by manuelkleinert** [pimcore/pimcore#1090]
The getByName function from Dao throws an error

Filepath; pimcore/models/ WebsiteSetting.php

```php
$setting->getDao()->getByName($name, $siteId);
 ```

### Code example 
```php
<?= \Pimcore\Model\WebsiteSetting::getByName("copyright", 35); ?>
```

Excuse me for the short message, my english is not so good.

**Comment by mrudnicki** [comment]
Hi @manuelkleinert,
Unfortunately, I can't repeat the issue in my environment. 
Which Pimcore version did you use? What kind of error you can see?

**Comment by manuelkleinert** [comment]
Hallo @mrudnicki 

I have the version 4.4.1. 
The problem is that I have several main domains.

Filepath; pimcore/models/ WebsiteSetting.php
```php
        try {
            $setting->getDao()->getByName($name, $siteId);
        } catch (\Exception $e) {
            Logger::error($e);

            return null;
        }
```

Error:
```
Zend_Controller_Exception
Website Setting with name: test does not exist#0 /var/www/vhosts/gewerberegionsursee.ch/httpdocs/pimcore/models/WebsiteSetting.php(86): Pimcore\Model\WebsiteSetting\Dao->getByName('test', 35) #1 /var/www/vhosts/gewerberegionsursee.ch/httpdocs/website/modules/association/views/layouts/standard.php(120): Pimcore\Model\WebsiteSetting::getByName('Copyright', 35) #2 /var/www/vhosts/gewerberegionsursee.ch/httpdocs/vendor/zendframework/zendframework1/library/Zend/View.php(157): include('/var/www/vhosts...') #3 /var/www/vhosts/gewerberegionsursee.ch/httpdocs/vendor/zendframework/zendframework1/library/Zend/View/Abstract.php(888): Zend_View->_run('/var/www/vhosts...') #4 /var/www/vhosts/gewerberegionsursee.ch/httpdocs/vendor/zendframework/zendframework1/library/Zend/Layout.php(796): Zend_View_Abstract->render() #5 /var/www/vhosts/gewerberegionsursee.ch/httpdocs/vendor/zendframework/zendframework1/library/Zend/Layout/Controller/Plugin/Layout.php(143): Zend_Layout->render() #6 /var/www/vhosts/gewerberegionsursee.ch/httpdocs/vendor/zendframework/zendframework1/library/Zend/Controller/Plugin/Broker.php(333): Zend_Layout_Controller_Plugin_Layout->postDispatch(Object(Zend_Controller_Request_Http)) #7 /var/www/vhosts/gewerberegionsursee.ch/httpdocs/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(965): Zend_Controller_Plugin_Broker->postDispatch(Object(Zend_Controller_Request_Http)) #8 /var/www/vhosts/gewerberegionsursee.ch/httpdocs/pimcore/lib/Pimcore.php(256): Zend_Controller_Front->dispatch() #9 /var/www/vhosts/gewerberegionsursee.ch/httpdocs/index.php(16): Pimcore::run() #10 {main}
```

Settings:
![settings](https://cloud.githubusercontent.com/assets/1038688/20742647/97764a46-b6d1-11e6-8c73-286413bc7a70.PNG)

**Comment by fashxp** [comment]
we still cannot reproduce your problem on the latest build. 
is your site-id correct? you can double check that in your sites table.
