### ISSUE TITLE
Delete Class does not delete Object-Brick ClassDefinition reference

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#1133]
When deleting a class, it doesn't delete its corresponding Object-Bricks ClassDefinition. Steps to reproduce:

- Create a class with objectbrick field
- Create objectbrick and reference new created Class
- Objectbrick definition now looks like this:

 ```
 'classDefinitions' => 
  array (
    0 => 
    array (
      'classname' => 7,
      'fieldname' => 'test',
    ),
  )
```
- Delete the class
- Objectbrick definition now still looks the same.
 ```
 'classDefinitions' => 
  array (
    0 => 
    array (
      'classname' => 7,
      'fieldname' => 'test',
    ),
  )
```
- Now re-open the objectbrick definition in pimcore, you'll get following error from ```/admin/object-helper/grid-get-column-config```

````

Warning: include(/home/pimcore_demo/www/website/var/classes/definition_.php): failed to open stream: No such file or directory in /home/pimcore_demo/www/pimcore/models/Object/ClassDefinition.php on line 160

Warning: include(): Failed opening '/home/pimcore_demo/www/website/var/classes/definition_.php' for inclusion (include_path='/home/pimcore_demo/www/vendor/zendframework/zendframework1/library:/home/pimcore_demo/www/pimcore/lib:/home/pimcore_demo/www/pimcore/models:/home/pimcore_demo/www/website/lib:/home/pimcore_demo/www/website/models:/home/pimcore_demo/www/website/var/classes:/home/pimcore_demo/www/vendor/zendframework/zendframework1/library/:') in /home/pimcore_demo/www/pimcore/models/Object/ClassDefinition.php on line 160

Fatal error: Uncaught Error: Call to a member function getFieldDefinitions() on null in /home/pimcore_demo/www/pimcore/modules/admin/controllers/ObjectHelperController.php:58 Stack trace: #0 /home/pimcore_demo/www/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): Admin_ObjectHelperController->gridGetColumnConfigAction() #1 /home/pimcore_demo/www/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('gridGetColumnCo...') #2 /home/pimcore_demo/www/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) #3 /home/pimcore_demo/www/pimcore/lib/Pimcore.php(250): Zend_Controller_Front->dispatch() #4 /home/pimcore_demo/www/index.php(18): Pimcore::run() #5 {main} thrown in /home/pimcore_demo/www/pimcore/modules/admin/controllers/ObjectHelperController.php on line 58
```

PS: All tests have been made on Pimcore Demo Website

**Comment by weisswurstkanone** [comment]
fixed in build 4038
