### ISSUE TITLE
[Bug]: Advanced Many-to-many relations causes error on save

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#11883]
### Expected behavior

Saving metadata on Many-to-many relations should work

### Actual behavior

Leaving a multiselect with none checked results in 500 server error:

![image](https://user-images.githubusercontent.com/279826/162739917-cf7f12cd-e787-4029-a9d7-be4055293a94.png)

```
Timestamp: Mon Apr 11 2022 14:32:08 GMT+0200 (Central European Summer Time)
Status: 500 | Internal Server Error
URL: /admin/object/save?task=publish
Method: PUT
Message: An exception occurred while executing 'INSERT INTO `object_metadata_product` (`o_id`, `dest_id`, `fieldname`, `ownertype`, `ownername`, `index`, `position`, `type`, `column`, `data`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE `o_id` = ?, `dest_id` = ?, `fieldname` = ?, `ownertype` = ?, `ownername` = ?, `index` = ?, `position` = ?, `type` = ?, `column` = ?, `data` = ?;' with params [22964, 23524, "dimensionalSketches", "object", "", 1, "0", "asset", "locale", [], 22964, 23524, "dimensionalSketches", "object", "", 1, "0", "asset", "locale", []]:

Warning: Array to string conversion
Trace: 
in /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:185
#0 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(159): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDO\MySQL\Driver), Object(ErrorException), 'An exception oc...')
#1 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(2226): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\MySQL\Driver), Object(ErrorException), 'INSERT INTO `ob...', Array)
#2 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1538): Doctrine\DBAL\Connection->handleExceptionDuringQuery(Object(ErrorException), 'INSERT INTO `ob...', Array, Array)
#3 /var/www/pimcore/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(117): Doctrine\DBAL\Connection->executeStatement('INSERT INTO `ob...', Array, Array)
#4 /var/www/pimcore/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(375): Pimcore\Db\Connection->executeUpdate('INSERT INTO `ob...', Array)
#5 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/Data/ObjectMetadata/Dao.php(63): Pimcore\Db\Connection->insertOrUpdate('object_metadata...', Array)
#6 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/Data/ElementMetadata.php(127): Pimcore\Model\DataObject\Data\ObjectMetadata\Dao->save(Object(App\Model\DataObject\Product), 'object', NULL, '0', 1, 'asset')
#7 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php(640): Pimcore\Model\DataObject\Data\ElementMetadata->save(Object(App\Model\DataObject\Product), 'object', NULL, '0', 1)
#8 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/Concrete/Dao.php(258): Pimcore\Model\DataObject\ClassDefinition\Data\AdvancedManyToManyRelation->save(Object(App\Model\DataObject\Product), Array)
#9 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/Concrete.php(204): Pimcore\Model\DataObject\Concrete\Dao->update(true)
#10 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(734): Pimcore\Model\DataObject\Concrete->update(true, Array)
#11 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/Concrete.php(714): Pimcore\Model\DataObject\AbstractObject->save(Array)
#12 /var/www/pimcore/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(1368): Pimcore\Model\DataObject\Concrete->save()
#13 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(152): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->saveAction(Object(Symfony\Component\HttpFoundation\Request))
#14 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#15 /var/www/pimcore/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /var/www/pimcore/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#17 {main}
```

### Steps to reproduce

1. Create the Advanced Many-to-many relation with and additional mutiselect field in your Model, in our case:
    ![image](https://user-images.githubusercontent.com/279826/162740231-e6fe001a-d2cf-49d3-889f-21e46028a3cf.png)

3. Add an asset or object to the relation:
    ![image](https://user-images.githubusercontent.com/279826/162739487-11d38ace-5dd9-4729-a96b-8573b6bced34.png)

4. Click on in to open the options:
    ![image](https://user-images.githubusercontent.com/279826/162739607-518ca1ce-3e93-4272-b991-6c94accd186d.png)

5. Select _at least one_ option:
    ![image](https://user-images.githubusercontent.com/279826/162739650-39c57927-38e5-42d0-ad03-31f320d8f811.png)

6. De-select it:
    ![image](https://user-images.githubusercontent.com/279826/162739770-ad66d043-154d-4258-806b-13d4408c6d40.png)

7. Click _Save_.
8. Click _Save & Publish_ on the asset/object.

**Comment by aryaantony92** [comment]
Fixed by #11934
