### ISSUE TITLE
[Bug]: Maintenance generateLowQualityPreview issue stream_get_meta_data(): Argument #1 ($stream) must be of type resource, null given

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#11909]
### Expected behavior

Should generate low Quality Preview Image

### Actual behavior

throws an error

### Steps to reproduce

Use remote storage with low Qualilty Preview Images enabled

I guess it doesn't work with remote storages yet properly?

```
TypeError: stream_get_meta_data(): Argument #1 ($stream) must be of type resource, null given
#26 /vendor/pimcore/pimcore/lib/Helper/TemporaryFileHelperTrait.php(37): stream_get_meta_data
#25 /vendor/pimcore/pimcore/lib/Helper/TemporaryFileHelperTrait.php(37): Pimcore\Model\Asset\Image\Thumbnail::getLocalFileFromStream
#24 /vendor/pimcore/pimcore/models/Asset/Thumbnail/ImageThumbnailTrait.php(337): Pimcore\Model\Asset\Image\Thumbnail::getLocalFile
#23 /vendor/pimcore/pimcore/models/Asset/Image.php(174): Pimcore\Model\Asset\Image::generateLowQualityPreview
#22 /vendor/pimcore/pimcore/lib/Messenger/Handler/AssetUpdateTasksHandler.php(124): Pimcore\Messenger\Handler\AssetUpdateTasksHandler::processImage
#21 /vendor/pimcore/pimcore/lib/Messenger/Handler/AssetUpdateTasksHandler.php(38): Pimcore\Messenger\Handler\AssetUpdateTasksHandler::__invoke
#20 /vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php(96): Symfony\Component\Messenger\Middleware\HandleMessageMiddleware::handle
#19 /vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(74): Symfony\Component\Messenger\Middleware\SendMessageMiddleware::handle
#18 /vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\Component\Messenger\Middleware\FailedMessageProcessingMiddleware::handle
#17 /vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\Component\Messenger\Middleware\DispatchAfterCurrentBusMiddleware::handle
#16 /vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(48): Symfony\Component\Messenger\Middleware\RejectRedeliveredMessageMiddleware::handle
#15 /vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\Component\Messenger\Middleware\AddBusNameStampMiddleware::handle
#14 /vendor/symfony/messenger/MessageBus.php(77): Symfony\Component\Messenger\MessageBus::dispatch
#13 /vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\Component\Messenger\RoutableMessageBus::dispatch
#12 /vendor/symfony/messenger/Worker.php(158): Symfony\Component\Messenger\Worker::handleMessage
#11 /vendor/symfony/messenger/Worker.php(107): Symfony\Component\Messenger\Worker::run
#10 /vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(225): Symfony\Component\Messenger\Command\ConsumeMessagesCommand::execute
#9 /vendor/symfony/console/Command/Command.php(298): Symfony\Component\Console\Command\Command::run
#8 /vendor/symfony/console/Command/LazyCommand.php(71): Symfony\Component\Console\Command\LazyCommand::run
#7 /vendor/pimcore/pimcore/bundles/CoreBundle/Command/MaintenanceCommand.php(124): Pimcore\Bundle\CoreBundle\Command\MaintenanceCommand::execute
#6 /vendor/symfony/console/Command/Command.php(298): Symfony\Component\Console\Command\Command::run
#5 /vendor/symfony/console/Application.php(1023): Symfony\Component\Console\Application::doRunCommand
#4 /vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Bundle\FrameworkBundle\Console\Application::doRunCommand
#3 /vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application::doRun
#2 /vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Bundle\FrameworkBundle\Console\Application::doRun
#1 /vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application::run
#0 /bin/console(51): null
```

**Comment by brusch** [comment]
For me it works like a charm, tested with MinIO. 
Tested with the demo: 
```php
$image = Asset\Image::getById(360);
$thumbnail = $image->generateLowQualityPreview();
```

**Comment by brusch** [comment]
Also tested again with AWS S3, again, works like a charm (used `10.x` branch).

**Comment by brusch** [comment]
@dpfaffenbauer any more insights on that? Thanks!

**Comment by dpfaffenbauer** [comment]
@brusch Interesting, might be that it happens when the asset doesn't exist on the storage but in the Pimcore DB?

**Comment by brusch** [comment]
@brusch might be, ... but if this is the case, I'd say this doesn't need to be covered by Pimcore. I'm closing this for now.

**Comment by thijs-windels** [comment]
Sorry to reopen this issue, but it seems like there are other scenario's where this exception happens. In my case, I uploaded a .ai (Adobe Illustrator) file and get this error in the logs.

A TypeError is thrown by the method `generateLowQualityPreview`, but won't be catched because that class is of not an Exception but a Throwable.

Seems like after catching both an Exception and a Throwable at these places, everything works fine again:

- https://github.com/pimcore/pimcore/blob/6a567fc2895a63d816194784b80dd71812df4fbf/lib/Maintenance/Tasks/LowQualityImagePreviewTask.php#L70.
- https://github.com/pimcore/pimcore/blob/6a567fc2895a63d816194784b80dd71812df4fbf/lib/Messenger/Handler/AssetUpdateTasksHandler.php#L138
