### ISSUE TITLE
[Bug]: 10.3.6 QuickSearch exception for non-admin users

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#11998]
### Expected behavior

QuickSearch should work for all users.

### Actual behavior

Left side: Admin user
Right side: User with limited permissions
![image](https://user-images.githubusercontent.com/279826/165778926-3eccc82c-9219-4927-b202-ef9978582bf8.png)

```trace
Timestamp: Thu Apr 28 2022 16:39:16 GMT+0200 (Central European Summer Time)
Status: 500 | Internal Server Error
URL: /admin/search/search/quicksearch?_dc=1651156756409
Method: GET
Message: An exception occurred while executing '
            SELECT
                cpath, userid, max(list) as list
            FROM users_workspaces_asset
            WHERE userId IN (4,15) AND cid NOT IN ()
            GROUP BY cpath
        ':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')
            GROUP BY cpath' at line 4
Trace: 
in /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:98
#0 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(182): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDO\Exception))
#1 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(159): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDO\MySQL\Driver), Object(Doctrine\DBAL\Driver\PDO\Exception), 'An exception oc...')
#2 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(2226): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\MySQL\Driver), Object(Doctrine\DBAL\Driver\PDO\Exception), '\n            SE...', Array)
#3 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1313): Doctrine\DBAL\Connection->handleExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\Exception), '\n            SE...', Array, Array)
#4 /var/www/pimcore/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(99): Doctrine\DBAL\Connection->executeQuery('\n            SE...', Array, Array, NULL)
#5 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1000): Pimcore\Db\Connection->executeQuery('\n            SE...', Array, Array)
#6 /var/www/pimcore/vendor/pimcore/pimcore/models/Element/Service.php(751): Doctrine\DBAL\Connection->fetchAll('\n            SE...')
#7 /var/www/pimcore/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Searchadmin/SearchController.php(367): Pimcore\Model\Element\Service::findForbiddenPaths('asset', Object(Pimcore\Model\User))
#8 /var/www/pimcore/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Searchadmin/SearchController.php(443): Pimcore\Bundle\AdminBundle\Controller\Searchadmin\SearchController->getForbiddenCondition()
#9 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(152): Pimcore\Bundle\AdminBundle\Controller\Searchadmin\SearchController->quicksearchAction(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#10 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#11 /var/www/pimcore/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /var/www/pimcore/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
```

### Steps to reproduce

1. Search for something as admin
2. Log in as a different user
3. Search for anything as the limited user.

(demo.pimcore.fun is currently unavailable due to "maintenance downtime or capacity problems" so can not attempt to reproduce there)

**Comment by NiklasBr** [comment]
Possible regression of https://github.com/pimcore/pimcore/commit/fae3a865b21ec55ddc6845dde13f001a633a3232?
