### ISSUE TITLE
[Bug]: "Cannot instantiate abstract class `Pimcore\Model\Document\PageSnippet`" when adding an AreaBrick with an empty cache

### ISSUE THREAD

**Issue by jdreesen** [pimcore/pimcore#12408]
### Expected behavior

Adding an AreaBrick to a Page should be possible even without an empty data cache.

### Actual behavior

When adding an AreaBrick to a Page right after the data cache was cleared, the following Exception is thrown: 
`Cannot instantiate abstract class Pimcore\Model\Document\PageSnippet`

Trace
```
in /var/www/html/vendor/pimcore/pimcore/models/Document.php:300
#0 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/PageController.php(407): Pimcore\Model\Document::getById(2)
#1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(152): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\PageController->areabrickRenderIndexEditmode(Object(Symfony\Component\HttpFoundation\Request), Object(Pimcore\Document\Editable\Block\BlockStateStack), Object(Pimcore\Document\Editable\EditmodeEditableDefinitionCollector), Object(Twig\Environment), Object(Pimcore\Templating\Renderer\EditableRenderer), Object(Pimcore\Http\Request\Resolver\DocumentResolver))
#2 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#3 /var/www/html/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#4 /var/www/html/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#5 {main}
```

### Steps to reproduce

- Create a Document with an AreaBlock and open it in the admin backend
- Call `bin/console pimcore:cache:clear`
- Add an AreaBrick to the AreaBlock in the Document

**Comment by jdreesen** [comment]
Nevermind. It seems it's already fixed by #12104 in `10.4.2` (we were still using `10.4.1`).
