### ISSUE TITLE
Failed update from 4.0.0 to 4.4.3 Duplicate column name 'reference' in table 'quantityvalue_units'

### ISSUE THREAD

**Issue by jbq** [pimcore/pimcore#1283]
### Expected behavior 

Running `sudo -u www-data php /var/www/pimcore/cli/console.php update -u 4.4.3` on my Pimcore 4.0.0 installation I'm expecting to have no error.

### Actual behavior  

```
You are going to update to build 4044! Continue with this action? (y/n)y
Starting the update process ...
 751/751 [============================] 100%

Update stopped by error! Please check your logs
Last return value was: [2017-02-13 16:14:40] core.ERROR: PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'reference' in /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228 Stack trace: #0 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array) #1 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array) #2 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array) #3 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('ALTER TABLE `qu...', Array) #4 [internal function]: Zend_Db_Adapter_Pdo_Abstract->query('ALTER TABLE `qu...') #5 /var/www/pimcore/lib/Pimcore/Db/Wrapper.php(290): call_user_func_array(Array, Array) #6 /var/www/pimcore/lib/Pimcore/Db/Wrapper.php(260): Pimcore\Db\Wrapper->callResourceMethod('query', Array) #7 /var/www/website/var/system/update/3839/scripts/postupdate.php(10): Pimcore\Db\Wrapper->__call('query', Array) #8 /var/www/pimcore/lib/Pimcore/Update.php(329): include('/var/www/websit...') #9 /var/www/pimcore/lib/Pimcore/Console/Command/InternalUpdateProcessorCommand.php(52): Pimcore\Update::executeScript('3839', 'postupdate') #10 /var/www/vendor/symfony/console/Command/Command.php(256): Pimcore\Console\Command\InternalUpdateProcessorCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #11 /var/www/vendor/symfony/console/Application.php(831): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #12 /var/www/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Console\Command\InternalUpdateProcessorCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #13 /var/www/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #14 /var/www/pimcore/cli/console.php(23): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput)) #15 {main}  Next Zend_Db_Statement_Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'reference', query was: ALTER TABLE `quantityvalue_units`     CHANGE COLUMN `referemce` `reference` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin' AFTER `conversionOffset`;      in /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:235 Stack trace: #0 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array) #1 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array) #2 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('ALTER TABLE `qu...', Array) #3 [internal function]: Zend_Db_Adapter_Pdo_Abstract->query('ALTER TABLE `qu...') #4 /var/www/pimcore/lib/Pimcore/Db/Wrapper.php(290): call_user_func_array(Array, Array) #5 /var/www/pimcore/lib/Pimcore/Db/Wrapper.php(260): Pimcore\Db\Wrapper->callResourceMethod('query', Array) #6 /var/www/website/var/system/update/3839/scripts/postupdate.php(10): Pimcore\Db\Wrapper->__call('query', Array) #7 /var/www/pimcore/lib/Pimcore/Update.php(329): include('/var/www/websit...') #8 /var/www/pimcore/lib/Pimcore/Console/Command/InternalUpdateProcessorCommand.php(52): Pimcore\Update::executeScript('3839', 'postupdate') #9 /var/www/vendor/symfony/console/Command/Command.php(256): Pimcore\Console\Command\InternalUpdateProcessorCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #10 /var/www/vendor/symfony/console/Application.php(831): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #11 /var/www/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Console\Command\InternalUpdateProcessorCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #12 /var/www/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #13 /var/www/pimcore/cli/console.php(23): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput)) #14 {main} {"origin":"Pimcore\\Db::errorHandler() on line 318","memory":"  8 MB"} []
[2017-02-13 16:14:40] core.ERROR: Array (     [message] => SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'reference', query was: ALTER TABLE `quantityvalue_units`         CHANGE COLUMN `referemce` `reference` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin' AFTER `conversionOffset`;          [method] => query     [arguments] => Array         (             [0] => ALTER TABLE `quantityvalue_units`         CHANGE COLUMN `referemce` `reference` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin' AFTER `conversionOffset`;              )  )  {"origin":"Pimcore\\Db::errorHandler() on line 322","memory":"  8 MB"} []
{"message":"","success":true}
```

### Steps to reproduce  

Make sure that your database has the following table: `quantityvalue_units` and this table has a column called `reference`.

Upgrade to version 4.4.3.

### Offending updates

The following updates should first check if the `reference` column already exists:

- `update/archive_4000/3837/postupdate.php`
- `update/archive_4000/3839/postupdate.php`

### Workaround

Remove the `reference` column before the upgrade:

```
ALTER TABLE `quantityvalue_units` drop COLUMN `reference`;
```

**Comment by brusch** [comment]
The question is why you are having already the column ... shouldn't be there. 
Maybe a merging / migration problem on your side?

**Comment by jbq** [comment]
After investigation I noticed that the update n°3837 has been introduced (with a typo) in version 4.1.2, whereas the `reference` column had already been introduced in version 4.0.0.

See for yourself the following commits:

Initial addition of the `reference` column dates back to november 2015 and is included in release 4.0.0:

```
commit 828940ffe0770cfaddfe1f2f91ad23a04ca74bbc                                                                                                                                                                                             
Author:     weisswurstkanone <josef.aichhorn@elements.at>                                                                                                                                                                                   
AuthorDate: Wed Nov 18 16:06:15 2015 +0100                                                                                                                                                                                                  
Commit:     weisswurstkanone <josef.aichhorn@elements.at>                                                                                                                                                                                   
CommitDate: Wed Nov 18 16:06:15 2015 +0100                                                                                                                                                                                                  
                                                                                                                       
    quantity value - added additional column                                                                                                                       
```

First update script to add the missing column for existing pre-4.0.0 installations was added in june 2016 and included in version 4.1.2:

```
commit 1e8004c72e0a44e231b9c5e47cede0848a1c9413                                                                                                                                                                                             
Author:     weisswurstkanone <josef.aichhorn@elements.at>                                                                                                                                                                                   
AuthorDate: Fri Jun 10 14:35:48 2016 +0200                                                                                                                                                                                                  
Commit:     weisswurstkanone <josef.aichhorn@elements.at>                                                                                                                                                                                   
CommitDate: Fri Jun 10 14:46:57 2016 +0200                                                                                                                                                                                                  
```

So I think this is not a problem on my side.  I haven't been performing any Pimcore update on my various sites and I haven't been tweaking my database either.  Problem is on Pimcore side AFAICT.

**Comment by weisswurstkanone** [comment]
Unable to reproduce
- created a completely fresh 4.0.0 instance (package downloaded from https://sourceforge.net/projects/pimcorebuilds/files/archive/3700/pimcore-build-3770.zip/download)
- followed the official update path via Extras | Update
- selected release 4.4.3
- absolutely no errors during update, everything went fine ...
- current build number is 4044

**Comment by jbq** [comment]
I just tested building the official docker image with ZIP URL for build number 3770 hardcoded in run.sh instead of latest release.

I get the same error while updating a freshly installed empty database: https://gist.github.com/jbq/5c4fb2c3f315c550313b92a224ae3ae3

I suspect a MySQL-specific behavior. I am using `mariadb-server-10.0` provided by the stock Docker image.  Are you using something else?

Could you please reopen the issue?

And BTW build 3770 is for 4.0.0 RC2, while I reported the bug for version 4.0.0, which is build 3777 but we now have evidence that both have the same issue.

**Comment by weisswurstkanone** [comment]
just one correction: I was testing build 3777 (download pimcore-build-3777.zip) but entered it wrong in the comment. please try to investigate why the exception falls through the update script

**Comment by jbq** [comment]
Same failure with build 3777, problem confirmed: https://gist.github.com/jbq/fbfed287d67fda03dc0732b694fc6059

@weisswurstkanone what do you mean with _please try to investigate why the exception falls through the update script_ I already did the whole investigation: the `reference` column of table `quantityvalue_units` is already present in version 4.0.0, so there is no point in adding it again in updates 3837 and 3839.  Adding a column that is already present is not supposed to work, I advise you to test with the latest Docker image.  What MySQL version did you use in your tests?

**Comment by jbq** [comment]
@brusch do you leave the issue closed because it won't be fixed?  Or shall it be reopened for the sake of correctness, until the issue exists?
