### ISSUE TITLE
Geopoint within block data component

### ISSUE THREAD

**Issue by drietsch** [pimcore/pimcore#1387]
### Expected behavior 
Use a geopoint data component within a block item. The geopoint element should also work within a block.
  
### Actual behavior  
Use a geopoint data component within a block item. When you search for a geopoint and then save the object an error occurs.

```text
Fatal error: Uncaught Error: Cannot use object of type Pimcore\Model\Object\Data\Geopoint as array in /home/pimcore_demo/www/pimcore/models/Object/ClassDefinition/Data/Geopoint.php:272 Stack trace: 
#0 /home/pimcore_demo/www/pimcore/models/Object/ClassDefinition/Data/Block.php(127): Pimcore\Model\Object\ClassDefinition\Data\Geopoint->marshal(Object(Pimcore\Model\Object\Data\Geopoint), Object(Pimcore\Model\Object\Person), Array) 
#1 /home/pimcore_demo/www/pimcore/models/Object/Concrete/Dao.php(215): Pimcore\Model\Object\ClassDefinition\Data\Block->getDataForResource(Array, Object(Pimcore\Model\Object\Person)) 
#2 /home/pimcore_demo/www/pimcore/models/Object/Concrete.php(198): Pimcore\Model\Object\Concrete\Dao->update() 
#3 /home/pimcore_demo/www/pimcore/models/Object/AbstractObject.php(588): Pimcore\Model\Object\Concrete->update() 
#4 /home/pimcore_demo/www/pimcore/modules/admin/controllers/ObjectController.php(1142): Pimcore\Model\Object\AbstractObject->save() 
#5 /home/pimcore_demo/www/vendor/zendframework/zendframework1/libra in /home/pimcore_demo/www/pimcore/models/Object/ClassDefinition/Data/Geopoint.php on line 272
```

**Comment by weisswurstkanone** [comment]
fixed in build #4066 (or #31 pimcore 5)
