### ISSUE TITLE
Custom report having multiple columns of same name

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#1414]
# Bug Report

Our Article objects can have multiple object bricks (technical data). I want to create a custom report with all articles in the rows and all brick fields in the columns

### Expected behavior 
Ignore additional columns with same name (like SQL does)
  
### Actual behavior  
500 error

<pre><details>
Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'o_id'' in .../vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 .../vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 .../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#2 .../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 .../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT COUNT(*)...', Array)
#4 .../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(828): Zend_Db_Adapter_Pdo_Abstract->query('SELECT COUNT(*)...', Array)
#5 [internal function]: Zend_Db_Adapter_Abstract->fetchOne('SELECT COUNT(*).. in .../vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235
</details></pre>
  
### Steps to reproduce  
1. Create a class with an object brick field
1. Create 2 bricks A and B each containing min. 1 field and allow them to be used in the class' brick field
1. create an object of given class and assign it both bricks
1. create a custom report showing all brick fields from both bricks
In my case the resulting SQL query looks like `SELECT ArtNr, brick1.*, brick2.* FROM  object_4 article INNER JOIN object_brick_store_A_4 brick1 ON article.o_id=brick1.o_id INNER JOIN object_brick_store_B_4 brick2 ON article.o_id=brick2.o_id`
While the column preview table when creating the report works find (ignoring multiple columns with same name) actually calling the report fails with above error message.

The problem is the extra wrapping around the SQL query in https://github.com/pimcore/pimcore/blob/master/pimcore/models/Tool/CustomReport/Adapter/Sql.php#L205-L211 because this cannot handle duplicate column names.

**Comment by BlackbitNeueMedien** [comment]
Solved this issue by creating views which get recreated via cronjob (to observe changed columns, bricks).
