### ISSUE TITLE
[Bug]: Can't save Objectbrick

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#14323]
### Expected behavior

Objectbrick will be saved

### Actual behavior

```
Status: 500 | Internal Server Error
URL: /admin/class/objectbrick-update
Method: PUT
Message: strlen(): Argument #1 ($string) must be of type string, bool given
Trace: 
in /var/www/html/dev/pimcore/pimcore/models/DataObject/Objectbrick/Definition.php:132
#0 /var/www/html/dev/pimcore/pimcore/models/DataObject/Objectbrick/Definition.php(132): strlen(false)
#1 /var/www/html/dev/pimcore/pimcore/models/DataObject/Objectbrick/Definition.php(158): Pimcore\Model\DataObject\Objectbrick\Definition->checkTablenames()
#2 /var/www/html/dev/pimcore/pimcore/bundles/AdminBundle/src/Controller/Admin/DataObject/ClassController.php(1214): Pimcore\Model\DataObject\Objectbrick\Definition->save()
#3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(163): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\ClassController->objectbrickUpdateAction(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/html/vendor/symfony/http-kernel/Kernel.php(184): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/html/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#7 {main}
```

### Steps to reproduce

- Create an Objectbrick with an input field
- Try to save it

**Comment by blankse** [comment]
@robertSt7 I created a PR https://github.com/pimcore/pimcore/pull/14325
