### ISSUE TITLE
[Bug]: User management doesn't work

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#14640]
### Expected behavior

Users can be saved, created and deleted 

### Actual behavior

```
Status: 500 | Internal Server Error
URL: /admin/user/delete
Method: DELETE
Message: Cannot instantiate abstract class Pimcore\Model\User\AbstractUser
Trace: 
in /var/www/html/dev/pimcore/pimcore/models/User/AbstractUser.php:48
#0 /var/www/html/dev/pimcore/pimcore/bundles/AdminBundle/src/Controller/Admin/UserController.php(246): Pimcore\Model\User\AbstractUser::getById(5)
#1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(163): Pimcore\Bundle\AdminBundle\Controller\Admin\UserController->deleteAction(Object(Symfony\Component\HttpFoundation\Request))
#2 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#3 /var/www/html/vendor/symfony/http-kernel/Kernel.php(184): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#4 /var/www/html/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#5 {main}
```

### Steps to reproduce

Try to save, create or delete an user

**Comment by robertSt7** [comment]
may be due to https://github.com/pimcore/pimcore/pull/14519
