### ISSUE TITLE
[Bug]: Can't open Custom Report 

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#14745]
### Expected behavior

Show Custom Report

### Actual behavior

```
URL: /admin/reports/custom-report/data?xaction=read&_dc=1679648408800
Method: POST
Message: Warning: Attempt to read property "type" on null
Trace: 
in /var/www/html/dev/pimcore/pimcore/models/Tool/CustomReport/Config.php:190
#0 /var/www/html/dev/pimcore/pimcore/bundles/AdminBundle/Controller/Reports/CustomReportController.php(340): Pimcore\Model\Tool\CustomReport\Config::getAdapter(NULL, Object(Pimcore\Model\Tool\CustomReport\Config))
#1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(163): Pimcore\Bundle\AdminBundle\Controller\Reports\CustomReportController->dataAction(Object(Symfony\Component\HttpFoundation\Request))
#2 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#3 /var/www/html/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#4 /var/www/html/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#5 {main}
```

### Steps to reproduce

Create a new Custom Report save it and try to open it

**Comment by robertSt7** [comment]
Possible fix: Make fields in the adapter mandatory

**Comment by torqdev** [comment]
@robertSt7 A PR was merged for this issue, did this resolve this issue for you?

**Comment by robertSt7** [comment]
> @robertSt7 A PR was merged for this issue, did this resolve this issue for you?

@torqdev Yes, thanks
