### ISSUE TITLE
[Bug]: Too few arguments to function Pimcore\Model\DataObject\AbstractObject::get(), 0 passed

### ISSUE THREAD

**Issue by DuckThom** [pimcore/pimcore#15334]
### Pimcore version

10.6.1

### Steps to reproduce

- Have pimcore/data-hub installed
- Have pimcore/data-importer installed

- Create a DataObject definition (ie. 'product') with inheritance and variants enabled
- Add an Objectbrick field to the 'product' object
- Create an Objectbrick definition and assign it to the 'product' object
- Add an input field to the Objectbrick

- Create and publish a new Object with a variant
- Add the objectbrick _only_ to the variant

- In the datahub, create a new importer
- Make the importer update field inside the objectbrick of the variant and make sure no objectbrick is created in the parent

### Expected / actual behavior

**Expected:**

The value is updated in the variant

**Actual:**

An error is thrown and the import skips updating the variant:

```
Failed to process "24345": Too few arguments to function Pimcore\Model\DataObject\AbstractObject::get(), 0 passed in /Volumes/Projects/<redacted>/pimcore/vendor/pimcore/pimcore/models/DataObject/Objectbrick/Data/AbstractData.php on line 184 and at least 1 expected
#0 /Volumes/Projects/<redacted>/pimcore/vendor/pimcore/pimcore/models/DataObject/Objectbrick/Data/AbstractData.php(184): Pimcore\Model\DataObject\AbstractObject->get()
#1 /Volumes/Projects/<redacted>/pimcore/var/classes/DataObject/Objectbrick/Data/Supplement.php(253): Pimcore\Model\DataObject\Objectbrick\Data\AbstractData->getValueFromParent('supplementSubst...')
#2 /Volumes/Projects/<redacted>/pimcore/vendor/pimcore/data-importer/src/Mapping/DataTarget/Direct.php(137): Pimcore\Model\DataObject\Objectbrick\Data\Supplement->getSupplementSubstance('')
#3 /Volumes/Projects/<redacted>/pimcore/vendor/pimcore/data-importer/src/Mapping/DataTarget/Direct.php(100): Pimcore\Bundle\DataImporterBundle\Mapping\DataTarget\Direct->checkAssignData(Object(Pimcore\Model\DataObject\Substance), Object(Pimcore\Model\DataObject\Objectbrick\Data\Supplement), 'getSupplementSu...')
#4 /Volumes/Projects/<redacted>/pimcore/vendor/pimcore/data-importer/src/Processing/ImportProcessingService.php(217): Pimcore\Bundle\DataImporterBundle\Mapping\DataTarget\Direct->assignData(Object(Pimcore\Model\DataObject\Product), Object(Pimcore\Model\DataObject\Substance))
#5 /Volumes/Projects/<redacted>/pimcore/vendor/pimcore/data-importer/src/Processing/ImportProcessingService.php(146): Pimcore\Bundle\DataImporterBundle\Processing\ImportProcessingService->processElement('product_supplem...', Array, Object(Pimcore\Bundle\DataImporterBundle\Resolver\Resolver), Array)
#6 /Volumes/Projects/<redacted>/pimcore/vendor/pimcore/data-importer/src/Command/ParallelProcessQueueCommand.php(70): Pimcore\Bundle\DataImporterBundle\Processing\ImportProcessingService->processQueueItem(24345)
#7 /Volumes/Projects/<redacted>/pimcore/vendor/webmozarts/console-parallelization/src/Parallelization.php(489): Pimcore\Bundle\DataImporterBundle\Command\ParallelProcessQueueCommand->runSingleCommand('24345', Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Volumes/Projects/<redacted>/pimcore/vendor/webmozarts/console-parallelization/src/Parallelization.php(442): Pimcore\Bundle\DataImporterBundle\Command\ParallelizationAbstractCommand->runTolerantSingleCommand('24345', Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Volumes/Projects/<redacted>/pimcore/vendor/webmozarts/console-parallelization/src/Parallelization.php(269): Pimcore\Bundle\DataImporterBundle\Command\ParallelizationAbstractCommand->executeChildProcess(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /Volumes/Projects/<redacted>/pimcore/vendor/symfony/console/Command/Command.php(298): Pimcore\Bundle\DataImporterBundle\Command\ParallelizationAbstractCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /Volumes/Projects/<redacted>/pimcore/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /Volumes/Projects/<redacted>/pimcore/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\DataImporterBundle\Command\ParallelProcessQueueCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /Volumes/Projects/<redacted>/pimcore/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\DataImporterBundle\Command\ParallelProcessQueueCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /Volumes/Projects/<redacted>/pimcore/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /Volumes/Projects/<redacted>/pimcore/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /Volumes/Projects/<redacted>/pimcore/bin/console(36): Symfony\Component\Console\Application->run()
#17 {main}
```

Reference screenshots:

![image](https://github.com/pimcore/pimcore/assets/6512901/740f2dc6-472a-43d7-b5eb-68a8cc4e3c06)
Objectbrick configuration

![image](https://github.com/pimcore/pimcore/assets/6512901/6c13bfd3-d7b6-4e44-b529-e010e6b1129e)
Variant setup ("ParentProduct" does not have an objectbrick set)

**Comment by robertSt7** [comment]
@DuckThom Sorry, I am not able to reproduce the bug. Could you please test it with the latest versions of each bundle and provide more information? Thanks

**Comment by dvesh3** [comment]
I'm not able to reproduce either with latest versions, pimcore v10.6.3 & data-import v1.8.1. Please feel free to continue the discussions.
