### ISSUE TITLE
[Bug]: After upgrade from Pimcore 10.6 to 11.0 all video editables have to be "saved" again, otherwise Pimcore won't save the document

### ISSUE THREAD

**Issue by cadeyrn** [pimcore/pimcore#15939]
### Pimcore version

11.0.8

### Steps to reproduce

1. Pimcore was on version 10.6.9.
2. Pimcore was upgraded to version 11.0.8.
3. There was code like this in the template:

```
{{ pimcore_video('video', {
  attributes: {
    poster: pimcore_video('video').getImageThumbnail('video')
  }
}) }}
```

The video editable was empty. While it still worked in the frontend, the backend showed an error:

```
Pimcore\Model\Asset::getById(): Argument #1 ($id) must be of type string|int, null given, called in /data/web/web8377/home/site/vendor/pimcore/pimcore/models/Document/Editable/Video.php on line 1050 File: /data/web/web8377/home/site/vendor/pimcore/pimcore/models/Asset.php Line: 244
#0 /data/web/web8377/home/site/vendor/pimcore/pimcore/models/Document/Editable/Video.php(1050): Pimcore\Model\Asset::getById()
#1 /data/web/web8377/home/site/vendor/pimcore/pimcore/models/Document/Editable/Video.php(1074): Pimcore\Model\Document\Editable\Video->getVideoAsset()
#2 /data/web/web8377/home/site/vendor/twig/twig/src/Extension/CoreExtension.php(1637): Pimcore\Model\Document\Editable\Video->getImageThumbnail()
#3 /data/web/web8377/home/site/var/cache/dev/twig/91/91af270042d239f4aaf92ca48f991867.php(148): twig_get_attribute()
#4 /data/web/web8377/home/site/vendor/twig/twig/src/Template.php(394): __TwigTemplate_8a448be9a22efbf491c991596d037c0a->doDisplay()
#5 /data/web/web8377/home/site/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#6 /data/web/web8377/home/site/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#7 /data/web/web8377/home/site/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render()
#8 /data/web/web8377/home/site/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render()
#9 /data/web/web8377/home/site/vendor/pimcore/pimcore/lib/Templating/TwigDefaultDelegatingEngine.php(62): Twig\Environment->render()
#10 /data/web/web8377/home/site/vendor/twig/twig/src/Extension/CoreExtension.php(1637): Pimcore\Templating\TwigDefaultDelegatingEngine->render()
#11 /data/web/web8377/home/site/var/cache/dev/twig/9a/9a143af6c72526d63acbf5e8ff72f7eb.php(233): twig_get_attribute()
#12 /data/web/web8377/home/site/vendor/twig/twig/src/Template.php(171): __TwigTemplate_c55ed133783f1f6125ba9677d22ec4c3->block_areabrickFrontend()
#13 /data/web/web8377/home/site/var/cache/dev/twig/9a/9a143af6c72526d63acbf5e8ff72f7eb.php(182): Twig\Template->displayBlock()
#14 /data/web/web8377/home/site/vendor/twig/twig/src/Template.php(171): __TwigTemplate_c55ed133783f1f6125ba9677d22ec4c3->block_areabrickWrapper()
#15 /data/web/web8377/home/site/var/cache/dev/twig/9a/9a143af6c72526d63acbf5e8ff72f7eb.php(147): Twig\Template->displayBlock()
#16 /data/web/web8377/home/site/vendor/twig/twig/src/Template.php(394): __TwigTemplate_c55ed133783f1f6125ba9677d22ec4c3->doDisplay()
#17 /data/web/web8377/home/site/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#18 /data/web/web8377/home/site/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#19 /data/web/web8377/home/site/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render()
#20 /data/web/web8377/home/site/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render()
#21 /data/web/web8377/home/site/vendor/pimcore/pimcore/lib/Templating/TwigDefaultDelegatingEngine.php(62): Twig\Environment->render()
#22 /data/web/web8377/home/site/vendor/pimcore/pimcore/lib/Document/Editable/EditableHandler.php(208): Pimcore\Templating\TwigDefaultDelegatingEngine->render()
#23 /data/web/web8377/home/site/vendor/pimcore/pimcore/models/Document/Editable/Areablock.php(248): Pimcore\Document\Editable\EditableHandler->renderAreaFrontend()
#24 /data/web/web8377/home/site/vendor/pimcore/pimcore/models/Document/Editable/Areablock.php(188): Pimcore\Model\Document\Editable\Areablock->content()
#25 /data/web/web8377/home/site/vendor/pimcore/pimcore/models/Document/Editable/Areablock.php(105): Pimcore\Model\Document\Editable\Areablock->loop()
#26 /data/web/web8377/home/site/vendor/pimcore/pimcore/models/Document/Editable/Areablock.php(93): Pimcore\Model\Document\Editable\Areablock->frontend()
#27 /data/web/web8377/home/site/vendor/pimcore/pimcore/models/Document/Editable.php(389): Pimcore\Model\Document\Editable\Areablock->admin()
#28 /data/web/web8377/home/site/vendor/pimcore/pimcore/models/Document/Editable.php(403): Pimcore\Model\Document\Editable->render()
#29 /data/web/web8377/home/site/var/cache/dev/twig/2a/2af6a6e7fdff981980385a3559167ae5.php(71): Pimcore\Model\Document\Editable->__toString()
#30 /data/web/web8377/home/site/vendor/twig/twig/src/Template.php(171): __TwigTemplate_b2249603380c9a421188a06dab251dca->block_content()
#31 /data/web/web8377/home/site/var/cache/dev/twig/6b/6b540cfa286c3bc525edeab2888170fd.php(458): Twig\Template->displayBlock()
#32 /data/web/web8377/home/site/vendor/twig/twig/src/Template.php(394): __TwigTemplate_307b3519bd552220080ac5d1e6c0f096->doDisplay()
#33 /data/web/web8377/home/site/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#34 /data/web/web8377/home/site/var/cache/dev/twig/2a/2af6a6e7fdff981980385a3559167ae5.php(50): Twig\Template->display()
#35 /data/web/web8377/home/site/vendor/twig/twig/src/Template.php(394): __TwigTemplate_b2249603380c9a421188a06dab251dca->doDisplay()
#36 /data/web/web8377/home/site/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#37 /data/web/web8377/home/site/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#38 /data/web/web8377/home/site/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render()
#39 /data/web/web8377/home/site/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render()
#40 /data/web/web8377/home/site/vendor/symfony/twig-bridge/EventListener/TemplateAttributeListener.php(62): Twig\Environment->render()
#41 /data/web/web8377/home/site/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(116): Symfony\Bridge\Twig\EventListener\TemplateAttributeListener->onKernelView()
#42 /data/web/web8377/home/site/vendor/symfony/event-dispatcher/EventDispatcher.php(220): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke()
#43 /data/web/web8377/home/site/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#44 /data/web/web8377/home/site/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(139): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#45 /data/web/web8377/home/site/vendor/symfony/http-kernel/HttpKernel.php(187): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
#46 /data/web/web8377/home/site/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#47 /data/web/web8377/home/site/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle()
#48 /data/web/web8377/home/site/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle()
#49 {main}
```

I was able to fix it with a null check for the poster property:

```
{{ pimcore_video('video', {
  attributes: {
    poster: not pimcore_video('video') ? pimcore_video('video').getImageThumbnail('video') : null
  }
}) }}
```

After then, Pimcore was able to show the element without error message. But it was not possible to save the document due to the following error:

```
Status: 500 | 
URL: /admin/page/save?task=publish
Method: PUT
Message: Pimcore\Model\Asset::getById(): Argument #1 ($id) must be of type string|int, null given, called in /data/web/web8377/home/site/vendor/pimcore/pimcore/models/Document/Editable/Video.php on line 290
Trace: 
in /data/web/web8377/home/site/vendor/pimcore/pimcore/models/Asset.php:244
#0 /data/web/web8377/home/site/vendor/pimcore/pimcore/models/Document/Editable/Video.php(290): Pimcore\Model\Asset::getById()
#1 /data/web/web8377/home/site/vendor/pimcore/pimcore/models/Document/PageSnippet.php(275): Pimcore\Model\Document\Editable\Video->resolveDependencies()
#2 /data/web/web8377/home/site/vendor/pimcore/pimcore/models/Document.php(503): Pimcore\Model\Document\PageSnippet->resolveDependencies()
#3 /data/web/web8377/home/site/vendor/pimcore/pimcore/models/Document/PageSnippet.php(157): Pimcore\Model\Document->update()
#4 /data/web/web8377/home/site/vendor/pimcore/pimcore/models/Document.php(331): Pimcore\Model\Document\PageSnippet->update()
#5 /data/web/web8377/home/site/vendor/pimcore/pimcore/models/Document/PageSnippet.php(145): Pimcore\Model\Document->save()
#6 /data/web/web8377/home/site/vendor/pimcore/pimcore/models/Document/Page.php(122): Pimcore\Model\Document\PageSnippet->save()
#7 /data/web/web8377/home/site/vendor/pimcore/admin-ui-classic-bundle/src/Controller/Admin/Document/DocumentControllerBase.php(397): Pimcore\Model\Document\Page->save()
#8 /data/web/web8377/home/site/vendor/pimcore/admin-ui-classic-bundle/src/Controller/Admin/Document/PageController.php(151): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\DocumentControllerBase->saveDocument()
#9 /data/web/web8377/home/site/vendor/symfony/http-kernel/HttpKernel.php(182): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\PageController->saveAction()
#10 /data/web/web8377/home/site/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#11 /data/web/web8377/home/site/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle()
#12 /data/web/web8377/home/site/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle()
#13 {main}
```

The same happened even after reducing the code to:

```
{{ pimcore_video('video') }}
```

But after pressing the edit icon of the video editable in Pimcore and pressing the save button in the video dialog (without any change) it is possible again to save the document.

Of course, it's a lot of work if you have to check many documents with many video editables and to do this for every single video element.

I guess pressing the save button in the video dialog makes sure that all the data have the correct type. Can this be done as part of a migration during the Pimcore upgrade?

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/15941
