### ISSUE TITLE
[Bug]: Class field with name "text" gets overwritten by object key

### ISSUE THREAD

**Issue by Myrmidonut** [pimcore/pimcore#16259]
### Pimcore version

11.1.0

### Steps to reproduce

Create a field called "text" in an object class (input, textarea, wyswyg, number).
Create an object and type something into the "text" field.
Save and publish and reload the object.

### Actual Behavior

The field "text" will be overwritten by the object key.

### Expected Behavior

The field "text" stays on the value that was typed.

This happens at least since version 11.1.0, maybe before that as well.
I tried it with different filed types, at least input, textarea, wyswyig and number are affected. Number throws an error message in the frontend when I type in "1":

Message: Pimcore\Model\DataObject\FAQ::setText(): Argument #1 ($text) must be of type ?float, string given, called in /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php on line 186

I assume it immediately writes the key into the filed and runs into a validation error.

This does not happen when the "text" filed is inside localfields.

**Comment by Myrmidonut** [comment]
A number field called "text" inside localizedfields is affected by this as well, there might be more field types affected.

**Comment by Myrmidonut** [comment]
Here is the full error message. The key of the dataobject is "demo".

`Timestamp: Wed Nov 15 2023 12:51:50 GMT+0100 (Mitteleuropäische Normalzeit)
Status: 500 | Internal Server Error
URL: /admin/object/save?task=publish
Method: PUT
Message: Pimcore\Model\DataObject\FAQ::setText(): Argument #1 ($text) must be of type ?float, string given, called in /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php on line 186
Trace: 
in /var/www/html/var/classes/DataObject/FAQ.php:195
#0 /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(186): Pimcore\Model\DataObject\FAQ->setText('demo')
#1 /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Controller/Admin/DataObject/DataObjectController.php(1393): Pimcore\Model\AbstractModel->setValue('text', 'demo')
#2 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(181): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->saveAction(Object(Symfony\Component\HttpFoundation\Request))
#3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#4 /var/www/html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#6 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#7 /var/www/html/public/index.php(19): require_once('/var/www/html/v...')
#8 {main}`

**Comment by alexej-d** [comment]
I can confirm the same error with an wysiwyg field

**Comment by dvesh3** [comment]
Regression of https://github.com/pimcore/pimcore/pull/15917
