### ISSUE TITLE
[Bug]: "classes-rebuild -d" fails on deployment

### ISSUE THREAD

**Issue by Pierre-Datasolution** [pimcore/pimcore#17388]
### Pimcore version

11.3.1

### Steps to reproduce

- Delete a class (ListOfOptions in following traces) on development environment
- Push code to your git and deploy to production server (Pimcore\Model\DataObject\ListOfOptions has been deleted)
- Execute "bin/console pimcore:deployment:classes-rebuild -d" on production server

### Actual Behavior

When executing "classes-rebuild -d" on server, job tries to delete class ListOfOptions but also tries to build objet of class during process (but Pimcore\Model\DataObject\ListOfOptions is not present anymore...)

```
$ bin/console pim:dep:cla -d

 You are going to delete classes that don't have class-definitions anymore. This could lead to data loss! Do you want to continue? (yes/no) [no]:
 > yes

Pimcore\Loader\ImplementationLoader\Exception\UnsupportedException: Loader for "Pimcore\Model\DataObject\ListOfOptions" was not found in /var/www/html/vendor/pimcore/pimcore/lib/Loader/ImplementationLoader/ImplementationLoader.php:90
Stack trace:
#0 /var/www/html/vendor/pimcore/pimcore/lib/Model/Factory.php(42): Pimcore\Loader\ImplementationLoader\ImplementationLoader->build('Pimcore\\Model\\D...', Array)
#1 /var/www/html/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(241): Pimcore\Model\Factory->build('Pimcore\\Model\\D...')
#2 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Listing/Dao.php(66): Pimcore\Model\DataObject\AbstractObject::getById(820145)
#3 [internal function]: Pimcore\Model\DataObject\Listing\Dao->load()
#4 /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(220): call_user_func_array(Array, Array)
#5 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition.php(496): Pimcore\Model\AbstractModel->__call('load', Array)
#6 /var/www/html/vendor/pimcore/pimcore/lib/Model/DataObject/ClassDefinition/ClassDefinitionManager.php(56): Pimcore\Model\DataObject\ClassDefinition->delete()
#7 /var/www/html/vendor/pimcore/pimcore/bundles/CoreBundle/src/Command/ClassesRebuildCommand.php(89): Pimcore\Model\DataObject\ClassDefinition\ClassDefinitionManager->cleanUpDeletedClassDefinitions()
#8 /var/www/html/vendor/symfony/console/Command/Command.php(326): Pimcore\Bundle\CoreBundle\Command\ClassesRebuildCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/symfony/console/Application.php(1096): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(126): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\ClassesRebuildCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\ClassesRebuildCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(80): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php(49): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run()
#16 /var/www/html/bin/console(20): require_once('/var/www/html/v...')
#17 {main}

In ImplementationLoader.php line 90:

  Loader for "Pimcore\Model\DataObject\ListOfOptions" was not found


pimcore:deployment:classes-rebuild [-c|--create-classes] [-d|--delete-classes] [-f|--force]
```

### Expected Behavior

Data and class tables should be deleted in the database without errors

**Comment by blankse** [comment]
@Pierre-Datasolution If you first delete all objects of ListOfOptions in the production system and then deploy without the ListOfOptions class, will it work?

**Comment by Pierre-Datasolution** [comment]
> @Pierre-Datasolution If you first delete all objects of ListOfOptions in the production system and then deploy without the ListOfOptions class, will it work?

@blankse Thanks for reading. Maybe, but deployment process is automatic and "classes-rebuild -d" has always done the job till now... :-)

**Comment by blankse** [comment]
@Pierre-Datasolution I have never tried to delete the class in this way on the production server if objects still existed. I don't think this has ever worked, because Pimcore needs the class to delete the objects.

**Comment by dpfaffenbauer** [comment]
@blankse it used to work in the past, but it got broken somewhere sometime. so we usually never delete classes or try at least to not delete them ;)

**Comment by michalananapps** [comment]
Maybe migration Pimcore\Bundle\CoreBundle\Migrations\Version20240708083500 is the cause of the problem? It tries to rebuild classes (Pimcore\Model\DataObject\*), but migrations can be executed with different permissions than other commands. 

In my opinion such things in doctrine migrations are quite crazy (and deleting previous entries from `migration_versions` i so... risky)

**Comment by GeorgII-web** [comment]
Got related issue, prod deploy fails with "Class pimcore/model/data object/anyclassname not found" after upgrade to 11.3.1.
The only way to get a working state is to use vendor/bin/pimcore-install before.
DataObjects were not changed, only upgrade of the pimcore package.
Any suggestions what to check next?

**Comment by NiklasBr** [comment]
It seems this Version20240708083500 migration is a bit strange:

```
09:37:47 [error] Migration Pimcore\Bundle\CoreBundle\Migrations\Version20240708083500 failed during Execution. Error: "Definitions in /var/www/pimcore/config/pimcore folder cannot be overwritten"
09:37:47 
09:37:47 In CustomLayout.php line 171:
09:37:47                                                                                
09:37:47   Definitions in /var/www/pimcore/config/pimcore folder cannot be overwritten  
09:37:47                                                                                
09:37:47 
09:37:47 doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--no-all-or-nothing] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--prefix [PREFIX]] [--] [<version>]
09:37:47 
```

**Comment by podarcis** [comment]
> It seems this Version20240708083500 migration is a bit strange:

@NiklasBr Indeed. The message `Definitions in /var/www/pimcore/config/pimcore folder cannot be overwritten` is true for `ClassDefinition|Objectbrick|Fieldcollection`, as their `isWritable()` all check for `PIMCORE_CLASS_DEFINITION_WRITABLE=1`. However, the `CustomLayout`'s `isWritable()` checks for writable config location (Symfony vs. Settings-Store) as therefore the message is misleading I guess.

**Comment by Geni2** [comment]
Hi, I just updated pimcore from v11.3.0 to 11.4.1 and got this issue: https://github.com/pimcore/pimcore/issues/17388#issuecomment-2320366221, has somebody managed to overcome this issue?

**Comment by NiklasBr** [comment]
The below code in the migration will never work, because this it is impossible to prepare it with `bin/console doctrine:migrations:version --add Migrations/Version20240708083500` because the migration is not available until it is deployed, causing a catch-22.

https://github.com/pimcore/pimcore/blob/322366f2d0d7613a0ce7ac796092f733b165008f/bundles/CoreBundle/src/Migrations/Version20240708083500.php#L71-L77

To "resolve" it we were forced by this bug to do a broken deploy, then rush to log in to the server, run the command, then do a new deploy.

**Comment by Geni2** [comment]
Thanks @NiklasBr for your response, I think for my project is safer to do a rollback to 11.3.0 until this issue is fixed

**Comment by MarcoLeko** [comment]
We do encounter the same issue and do not know how to solve this :/
@NiklasBr could you kindly describe your workaround step-by-step?

**Comment by NiklasBr** [comment]
Yeah, unfortunately the bug is still present as of 11.5.1.

We had to manually add the migration as completed directly to the DB with an SQL query, and not `bin/console doctrine:migrations:version --add …`:

```sql
INSERT INTO `migration_versions` (`version`, `executed_at`, `execution_time`)
VALUES ('Pimcore\\Bundle\\CoreBundle\\Migrations\\Version20240708083500', '2025-01-16 10:10:10', '0');

```

**Comment by kingjia90** [comment]
This should be resolved by https://github.com/pimcore/pimcore/pull/18393 (upcoming 11.5.5)

> It seems this Version20240708083500 migration is a bit strange:
> 
> ```
> 09:37:47 [error] Migration Pimcore\Bundle\CoreBundle\Migrations\Version20240708083500 failed during Execution. Error: "Definitions in /var/www/pimcore/config/pimcore folder cannot be overwritten"
> 09:37:47 
> 09:37:47 In CustomLayout.php line 171:
> 09:37:47                                                                                
> 09:37:47   Definitions in /var/www/pimcore/config/pimcore folder cannot be overwritten  
> 09:37:47                                                                                
> 09:37:47 
> 09:37:47 doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--no-all-or-nothing] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--prefix [PREFIX]] [--] [<version>]
> 09:37:47 
> ```

**Comment by kingjia90** [comment]
I guess this can be considered as resolved, right? Closing for the moment, if there's anything else popping up, let me know

**Comment by creativehubspace** [comment]
This issue seems to have resurfaced in Pimcore 12 (v2025.2)

`10:17:06 [notice] Could not write class definition file. Please set PIMCORE_CLASS_DEFINITION_WRITABLE env.
10:17:06 If you already have migrate the definitions you can skip this migration via "php bin/console doctrine:migrations:version --add Pimcore\Bundle\CoreBundle\Migrations\Version20240708083500"
10:17:06 [error] Migration Pimcore\Bundle\CoreBundle\Migrations\Version20240708083500 failed during Execution. Error: "Definitions in /var/www/pimcore/config/pimcore folder cannot be overwritten"
10:17:06 
10:17:06 In CustomLayout.php line 169:
10:17:06                                                                                
10:17:06   Definitions in /var/www/pimcore/config/pimcore folder cannot be overwritten  `

My config is as follows:

`pimcore:
    config_location:
        object_custom_layouts:
            write_target:
                type: 'symfony-config'
                options:
                    directory: '/var/www/pimcore/var/config/custom_object_layouts'
        image_thumbnails:
            write_target:
                type: 'symfony-config'
                options:
                    directory: '/var/www/pimcore/var/config/image_thumbnails'
        predefined_properties:
            write_target:
                type: 'symfony-config'
                options:
                    directory: '/var/www/pimcore/var/config/predefined_properties'
        predefined_asset_metadata:
            write_target:
                type: 'symfony-config'
                options:
                    directory: '/var/www/pimcore/var/config/predefined_asset_metadata'
        perspectives:
            write_target:
                type: 'symfony-config'
                options:
                    directory: '/var/www/pimcore/var/config/perspectives'
        custom_views:
            write_target:
                type: 'symfony-config'
                options:
                    directory: '/var/www/pimcore/var/config/custom_views'
        select_options:
            write_target:
                type: 'symfony-config'
                options:
                    directory: '/var/www/pimcore/var/config/select_options'`

**Comment by creativehubspace** [comment]
The issue seems to stem from [L124](https://github.com/pimcore/pimcore/blob/v12.1.4/lib/Config/LocationAwareConfigRepository.php#L124).

I use Jenkins as the CI/CD pipeline and when the migrations run, that's when the error `[error] Migration Pimcore\Bundle\CoreBundle\Migrations\Version20240708083500 failed during Execution. Error: "Definitions in /var/www/pimcore/config/pimcore folder cannot be overwritten"` occurs since the debug mode is false.

However, when I manually run the migrations like `APP_DEBUG=true php bin/console doctrine:migrations:migrate` all the migrations run successfully.

**Comment by kingjia90** [comment]
Thank you for reporting.

So far, it looks like falls under the documented case of https://docs.pimcore.com/platform/Pimcore/Deployment/Configuration_Environments/#production-environment-with-symfony-config and 

It is intentionally this way to be read-only, maybe we can improve the output message from the Migration and the documentation but it is not considered as a bug.
