### ISSUE TITLE
[Bug]: Sorting or filtering "Quantity Value Field" of ObjectBrick in Grid View not working

### ISSUE THREAD

**Issue by plixus** [pimcore/pimcore#17467]
### Pimcore version

v11.3.1.1 / v2024.2

### Steps to reproduce

Could be a duplicate or related to #17422 

1. Login into the public demo.
2. Open a Car Grid view. (like [this](https://demo.pimcore.com/admin/login/deeplink?object_27_folder))
3. Add a Quantity Value Field from an ObjectBrick to the Grid View (like bodywork.cargoCapacity)
4. Click on the newly appeared table header to sort the column
5. A "database error message" appears (Message: Database error, see logs for details)

on my local machine the error message is like:
`Message: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dimensions.diameter' in 'order clause'
Trace: 
in /var/www/html/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:67
#0 /var/www/html/vendor/doctrine/dbal/src/Connection.php(1939): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query))
#1 /var/www/html/vendor/doctrine/dbal/src/Connection.php(1881): Doctrine\DBAL\Connection->handleDriverException(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query))
#2 /var/www/html/vendor/doctrine/dbal/src/Connection.php(1106): Doctrine\DBAL\Connection->convertExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\Exception), 'SELECT object_l...', Array, Array)
#3 /var/www/html/vendor/doctrine/dbal/src/Connection.php(953): Doctrine\DBAL\Connection->executeQuery('SELECT object_l...', Array, Array)
#4 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Listing/Dao.php(105): Doctrine\DBAL\Connection->fetchFirstColumn('SELECT object_l...', Array, Array)
#5 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Listing/Concrete/Dao.php(45): Pimcore\Model\DataObject\Listing\Dao->loadIdList()
#6 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Listing/Dao.php(62): Pimcore\Model\DataObject\Listing\Concrete\Dao->loadIdList()
#7 [internal function]: Pimcore\Model\DataObject\Listing\Dao->load()
#8 /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(220): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Controller/Admin/DataObject/DataObjectActionsTrait.php(121): Pimcore\Model\AbstractModel->__call('load', Array)
#10 /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Controller/Admin/DataObject/DataObjectController.php(1717): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->gridProxy(Array, 'object', Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher), Object(Pimcore\Bundle\AdminBundle\Helper\GridHelperService), Object(Pimcore\Localization\LocaleService))
#11 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(181): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->gridProxyAction(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher), Object(Pimcore\Bundle\AdminBundle\Helper\GridHelperService), Object(Pimcore\Localization\LocaleService), Object(Pimcore\Bundle\AdminBundle\Security\CsrfProtectionHandler))
#12 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#13 /var/www/html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#15 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#16 /var/www/html/public/index.php(19): require_once('/var/www/html/v...')
#17 {main}`

### Actual Behavior

Error if you want to sort or filter the grid view by a quantity value field

### Expected Behavior

No Error if you want to sort or filter the grid view by a quantity value field.

**Comment by SimonCremer** [comment]
This one is not restricted to the QuantityValue Datatype. As far as I can see the error occurs on every DataType as soon as the field comes from a brick. 
Any chance that this is getting fixed because searching, filtering and sorting is a basic and heavy used feature.

After a quick investigation I can see that, in my case, the table name is quoted twice which results in a sql error. The first quote takes place in `GridHelperService: $brickPrefix = $db->quoteIdentifier([...]`
The second quote comes from `RelationFilterConditionParser:$db->quoteIdentifier($name)` where `$name` is the already quoted value.
