### ISSUE TITLE
[Pimcore 5] Fatal error when including startup.php in one script and startup_cli.php in another

### ISSUE THREAD

**Issue by janwalther** [pimcore/pimcore#1759]
Beside the normal Pimcore I have some CLI scripts which include pimcore/config/startup_cli.php instead of pimcore/config/startup.php.
Being in dev mode the following error happens reproduable when loading normal Pimcore (which uses startup.php) and thereafter calling a script which only includes startup_cli.php.
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/clients/client1/web5/web/var/cache/dev/appDevDebugProjectContainer.php:9294
Stack trace:
#0 /var/www/clients/client1/web5/web/pimcore/lib/Pimcore/Kernel.php(110): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#1 /var/www/clients/client1/web5/web/pimcore/config/kernel.php(25): Pimcore\Kernel->boot()
#2 /var/www/clients/client1/web5/web/pimcore/config/startup_cli.php(40): include_once('/var/www/client...')
#3 /var/www/clients/client1/web5/web/vendor/blackbit/Pim/cli/pimimport.php(17): include_once('/var/www/client...')
#4 {main}
  thrown in /var/www/clients/client1/web5/web/var/cache/dev/appDevDebugProjectContainer.php on line 9294

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/clients/client1/web5/web/var/cache/dev/appDevDebugProjectContainer.php on line 9294

Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/clients/client1/web5/web/var/cache/dev/appDevDebugProjectContainer.php on line 9294

Call Stack:
    0.0428    4707008   1. Symfony\Component\Debug\ErrorHandler->handleException() /var/www/clients/client1/web5/web/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php:0
```

In web/var/cache/dev/appDevDebugProjectContainer.php:9294 is:
```
public function buildNavigation(\Pimcore\Model\Document $activeDocument, ?\Pimcore\Model\Document $navigationRootDocument = null, ?string $htmlMenuPrefix = null, ?callable $pageCallback = null, $cache = true) : \Pimcore\Navigation\Container
```

We are using PHP version 7.1.6 and Pimcore 5.0.0-BETA1 Build: 72

**Comment by mgomse** [comment]
@janwalther are you sure that you use correct PHP version for running CLI script? Maybe you have got few php versions and default `php` is not 7.1.6?

I'm asking because nullable type is a [php 7.1 feature](http://php.net/manual/en/migration71.new-features.php#migration71.new-features.nullable-types)

**Comment by brusch** [comment]
yes, ... really seems to be a PHP version issue. 
Please try `php -v`
