### ISSUE TITLE
[Bug]: SVGs are overwritten bei inkscape/imagick

### ISSUE THREAD

**Issue by Myrmidonut** [pimcore/pimcore#17642]
### Pimcore version

v2024.2 but also in 6.5.3

### Steps to reproduce

Upload a SVG file to the assets.
Open the SVG inside Pimcore.

### Actual Behavior

The SVG becomes unreadable because it gets overwritten with the following content:

`sh: inkscape: command not found`

### Expected Behavior

A SVG can be opened without altercations to the file.

I am not sure where this Problem comes from. I have noticed that this started happening in the last one or two weeks. And it is happening on a very old Pimcore 6 Website too. Which leads me to believe that it is related to our hosting infrastructure.

Has anyone experienced something like this?

It looks like the inkscape binary is missing. Imagick is running on version 6.9.13-10 Q16 x86_64 18376.

This happens when I upload a SVG and open it in Pimcore. Only uploading and then opening the SVG outside of Pimcore preserves the file.

But why would Pimcore overwrite a SVG in the first place?

Output from dev.log:

```
[2024-09-19T13:35:36.632714+02:00] admin_statistics.INFO: Pimcore\Bundle\AdminBundle\Controller\Admin\Asset\AssetController::addAssetAction 
[4,"pimcore_admin_asset_addasset",[],{"parentId":"4","dir":"","allowOverwrite":"0","filename":"logo-a4-pos.svg","csrfToken":"5efb2a7fca1cab2d670deb3043185caf40e338d5"}] []


[2024-09-19T13:36:41.057234+02:00] pimcore.ERROR: Unable to load image /httpdocs/project/public/var/assets/dev/logo-a4-pos.svg: 
ImagickException: unable to read image data `/httpdocs/project/public/var/assets/dev/logo-a4-pos.svg' @ error/svg.c/RenderRSVGImage/462 
in /httpdocs/project/vendor/pimcore/pimcore/lib/Image/Adapter/Imagick.php:82 
Stack trace: 
#0 /httpdocs/project/vendor/pimcore/pimcore/lib/Image/Adapter/Imagick.php(82): Imagick->readImage('/home/httpd/vho...') 
#1 /httpdocs/project/vendor/pimcore/pimcore/models/Asset/Image.php(266): Pimcore\Image\Adapter\Imagick->load('/home/httpd/vho...', Array) 
#2 /httpdocs/project/vendor/pimcore/pimcore/models/Asset/Image.php(308): Pimcore\Model\Asset\Image->getDimensions() 
#3 /httpdocs/project/vendor/pimcore/admin-ui-classic-bundle/src/Controller/Admin/Asset/AssetController.php(174): Pimcore\Model\Asset\Image->getWidth() 
#4 /httpdocs/project/vendor/symfony/http-kernel/HttpKernel.php(181): Pimcore\Bundle\AdminBundle\Controller\Admin\Asset\AssetController->getDataByIdAction(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher)) 
#5 /httpdocs/project/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) 
#6 /httpdocs/project/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#7 /httpdocs/project/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) 
#8 /httpdocs/project/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run() 
#9 /httpdocs/project/public/index.php(19): require_once('/home/httpd/vho...') 
#10 {main} [] []


[2024-09-19T13:36:41.062219+02:00] php.DEBUG: Warning: exif_read_data(logo-a4-pos.svg): File not supported 
{"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/httpdocs/project/vendor/pimcore/pimcore/models/Asset/MetaData/EmbeddedMetaDataTrait.php","line":115,"trace":
[{"file":"/httpdocs/project/vendor/pimcore/pimcore/models/Asset/MetaData/EmbeddedMetaDataTrait.php","line":85,"function":"getEXIFData","class":"Pimcore\\Model\\Asset\\Image","type":"->"}],"count":1}}} []


[2024-09-19T13:36:42.007346+02:00] pimcore.ERROR: Unable to load image /httpdocs/project/public/var/assets/dev/logo-a4-pos.svg: 
ImagickException: unable to read image data `/httpdocs/project/public/var/assets/dev/logo-a4-pos.svg' @ error/svg.c/RenderRSVGImage/462 
in /httpdocs/project/vendor/pimcore/pimcore/lib/Image/Adapter/Imagick.php:82 
Stack trace: 
#0 /httpdocs/project/vendor/pimcore/pimcore/lib/Image/Adapter/Imagick.php(82): Imagick->readImage('/home/httpd/vho...') 
#1 /httpdocs/project/vendor/pimcore/pimcore/models/Asset/Image/Thumbnail/Processor.php(276): Pimcore\Image\Adapter\Imagick->load('/home/httpd/vho...', Array) 
#2 /httpdocs/project/vendor/pimcore/pimcore/models/Asset/Image/Thumbnail.php(130): Pimcore\Model\Asset\Image\Thumbnail\Processor::process(Object(Pimcore\Model\Asset\Image), Object(Pimcore\Model\Asset\Image\Thumbnail\Config), '/home/httpd/vho...', false, false) 
#3 /httpdocs/project/vendor/pimcore/pimcore/models/Asset/Thumbnail/ImageThumbnailTrait.php(110): Pimcore\Model\Asset\Image\Thumbnail->generate(false) 
#4 /httpdocs/project/vendor/pimcore/pimcore/models/Asset/Thumbnail/ImageThumbnailTrait.php(93): Pimcore\Model\Asset\Image\Thumbnail->getPathReference(false) 
#5 /httpdocs/project/vendor/pimcore/admin-ui-classic-bundle/src/Controller/Admin/Asset/AssetController.php(1225): Pimcore\Model\Asset\Image\Thumbnail->getStream() 
#6 /httpdocs/project/vendor/symfony/http-kernel/HttpKernel.php(181): Pimcore\Bundle\AdminBundle\Controller\Admin\Asset\AssetController->getImageThumbnailAction(Object(Symfony\Component\HttpFoundation\Request)) 
#7 /httpdocs/project/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) 
#8 /httpdocs/project/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#9 /httpdocs/project/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) 
#10 /httpdocs/project/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run() 
#11 /httpdocs/project/public/index.php(19): require_once('/home/httpd/vho...') 
#12 {main} [] []


[2024-09-19T13:36:42.009933+02:00] pimcore.ERROR: Couldn't create thumbnail of image /dev/logo-a4-pos.svg: 
Exception: Unable to generate thumbnail for asset 82 from source image /httpdocs/project/public/var/assets/dev/logo-a4-pos.svg 
in /httpdocs/project/vendor/pimcore/pimcore/models/Asset/Image/Thumbnail/Processor.php:277 
Stack trace: 
#0 /httpdocs/project/vendor/pimcore/pimcore/models/Asset/Image/Thumbnail.php(130): Pimcore\Model\Asset\Image\Thumbnail\Processor::process(Object(Pimcore\Model\Asset\Image), Object(Pimcore\Model\Asset\Image\Thumbnail\Config), '/home/httpd/vho...', false, false) 
#1 /httpdocs/project/vendor/pimcore/pimcore/models/Asset/Thumbnail/ImageThumbnailTrait.php(110): Pimcore\Model\Asset\Image\Thumbnail->generate(false) 
#2 /httpdocs/project/vendor/pimcore/pimcore/models/Asset/Thumbnail/ImageThumbnailTrait.php(93): Pimcore\Model\Asset\Image\Thumbnail->getPathReference(false) 
#3 /httpdocs/project/vendor/pimcore/admin-ui-classic-bundle/src/Controller/Admin/Asset/AssetController.php(1225): Pimcore\Model\Asset\Image\Thumbnail->getStream() 
#4 /httpdocs/project/vendor/symfony/http-kernel/HttpKernel.php(181): Pimcore\Bundle\AdminBundle\Controller\Admin\Asset\AssetController->getImageThumbnailAction(Object(Symfony\Component\HttpFoundation\Request)) 
#5 /httpdocs/project/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) 
#6 /httpdocs/project/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#7 /httpdocs/project/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) 
#8 /httpdocs/project/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run() 
#9 /httpdocs/project/public/index.php(19): require_once('/home/httpd/vho...') 
#10 {main} [] []
```

**Comment by Myrmidonut** [comment]
I managed to fix this issue by commenting out all lines regarding SVGs in the delegates.xml file for ImageMagick (/etc/ImageMagick-6/delegates.xml)

Maybe an update to ImageMagick-7 would solve the issue as well.

This is a similar issue that helped me get to the bottom of this:
[https://github.com/ImageMagick/ImageMagick/issues/7244](https://github.com/ImageMagick/ImageMagick/issues/7244)
