### ISSUE TITLE
Fieldcollection - block - localizedfield

### ISSUE THREAD

**Issue by jansarmir** [pimcore/pimcore#1840]
i have structure of fieldcollection from block with localizedfield
![screenshot from 2017-08-21 10-33-59](https://user-images.githubusercontent.com/13581247/29510801-645db822-865d-11e7-82fb-12a8c5035b2a.png)

saving object with this fieldcollection filled with data, gets this problem [build 4094]
```
[21-Aug-2017 10:29:20 Europe/Bratislava] PHP Fatal error:  Uncaught Error: Call to undefined method Pimcore\Model\Object\ClassDefinition\Data\Fieldcollections::getFieldDefinition() in /var/www/sarmir.sk/pimcore/models/Object/Localizedfield.php:344
Stack trace:
#0 /var/www/sarmir.sk/pimcore/models/Object/ClassDefinition/Data/Localizedfields.php(231): Pimcore\Model\Object\Localizedfield->setLocalizedValue('description', 'Energetick\xC3\xA1 \xC5\xA1...', 'sk_SK')
#1 /var/www/sarmir.sk/pimcore/models/Object/ClassDefinition/Data/Block.php(282): Pimcore\Model\Object\ClassDefinition\Data\Localizedfields->getDataFromEditmode(Array, Object(Pimcore\Model\Object\DisArticle), Array)
#2 /var/www/sarmir.sk/pimcore/models/Object/ClassDefinition/Data/Fieldcollections.php(185): Pimcore\Model\Object\ClassDefinition\Data\Block->getDataFromEditmode(Array, Object(Pimcore\Model\Object\DisArticle), Array)
#3 /var/www/sarmir.sk/pimcore/modules/admin/controllers/ObjectController.php(1084): Pimcore\Model\Object\ClassDefinition\Data\Fieldcollections->getDataFromEditmode(Array, Object(Pimcore\M in /var/www/sarmir.sk/pimcore/models/Object/Localizedfield.php on line 344
```

i tried  to wrap it with method test in /var/www/sarmir.sk/pimcore/models/Object/Localizedfield.php:344
first saving was correct, but resaving it, got conversion type error

reproducing on demo [build 4094] i got this problem
```
Fatal error:  Uncaught Exception: Call to undefined method getBlock in class Pimcore\Model\Object\Article in /home/pimcore_demo/www/pimcore/lib/Pimcore/Model/AbstractModel.php:261
Stack trace:
#0 /home/pimcore_demo/www/pimcore/models/Object/AbstractObject.php(1218): Pimcore\Model\AbstractModel->__call('getBlock', Array)
#1 /home/pimcore_demo/www/pimcore/models/Object/ClassDefinition/Data.php(1078): Pimcore\Model\Object\AbstractObject->__call('getBlock', Array)
#2 /home/pimcore_demo/www/pimcore/models/Object/ClassDefinition/Data/Localizedfields.php(218): Pimcore\Model\Object\ClassDefinition\Data->getDataFromObjectParam(Object(Pimcore\Model\Object\Article), Array)
#3 /home/pimcore_demo/www/pimcore/models/Object/ClassDefinition/Data/Block.php(282): Pimcore\Model\Object\ClassDefinition\Data\Localizedfields->getDataFromEditmode(Array, Object(Pimcore\Model\Object\Article), Array)
#4 /home/pimcore_demo/www/pimcore/models/Object/ClassDefinition/Data/Fieldcollections.php(185): Pimcore\Model\Object\ClassDefinition\Data\Block->getDat in /home/pimcore_demo/www/pimcore/lib/Pimcore/Model/AbstractModel.php on line 261
```

blocks are perfect idea, i like it, specialy with localization, but iam not able to help to fix this

**Comment by weisswurstkanone** [comment]
Unfortunately, the described setup:

Object -> Fieldcollection (parameterized through index) -> Localized Fields (language) -> Block (again index)

is very complex and currently not supported. From an editor point of view this would be similar as fieldcollections inside fieldcollections. Taking localizedfields into accont makes it even more difficult.

We will keep this in mind as improvement for pimcore 5.

Many thanks!
