### ISSUE TITLE
clear cache button in admin gui throws a Internal Server Error in v5.1

### ISSUE THREAD

**Issue by js-aw** [pimcore/pimcore#2452]
The Clear Cache Button under Extensions or Admin > Cache > Clear-Cache produces the following error: 

```
Server threw exception - could not perform action. Please reload the admin interface and try again.

Timestamp: Mon Jan 15 2018 09:07:32 GMT+0100 (CET)
Status: 500 | Internal Server Error
URL: /admin/settings/clear-cache
Message: 

Warning:  Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: require(/var/www/demo/var/cache/dev/ContainerVo4xx1a/getPimcoreAdmin_SerializerService.php): failed to open stream: No such file or directory in /var/www/demo/var/cache/dev/ContainerVo4xx1a/appDevDebugProjectContainer.php:1770
Stack trace:
#0 /var/www/demo/var/cache/dev/ContainerVo4xx1a/appDevDebugProjectContainer.php(1770): require()
#1 /var/www/demo/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(297): ContainerVo4xx1a\appDevDebugProjectContainer->load('/var/www/demo/...')
#2 /var/www/demo/pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/AdminController.php(126): Symfony\Component\DependencyInjection\Container->get('pimcore_admin.s...')
#3 /var/www/demo/pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/AdminController.php(177): Pimcore\Bundle\AdminBundle\Controller\AdminController->encodeJson(Array, Array, 15, true)
#4 /var/www/demo/pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/Settin in /var/www/demo/var/cache/dev/ContainerVo4xx1a/appDevDebugProjectContainer.php on line 1770

Fatal error:  ContainerVo4xx1a\appDevDebugProjectContainer::load(): Failed opening required '/var/www/demo/var/cache/dev/ContainerVo4xx1a/getPimcoreAdmin_SerializerService.php' (include_path='/var/www/demo/vendor/pear/net_url2:.:/usr/share/php') in /var/www/demo/var/cache/dev/ContainerVo4xx1a/appDevDebugProjectContainer.php on line 1770
```

Testet with a clean 5.1 and a upgraded installation. In 5.0.2 it works as expected.

**Comment by maff** [comment]
Thanks for reporting! For reference: this was already reported inside #2434 and will be fixed with #2450.
