### ISSUE TITLE
Return value of getMatchers() must be of the type array, null returned

### ISSUE THREAD

**Issue by aliw77** [pimcore/pimcore#2489]
Unable to locate the source of the issue, could you please provide some guidance.

```sh
==> var/logs/prod.log <==
[2018-01-23 03:16:57] php.CRITICAL: Type error: Return value of Pimcore\Http\Context\PimcoreContextGuesser::getMatchers() must be of the type array, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Return value of Pimcore\\Http\\Context\\PimcoreContextGuesser::getMatchers() must be of the type array, null returned at /opt/bitnami/apps/pimcore/htdocs/pimcore/lib/Pimcore/Http/Context/PimcoreContextGuesser.php:92)"} []
[2018-01-23 03:16:57] php.CRITICAL: Type error: Return value of Pimcore\Http\Context\PimcoreContextGuesser::getMatchers() must be of the type array, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Return value of Pimcore\\Http\\Context\\PimcoreContextGuesser::getMatchers() must be of the type array, null returned at /opt/bitnami/apps/pimcore/htdocs/pimcore/lib/Pimcore/Http/Context/PimcoreContextGuesser.php:92)"} []

==> var/logs/php.log <==
[23-Jan-2018 03:16:57 America/New_York] PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Return value of Pimcore\Http\Context\PimcoreContextGuesser::getMatchers() must be of the type array, null returned in /opt/bitnami/apps/pimcore/htdocs/pimcore/lib/Pimcore/Http/Context/PimcoreContextGuesser.php:92
Stack trace:
#0 /opt/bitnami/apps/pimcore/htdocs/pimcore/lib/Pimcore/Http/Context/PimcoreContextGuesser.php(68): Pimcore\Http\Context\PimcoreContextGuesser->getMatchers()
#1 /opt/bitnami/apps/pimcore/htdocs/pimcore/lib/Pimcore/Http/Request/Resolver/PimcoreContextResolver.php(65): Pimcore\Http\Context\PimcoreContextGuesser->guess(Object(Symfony\Component\HttpFoundation\Request), 'default')
#2 /opt/bitnami/apps/pimcore/htdocs/pimcore/lib/Pimcore/Http/Request/Resolver/PimcoreContextResolver.php(106): Pimcore\Http\Request\Resolver\PimcoreContextResolver->getPimcoreContext(Object(Symfony\Component\HttpFoundation\Request))
#3 /opt/bitnami/apps/pimcore/htdocs/pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Traits/PimcoreContextA in /opt/bitnami/apps/pimcore/htdocs/pimcore/lib/Pimcore/Http/Context/PimcoreContextGuesser.php on line 92
```

**Comment by maff** [comment]
Hi,

what Pimcore and PHP version are you using?

**Comment by aliw77** [comment]
PHP 7.0.25
Pimcore 5.1.1 (kernel: app, env: prod, debug: false)


On January 23, 2018 at 3:28:36 AM, Mathias Geat (notifications@github.com)
wrote:

Hi,

what Pimcore and PHP version are you using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pimcore/pimcore/issues/2489#issuecomment-359714149>,
or mute
the thread

**Comment by maff** [comment]
The error you're seeing should be resolved with 28ba5f5acf0e41454f336ca82bc8fdee5b4a41e6, however there must be something weird with your config as there should be matchers available. Can you post the output of `bin/console debug:config pimcore context`?

**Comment by aliw77** [comment]
```sh
> sudo bin/console debug:config pimcore context

Current configuration for "pimcore.context"
===========================================

{  }
```

**Comment by aliw77** [comment]
Applied the fix but admin is still blank page, and so is the site.  Logs are not showing anything now, hanging and browser timeout.

**Comment by maff** [comment]
Your config is incomplete - there should be values in the output of the CLI command. How did you install Pimcore? Does deleting everything in `var/cache` make any difference?

**Comment by aliw77** [comment]
rm -rf of var/cache does not help

I installed using bitnami AWS marketplace installation process and it was working for a good 2 days
