### ISSUE TITLE
PIMCORE Update to 5.1 to 5.1.3 failed

### ISSUE THREAD

**Issue by incoxx** [pimcore/pimcore#2580]
I did an update for a customer project from Pimcore 5.1 to 5.1.3

During the update a popup comes up with this message.

The update failed. Furthermore the pimcore installation was more or less destroyed.
The only solution was the installation of the last backup.

Pimcore 5.1 was a standard installation an no update from pimcore 4

Cheers
Markus

(1/1)                                         **ClassNotFoundException                                                                          Attempted to load class "PrestaSitemapBundle" from namespace "Presta\SitemapBundle". Did you forget a "use" statement for another namespace?**
--
in Kernel.php (line 253)
at Kernel->registerCoreBundlesToCollection(object(BundleCollection))in Kernel.php (line 196)
at Kernel->registerBundles()in Kernel.php (line 494)
at Kernel->initializeBundles()in Kernel.php (line 134)
at Kernel->boot()in Kernel.php (line 160)
at Kernel->boot()in kernel.php (line 25)
at require_once('/var/www/vhosts/localhost.localdomain/httpdocs/pimcore/config/kernel.php')in app.php (line 50)

**Comment by incoxx** [comment]
Sorry, i saw this ticket is duplicate to https://github.com/pimcore/pimcore/issues/2559

**Comment by brusch** [comment]
@incoxx have you tried the proposed patches in  #2559? Did it make it any better? Thanks for your feedback. (please post your feedback in  #2559 ;)).

**Comment by incoxx** [comment]
Hello Bernhard,

i installed the patch. OK.

Then i did an update from 5.1 to 5.1.1 ok
Then from 5.1.2. to 5.1.2 ok
Then from 5.1.2 to 5.1.3 => Error as mentioned above
I did an composer update 2 times. First i saw,         "presta/sitemap-bundle": "^1.5"
was in composer.json but NOT in vendor. After the second composer update presta was available in vendor
Then i did the update from 5.1.2 to 5.1.3 => OK

No idea what exacatly went wrong, but now 5.1.3 is up and running :)

Schönes Wochenende! Markus

**Comment by incoxx** [comment]
Hello Bernhard,

today it seems i am not the lucky one...

I disabled the debug mode and then the backend shows an error 500

In prod.log the exception is:

[2018-02-09 12:48:14] request.CRITICAL: Uncaught PHP Exception RuntimeException: "**Controller "Pimcore\Bundle\AdminBundle\Controller\Admin\IndexController::indexAction()" requires that you provide a value for the "$siteConfigProvider" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one." at /var/www/vhosts/localhost.localdomain/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver.php line 78 {"exception":"[object]** (RuntimeException(code: 0): Controller \"Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\IndexController::indexAction()\" requires that you provide a value for the \"$siteConfigProvider\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/vhosts/localhost.localdomain/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver.php:78)"} []
[2018-02-09 12:48:14] php.CRITICAL: Type error: Argument 1 passed to Pimcore\Bundle\CoreBundle\EventListener\Frontend\GoogleTagManagerListener::__construct() must be an instance of Pimcore\Analytics\SiteId\SiteIdProvider, none given, called in /var/www/vhosts/localhost.localdomain/httpdocs/var/cache/prod/Container6bczezq/appProdProjectContainer.php on line 1626 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Pimcore\\Bundle\\CoreBundle\\EventListener\\Frontend\\GoogleTagManagerListener::__construct() must be an instance of Pimcore\\Analytics\\SiteId\\SiteIdProvider, none given, called in /var/www/vhosts/localhost.localdomain/httpdocs/var/cache/prod/Container6bczezq/appProdProjectContainer.php on line 1626 at /var/www/vhosts/localhost.localdomain/httpdocs/pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/GoogleTagManagerListener.php:77)"} []
[2018-02-09 12:48:14] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Pimcore\Bundle\CoreBundle\EventListener\Frontend\GoogleTagManagerListener::__construct() must be an instance of Pimcore\Analytics\SiteId\SiteIdProvider, none given, called in /var/www/vhosts/localhost.localdomain/httpdocs/var/cache/prod/Container6bczezq/appProdProjectContainer.php on line 1626" at /var/www/vhosts/localhost.localdomain/httpdocs/pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/GoogleTagManagerListener.php line 77 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Pimcore\\Bundle\\CoreBundle\\EventListener\\Frontend\\GoogleTagManagerListener::__construct() must be an instance of Pimcore\\Analytics\\SiteId\\SiteIdProvider, none given, called in /var/www/vhosts/localhost.localdomain/httpdocs/var/cache/prod/Container6bczezq/appProdProjectContainer.php on line 1626 at /var/www/vhosts/localhost.localdomain/httpdocs/pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/GoogleTagManagerListener.php:77)"} []
[2018-02-09 12:48:25] cache.DEBUG: Key site_domain_3229cc9de7e22d4596ab91d8f331e87a doesn't exist in cache {"key":"site_domain_3229cc9de7e22d4596ab91d8f331e87a"} []
[2018-02-09 12:48:25] pimcore.DEBUG: Exception: there is no site for the requested domain: `82.165.61.174Â´ in /var/www/vhosts/localhost.localdomain/httpdocs/pimcore/models/Site/Dao.php:92 Stack trace: #0 /var/www/vhosts/localhost.localdomain/httpdocs/pimcore/models/Site.php(130): Pimcore\Model\Site\Dao->getByDomain('82.165.61.174') #1 /var/www/vhosts/localhost.localdomain/httpdocs/pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/FrontendRoutingListener.php(161): Pimcore\Model\Site::getByDomain('82.165.61.174') #2 /var/www/vhosts/localhost.localdomain/httpdocs/pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/FrontendRoutingListener.php(109): Pimcore\Bundle\CoreBundle\EventListener\Frontend\FrontendRoutingListener->resolveSite(Object(Symfony\Component\HttpFoundation\Request), '/') #3 /var/www/vhosts/localhost.localdomain/httpdocs/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): Pimcore\Bundle\CoreBundle\EventListener\Frontend\FrontendRoutingListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #4 /var/www/vhosts/localhost.localdomain/httpdocs/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #5 /var/www/vhosts/localhost.localdomain/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(127): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #6 /var/www/vhosts/localhost.localdomain/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 /var/www/vhosts/localhost.localdomain/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/vhosts/localhost.localdomain/httpdocs/web/app.php(55): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #9 {main} [] []

**Comment by brusch** [comment]
@incoxx please try: 

`./bin/console cache:clear --env=prod`
