### ISSUE TITLE
[ECOMMERCE] Order Agent fails on setting the PaymentProvider 

### ISSUE THREAD

**Issue by davidhoeck** [pimcore/pimcore#2645]
Just updated Pimcore from 5.0.2 to 5.2.0. Did some customization to fit the update. Now I get this error in the CommitOrderProcessor ( in my server side callback ). I have no idea why and what is the origin of this error. 

- I changed nothing in my Order DataObject
- I changed nothing in my PaymentProvider

```
[01-Mar-2018 10:55:34 Europe/Vienna] PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function setPaymentProviderMPay24Checkout() on null in /var/www/bts-platform/pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/OrderManager/Order/Agent.php:313
Stack trace:
#0 /var/www/bts-platform/pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/CheckoutManager/CommitOrderProcessor.php(175): Pimcore\Bundle\EcommerceFrameworkBundle\OrderManager\Order\Agent->setPaymentProvider(Object(AppBundle\Ecommerce\Payment\MPay24Checkout))
#1 /var/www/bts-platform/pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/CheckoutManager/CommitOrderProcessor.php(115): Pimcore\Bundle\EcommerceFrameworkBundle\CheckoutManager\CommitOrderProcessor->commitOrderPayment(Object(Pimcore\Bundle\EcommerceFrameworkBundle\PaymentManager\Status), Object(AppBundle\Ecommerce\Payment\MPay24Checko$
#2 /var/www/bts-platform/src/CheckoutBundle/Controller/MPay24Controller.php(172): Pimcore\Bundle\EcommerceFrameworkBundle\CheckoutManager\CommitOrderProcessor->han in /var/www/bts-platform/pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/OrderManager/Order/Agent.php on line 313
```

**Comment by fashxp** [comment]
hmm, that is strange ... when I have a look at the line of code where the error occurs, the method that is called should start with 'setAuth_' ... and not 'setPaymentProvider' like the error message suggests?!

can you verify that the code is the same? 
https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/OrderManager/Order/Agent.php#L313
