### ISSUE TITLE
Fatal exception: There is no class with the name: 17

### ISSUE THREAD

**Issue by bramstroker** [pimcore/pimcore#3159]
After upgrading my Pimcore installation to 5.3.1 I get the following error when trying to open a certain object.

Pimcore tries to get a class definition by name, but it passes an id.
The concerning code is in DataObject/ClassDefinition/Data/ObjectsMetadata.php line 876:
`$class = DataObject\ClassDefinition::getByName($classId);`

This should be the following imo.

`$class = DataObject\ClassDefinition::getById($classId);`

Full stacktrace:

```
pimcore.ERROR: Exception: There is no class with the name: 17 in /Volumes/www/pim.zitmaxx/pimcore/models/DataObject/ClassDefinition.php:210 Stack trace: #0 /Volumes/www/pim.zitmaxx/pimcore/models/DataObject/ClassDefinition/Data/ObjectsMetadata.php(876): Pimcore\Model\DataObject\ClassDefinition::getByName(17) #1 /Volumes/www/pim.zitmaxx/pimcore/models/DataObject/Service.php(1540): Pimcore\Model\DataObject\ClassDefinition\Data\ObjectsMetadata->enrichLayoutDefinition(Object(Pimcore\Model\DataObject\Product), Array) #2 /Volumes/www/pim.zitmaxx/pimcore/models/DataObject/Service.php(1558): Pimcore\Model\DataObject\Service::enrichLayoutDefinition(Object(Pimcore\Model\DataObject\ClassDefinition\Data\ObjectsMetadata), Object(Pimcore\Model\DataObject\Product), Array) #3 /Volumes/www/pim.zitmaxx/pimcore/models/DataObject/Service.php(1558): Pimcore\Model\DataObject\Service::enrichLayoutDefinition(Object(Pimcore\Model\DataObject\ClassDefinition\Layout\Panel), Object(Pimcore\Model\DataObject\Product), Array) #4 /Volumes/www/pim.zitmaxx/pimcore/models/DataObject/Service.php(1558): Pimcore\Model\DataObject\Service::enrichLayoutDefinition(Object(Pimcore\Model\DataObject\ClassDefinition\Layout\Tabpanel), Object(Pimcore\Model\DataObject\Product), Array) #5 /Volumes/www/pim.zitmaxx/pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectController.php(448): Pimcore\Model\DataObject\Service::enrichLayoutDefinition(Object(Pimcore\Model\DataObject\ClassDefinition\Layout\Panel), Object(Pimcore\Model\DataObject\Product)) #6 /Volumes/www/pim.zitmaxx/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObjectController->getAction(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher)) #7 /Volumes/www/pim.zitmaxx/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /Volumes/www/pim.zitmaxx/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /Volumes/www/pim.zitmaxx/web/index.php(48): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /Users/bram/.composer/vendor/weprovide/valet-plus/server.php(117): require('/Volumes/www/pi...') #11 {main} [] []
```

**Comment by brusch** [comment]
No `DataObject\ClassDefinition::getByName($classId);` is intentional. 
It seems that one of the update scripts wasn't executed during the update.
Try running it manually: 
https://github.com/pimcore/pimcore/blob/pimcore-5.3.x/update-scripts/283/postupdate.php

**Comment by brusch** [comment]
Btw. please don't open tickets for support ... better to use Gitter or https://talk.pimcore.com first, until it's verified it's a bug - thanks for your cooperation.
