### ISSUE TITLE
Unable to call private/protected method 'save' on object Pimcore\Model\Object\KeyValue\GroupConfig

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#350]
When saving a new Key/Value Group the ```parent::save()``` line in ```Pimcore\Model\Object\KeyValue\GroupConfig.php``` will trigger an error. 

This is happening because of your last commit: https://github.com/pimcore/pimcore/commit/56e836e030f9033b7ba9a1052e400b12bac89289.

i'm not 100% sure, but i think there are two mistakes:
- instead of asking ```if( method_exists() )``` it should be ```if( !method_exists() )```
- in order to avoid the call of private or protected methods, you should use the ```is_callable()```method. it returns```false``` in case of private or protected methods since php 5.2 i believe. also change ```$this```to ```__CLASS__```.

stacktrace:

```log
URL: /admin/key-value/addgroup
Params:
-> name: TestGruppe
Message: 

Fatal error:  Uncaught exception 'Exception' with message 'Unable to call private/protected method 'save' on object Pimcore\Model\Object\KeyValue\GroupConfig' in /vagrant/src/pimcore/lib/Pimcore/Model/AbstractModel.php:246
Stack trace:
#0 /vagrant/src/pimcore/models/Object/KeyValue/GroupConfig.php(159): Pimcore\Model\AbstractModel->__call('save', Array)
#1 /vagrant/src/pimcore/models/Object/KeyValue/GroupConfig.php(159): Pimcore\Model\AbstractModel->save()
#2 /vagrant/src/pimcore/modules/admin/controllers/KeyValueController.php(37): Pimcore\Model\Object\KeyValue\GroupConfig->save()
#3 /vagrant/src/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): Admin_KeyValueController->addgroupAction()
#4 /vagrant/src/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addgroupAction')
#5 /vagrant/src/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Contro in /vagrant/src/pimcore/lib/Pimcore/Model/AbstractModel.php on line 246
```

**Comment by brusch** [comment]
Thanks!
