### ISSUE TITLE
PublicServices Controller - not return on ImageMagick error

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#3719]
I just had a problem with ImageMagick and Adobe Illustrators files, which absolutely had nothing todo with Pimcore (ghostscript update fixed that). But having that issue, I discovered that there is a route in the PublicServicesController that doesn't return anything:

https://github.com/pimcore/pimcore/blob/master/bundles/CoreBundle/Controller/PublicServicesController.php#L99

If $thumbnailFile is null or doesn't exist the Controller doesn't return a Response. This case should actually never happen, cause Pimcore should fall-back to the `not-supported` image, but it doesn't.

Pimcore: 5.5.3
ImageMagic: ImageMagick 7.0.8-3 Q16 x86_64 2018-07-03
GhostScript (that fails): GPL Ghostscript 9.07 (2013-02-14)
GhostScript (that works): GPL Ghostscript 9.26 (2018-11-20)
Image: [Fabbri Flue Diagram Flue kit.ai.zip](https://github.com/pimcore/pimcore/files/2657104/Fabbri.Flue.Diagram.Flue.kit.ai.zip)

Error Log

```
[2018-12-07 12:34:25] pimcore.ERROR: Unable to load image: /var/www/html/web/var/assets/Image Library/Biomass/Fabbri/Fabbri Old price list/Flue Diagram.ai [] []
[2018-12-07 12:34:25] pimcore.ERROR: ImagickException: FailedToExecuteCommand `'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r72x72'  '-sOutputFile=/tmp/magick-3686SAfdk0Mih41s%d' '-f/tmp/magick-3686N8D87jCzN3qL' '-f/tmp/magick-3686Fprln-wQ27P3'' (1) @ error/pdf.c/InvokePDFDelegate/291 in /var/www/html/vendor/pimcore/pimcore/lib/Image/Adapter/Imagick.php:117 Stack trace: #0 /var/www/html/vendor/pimcore/pimcore/lib/Image/Adapter/Imagick.php(117): Imagick->readimage('/home/website/r...') #1 /var/www/html/vendor/pimcore/pimcore/models/Asset/Image/Thumbnail/Processor.php(199): Pimcore\Image\Adapter\Imagick->load('/home/website/r...', Array) #2 /var/www/html/vendor/pimcore/pimcore/models/Asset/Image/Thumbnail.php(164): Pimcore\Model\Asset\Image\Thumbnail\Processor::process(Object(Pimcore\Model\Asset\Image), Object(Pimcore\Model\Asset\Image\Thumbnail\Config), '/home/website/r...', false, true, false) #3 /var/www/html/vendor/pimcore/pimcore/models/Asset/Image/Thumbnail.php(139): Pimcore\Model\Asset\Image\Thumbnail->generate(false) #4 /var/www/html/vendor/pimcore/pimcore/bundles/CoreBundle/Controller/PublicServicesController.php(96): Pimcore\Model\Asset\Image\Thumbnail->getFileSystemPath() #5 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): Pimcore\Bundle\CoreBundle\Controller\PublicServicesController->thumbnailAction(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/web/app.php(48): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #9 {main} [] []
```

My guess is that this line:

https://github.com/pimcore/pimcore/blob/a530b922ac410ac99639e7f80316fd89e3487efb/lib/Image/Adapter/Imagick.php#L120

Should throw an exception instead of just returning `false`.

**Comment by brusch** [comment]
Hmm, I'm not able to reproduce the problem :| 
I've put `throw new \Exception('just a test');` and `return false` into the first line of `\Pimcore\Image\Adapter\Imagick::load()` and in both cases the error image was returned when calling `/examples/panama/image-thumb__22__galleryLightbox/img_0399.webp`. Of course I've cleared all caches between the tests ;)

**Comment by dpfaffenbauer** [comment]
I will try to make a reproduce able case. As said, this is quite an edge case.

**Comment by dpfaffenbauer** [comment]
Still happens. Will try to create a reproduceable case next week

**Comment by dpfaffenbauer** [comment]
cannot reproduce it anymore... when it happens again, I will reopen this case.
