### ISSUE TITLE
[Pimcore 4.6.5] Update fails due to PHP 5.6 constraint in composer.json

### ISSUE THREAD

**Issue by macghriogair** [pimcore/pimcore#3841]
# Bug Report

When updating from a Pimcore project with version 4.5.0 to **4.6.5** the CLI updater will fail due to incompatible composer platform config: The constraint is to PHP 5.6 but some packages require PHP >=7.1

### Expected behavior 

`composer install` should run without errors
  
### Actual behavior  

`composer install` fails due to dependency conflict.
  
### Steps to reproduce  

Given Project with Pimcore 4.5.0 or prior
When I run in CLI: `php pimcore/cli/console.php update -u 4123 -vvv`

I got the following Exception: 

`[2019-01-16 16:53:11] core.ERROR: Symfony\Component\Process\Exception\ProcessFailedException: The command "/usr/local/bin/composer update nothing -d /var/www/sites/project/htdocs" failed.  Exit Code: 2(Misuse of shell builtins)  Working directory: /var/www/sites/project/htdocs  Output: ================   Error Output: ================ Loading composer repositories with package information Updating dependencies (including require-dev) Your requirements could not be resolved to an installable set of packages.    Problem 1     - Installation request for azuyalabs/yasumi dev-master -> satisfiable by azuyalabs/yasumi[dev-master].     - azuyalabs/yasumi dev-master requires php >=7.1 -> your PHP version (7.1.26-1+ubuntu16.04.1+deb.sury.org+1) overriden by "config.platform.php" version (5.6) does not satisfy that requirement.   in /var/www/sites/project/htdocs/vendor/symfony/process/Process.php:232 Stack trace: #0 /var/www/sites/project/htdocs/pimcore/lib/Pimcore/Update.php(408): Symfony\Component\Process\Process->mustRun() #1 /var/www/sites/project/htdocs/pimcore/lib/Pimcore/Console/Command/UpdateCommand.php(184): Pimcore\Update::composerDumpAutoload() #2 /var/www/sites/project/vendor/symfony/console/Command/Command.php(240): Pimcore\Console\Command\UpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #3 /var/www/sites/project/vendor/symfony/console/Application.php(876): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #4 /var/www/sites/project/vendor/symfony/console/Application.php(215): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Console\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #5 /var/www/sites/project/vendor/symfony/console/Application.php(122): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #6 /var/www/sites/project/htdocs/pimcore/cli/console.php(23): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput)) #7 {main} {"origin":"Pimcore\\Update::composerDumpAutoload() on line 410","memory":"  9 MB"} []`

You can reproduce it with composer.json of https://github.com/pimcore/pimcore/blob/4.6.5/composer.json:

```

XXX@XXX:~/sites/project/htdocs$ rm composer.lock && COMPOSER_MEMORY_LIMIT=-1 composer update nothing
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for azuyalabs/yasumi dev-master -> satisfiable by azuyalabs/yasumi[dev-master].
    - azuyalabs/yasumi dev-master requires php >=7.1 -> your PHP version (7.1.26-1+ubuntu16.04.1+deb.sury.org+1) overriden by "config.platform.php" version (5.6) does not satisfy that requirement. 
```

```
cat ./pimcore/lib/Pimcore/Version.php | grep 'ion ='"
    public static $version = "4.6.5";
    public static $revision = 4123;
```

composer.json
```
 "config": {
        "optimize-autoloader": true,
        "platform": {
            "php": "5.6"
        }
    },

```
  
Suggested FIX: remove "platform" key from composer config or adapt to valid version constraint.

**Comment by brusch** [comment]
Fixed in 508241192ee6d31bfee11842e886104f8dc39fda 
Please note that Pimcore 4 is actually not supported anymore ;)
