### ISSUE TITLE
Imagemagick based image preview generation crashes when PIMCORE_SYSTEM_TEMP_DIRECTORY is stored in Amazon S3

### ISSUE THREAD

**Issue by pmuskovac** [pimcore/pimcore#3866]
When you use S3 as a shared storage, and set PIMCORE_SYSTEM_TEMP_DIRECTORY to a location in S3 and have the imagemagick php extension enabled, both uploading images and generating preview thumbnails will cause PHP Exceptions:

```
pimcore.ERROR: ImagickException: unable to open image ':s3://bucket-var-dev/var/tmp/asset-temporary/asset_81_8a1f3915dc94c916e049d2bb2fde5d8b__display-custom-logo.png[0]': No such file or directory @ error/blob.c/OpenBlob/3457 in /data/cms/vendor/pimcore/pimcore/lib/Image/Adapter/Imagick.php:119
```

(Full trace at the bottom)
  
### Expected behavior 
Uploading an asset and opening it shows the Asset in the Admin panel
  
### Actual behavior  
Pimcore crashes and the Admin view only shows a 'broken image' icon as the image preview.
  
### Steps to reproduce  
- ensure php7 imagick and imagemagick are installed and enabled
- set up S3 as a shared storage for the CMS data and make sure PIMCORE_SYSTEM_TEMP_DIRECTORY is prefixed with the bucket URL
- upload an Asset from the Admin panel
  
### Code example 
I have attempted to patch this in https://github.com/pmuskovac/pimcore/commit/283bfab331c934d62ed208618f838890568bbb77
but I'm not convinced that this is the proper way to do this as it just works around the problem by making sure the images get temporarily stored on the local filesystem.

### Further information
The reason why PIMCORE_SYSTEM_TEMP_DIRECTORY is placed in S3 is the Javascript minimizer for the Admin view which uses that as its storage location and we have a clustered Pimcore setup.

Full stack trace:
```
2019-01-22T09:57:02.090867761Z [2019-01-22 10:57:02] pimcore.ERROR: ImagickException: unable to open image ':s3://bucket-var-dev/var/tmp/asset-temporary/asset_81_8a1f3915dc94c916e049d2bb2fde5d8b__display-custom-logo.png[0]': No such file or directory @ error/blob.c/OpenBlob/3457 in /data/cms/vendor/pimcore/pimcore/lib/Image/Adapter/Imagick.php:119 Stack trace: #0 /data/cms/vendor/pimcore/pimcore/lib/Image/Adapter/Imagick.php(119): Imagick->readimage(':s3://bucket...') #1 /data/cms/vendor/pimcore/pimcore/models/Asset/Image/Thumbnail/Processor.php(199): Pimcore\Image\Adapter\Imagick->load('s3://bucket-...', Array) #2 /data/cms/vendor/pimcore/pimcore/models/Asset/Image/Thumbnail.php(163): Pimcore\Model\Asset\Image\Thumbnail\Processor::process(Object(Pimcore\Model\Asset\Image), Object(Pimcore\Model\Asset\Image\Thumbnail\Config), 's3://bucket-...', false, true, false) #3 /data/cms/vendor/pimcore/pimcore/models/Asset/Image/Thumbnail.php(139): Pimcore\Model\Asset\Image\Thumbnail->generate(false) #4 /data/cms/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/AssetController.php(1342): Pimcore\Model\Asset\Image\Thumbnail->getFileSystemPath() #5 /data/cms/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): Pimcore\Bundle\AdminBundle\Controller\Admin\AssetController->getImageThumbnailAction(Object(Symfony\Component\HttpFoundation\Request)) #6 /data/cms/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 /data/cms/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /data/cms/web/app.php(48): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #9 {main} [] []
  ```

**Comment by brusch** [comment]
While `PIMCORE_TEMPORARY_DIRECTORY` can be on a remote file system,  `PIMCORE_SYSTEM_TEMP_DIRECTORY ` (or better to say `PIMCORE_PRIVATE_VAR`) has to be locally in any case! 

The Imagick adapter is already handling remote file systems for the public var folder properly, so if you change `PIMCORE_SYSTEM_TEMP_DIRECTORY ` back to the local file system, you should be fine. 

Normally there's no reason to change that, even when running on a cluster environment.
