### ISSUE TITLE
[ecommerce] Disabling/uninstalling keep object/objectbrick/fieldollection

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4060]
Hello,

When disabling/uninstalling the ecommerce, it keep object/objectbrick/fieldollection.

Problem is that the specific ecommerce attribut type are no more available, making some side bugs (cannot no more open the fieldcollections, etc...).

They should be uninstalled as well ?

Thanks.

**Comment by brusch** [comment]
That's intentional, the definitions for the classes, bricks and fieldcollections need to be deleted manually.

**Comment by dpfaffenbauer** [comment]
And thats good :), cause you now people -> they make mistakes, and one of that could be to uninstall something and loose all data, in production, on a friday afternoon ;)

**Comment by Yivan** [comment]
Thanks for your answer, I undestand perfectly that for security purpose datas are kept.

But the problem behind is that we can no more access in the GUI to DataObject -> Fieldcollections, fieldcollections are no more listed and an error is send. : (

Here is a screenshot after uninstall and disable:

![bug-ecommerce](https://user-images.githubusercontent.com/9025839/54276076-a22b5e80-458c-11e9-8ab4-a27eaed54c21.png)

Here is the detail of the error message:

```
BE RESPECTFUL AND HONOR OUR WORK FOR FREE & OPEN SOURCE SOFTWARE BY NOT REMOVING OUR LOGO. WE OFFER YOU THE POSSIBILITY TO ADDITIONALLY ADD YOUR OWN LOGO IN PIMCORE'S SYSTEM SETTINGS. THANK YOU!
Le server a lancé une exception - l'action n'a pas pu être effectuée
Timestamp: Wed Mar 13 2019 12:31:53 GMT+0100 (heure normale d’Europe centrale)
Status: 500 | Internal Server Error
URL: /admin/class/fieldcollection-tree?_dc=1552476712099
Method: GET
Message: You have requested a non-existent service "pimcore_ecommerce.factory".
Trace: 
#0 /var/www/html/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/Factory.php(151): Symfony\Component\DependencyInjection\Container->get('pimcore_ecommer...')
#1 /var/www/html/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CoreExtensions/ClassDefinition/IndexFieldSelectionCombo.php(41): Pimcore\Bundle\EcommerceFrameworkBundle\Factory::getInstance()
#2 /var/www/html/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CoreExtensions/ClassDefinition/IndexFieldSelectionCombo.php(36): Pimcore\Bundle\EcommerceFrameworkBundle\CoreExtensions\ClassDefinition\IndexFieldSelectionCombo->buildOptions()
#3 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Helper/VarExport.php(28): Pimcore\Bundle\EcommerceFrameworkBundle\CoreExtensions\ClassDefinition\IndexFieldSelectionCombo->__construct()
#4 /var/www/html/var/classes/fieldcollections/FilterInputfield.php(85): Pimcore\Model\DataObject\ClassDefinition\Data::__set_state(Array)
#5 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Fieldcollection/Definition/Listing.php(34): include('/var/www/html/v...')
#6 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php(801): Pimcore\Model\DataObject\Fieldcollection\Definition\Listing->load()
#7 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\ClassController->fieldcollectionTreeAction(Object(Symfony\Component\HttpFoundation\Request))
#8 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#9 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /var/www/html/web/app.php(48): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#11 {main}
```

Thanks.

**Comment by Yivan** [comment]
@brush I think it need to be reopened maybe as it breaks the field collection panel. Please see my previous post. Thanks.

**Comment by fashxp** [comment]
this is connected to that one: https://github.com/pimcore/pimcore/issues/3640
