### ISSUE TITLE
[DataObjects] copy as child recursively failed in backend if @ in path (PR proposed)

### ISSUE THREAD

**Issue by FredoVelcro** [pimcore/pimcore#4159]
When copying "as a child recursivly" in back office, i have this error in a modal :
```
Warning: preg_replace(): Unknown modifier 'g'
```
```
Status: 500 | Internal Server Error
URL: /admin/object/copy
Method: POST
Message: Warning: preg_replace(): Unknown modifier 'g'
Trace: 
#0 /home/web-user/htdocs/fv.dev.pimcore.bigmat.galilee.fr/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->copyAction(Object(Symfony\Component\HttpFoundation\Request))
#1 /home/web-user/htdocs/fv.dev.pimcore.bigmat.galilee.fr/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#2 /home/web-user/htdocs/fv.dev.pimcore.bigmat.galilee.fr/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#3 /home/web-user/htdocs/fv.dev.pimcore.bigmat.galilee.fr/web/app.php(42): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
```

Found error here : 
https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L2019
```
$targetPath = preg_replace('@^' . $sourceParent->getRealFullPath() . '@', $targetParent . '/', $source->getRealPath());
```
Because i have an arobase in my object Path (in object key in fact), it fails with for example : 
/Utilisateurs/Siège/**siege@toto.com**/Documents/Administratifs/PLV/Mon catalogue

POSSIBLE SOLUTION : 
```php
$targetPath = preg_replace('/^' . str_replace('/', '\/', $sourceParent->getRealFullPath()) . '/', $targetParent . '/', $source->getRealPath());
```

Thank you for your fix ! ;)
Best regards,

Fred

**Comment by FredoVelcro** [comment]
https://github.com/pimcore/pimcore/pull/4160
