### ISSUE TITLE
[Core][Extensions][Areabricks] Duplicate Areabrick excception 

### ISSUE THREAD

**Issue by anyMOTION-GRAPHICS** [pimcore/pimcore#4917]
# Bug Report

#### Scenario 1
If you try to install a second Bundle which provide an Areabrick with the same name. You get an Exception while installing.  

#### Scenario 2
If you have 2 different Bundles with multiple Areabricks and you create a new Areabrick with a name which already exist.  

#### Scenario 1
Exception will be thrown with hint of service registration.
#### Scenario 2
Some or all Areabricks stop working, the first Areablock return nothing to the view.

#### Scenario 1
Exception will be thrown with hint of service registration. __(see Exception)__
#### Scenario 2
Some or all Areabricks stop working, the first Areablock return nothing to the view.

### Steps to reproduce
Install latest Version of Pimcore. Register 2 Bundles which has Areabricks with the same name.

# Feature Request
Prefixed Areabricks by Bundle

## Feature description
Our suggestion is to add an bundle prefix for every Areablock, which will be registered by an bundle to avoid duplication. 

# Exceptions
#### Scenario 1
```
Please don't forget to clear the cache and reload pimcore after your modifications!

3
BE RESPECTFUL AND HONOR OUR WORK FOR FREE & OPEN SOURCE SOFTWARE BY NOT REMOVING OUR LOGO. WE OFFER YOU THE POSSIBILITY TO ADDITIONALLY ADD YOUR OWN LOGO IN PIMCORE'S SYSTEM SETTINGS. THANK YOU!

Timestamp: Thu Aug 29 2019 14:56:08 GMT+0200 (Central European Summer Time)
Status: 500 | Internal Server Error
URL: /admin/extensionmanager/admin/extensions?_dc=1567083368213
    Method: GET
Message: Areabrick hallo-welt-brick is already registered as service any_m_o_t_i_o_n_duplicate_brick_brick1.area.brick.hallo_welt_brick (trying to add service any_m_o_t_i_o_n_duplicate_brick_brick2.area.brick.hallo_welt_brick)
Trace:
#0 /var/www/html/www/var/cache/dev/ContainerXY6Xdfo/getAreabrickManagerService.php(16): Pimcore\Extension\Document\Areabrick\AreabrickManager->registerService('hallo-welt-bric...', 'any_m_o_t_i_o_n...')
#1 /var/www/html/www/var/cache/dev/ContainerXY6Xdfo/appAppKernelDevDebugContainer.php(404): require('/var/www/html/w...')
#2 /var/www/html/www/var/cache/dev/ContainerXY6Xdfo/getExtensionManagerControllerService.php(9): ContainerXY6Xdfo\appAppKernelDevDebugContainer->load('getAreabrickMan...')
#3 /var/www/html/www/var/cache/dev/ContainerXY6Xdfo/appAppKernelDevDebugContainer.php(404): require('/var/www/html/w...')
#4 /var/www/html/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(243): ContainerXY6Xdfo\appAppKernelDevDebugContainer->load('getExtensionMan...')
#5 /var/www/html/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(225): Symfony\Component\DependencyInjection\Container->make('Pimcore\\Bundle\\...', 1)
#6 /var/www/html/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ContainerControllerResolver.php(53): Symfony\Component\DependencyInjection\Container->get('Pimcore\\Bundle\\...')
#7 /var/www/html/www/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php(54): Symfony\Component\HttpKernel\Controller\ContainerControllerResolver->instantiateController('Pimcore\\Bundle\\...')
#8 /var/www/html/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php(122): Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver->instantiateController('Pimcore\\Bundle\\...')
#9 /var/www/html/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ContainerControllerResolver.php(42): Symfony\Component\HttpKernel\Controller\ControllerResolver->createController('Pimcore\\Bundle\\...')
#10 /var/www/html/www/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php(46): Symfony\Component\HttpKernel\Controller\ContainerControllerResolver->createController('Pimcore\\Bundle\\...')
#11 /var/www/html/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php(86): Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver->createController('Pimcore\\Bundle\\...')
#12 /var/www/html/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/TraceableControllerResolver.php(38): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request))
#13 /var/www/html/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(134): Symfony\Component\HttpKernel\Controller\TraceableControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request))
#14 /var/www/html/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#15 /var/www/html/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(198): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /var/www/html/www/web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#17 {main}
```

**Comment by brusch** [comment]
Prefixing would be a huge BC-break as all contents of existing area bricks will be lost. Migrating the content is nearly impossible. I don't think it's worth the effort and pain ... 

Maybe you should think about registering the areas manually as a service? 
There you can manually specify the ID and service name ...
