### ISSUE TITLE
Rea,ted

### ISSUE THREAD

**Issue by ramundomario** [pimcore/pimcore#5007]
# Bug Report

### Code example
```php
// your code
```

# Feature Request

**Comment by dbraito-bsd** [comment]
S3 support is really a mess. I was able to hackily overcome this issue by having both Asset and Ffmpeg not delete their temporary files on __destruct(). I also had to disable the recommended S3  event "FrontendEvents::ASSET_VIDEO_IMAGE_THUMBNAIL".

There seems to be another related bug. In serveVideoPreviewAction() they use BinaryFileResponse which attempts to seek on the S3 file, using steam_copy_to_stream(). This fails with warning

 `php.WARNING: Uncaught Warning: stream_copy_to_stream(): Failed to seek to position 65536 in the stream {"exception":"[object] (ErrorException(code: 0): Warning: stream_copy_to_stream(): Failed to seek to position 65536 in the stream at /var/www/pimcore/avb-dam/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/BinaryFileResponse.php:303)"} []`

Maybe the proper fix here is to directly serve the video from S3, skipping using serveVideoPreviewAction() entirely.

If anyone is willing to share their complete Pimcore + S3 + Video implementation I'd love to see it.

**Comment by scsi303** [comment]
Still no working Video preview with the assets stored in AWS S3. Using Pimcore v6.8.4
Did someone get it to work? That would be great.

Btw. Pdf thumbs are also not generated in the asset list using AWS S3. Problem with FileinfoMimeTypeGuesser. Strange.

**Comment by jkalbhenn** [comment]
i would like to share my debug notes and current workaround patch for pimcore v6.8.6. ramundomario and dbraito-bsd already listed the main issues. i get working video thumbnails and previews with these changes. there might be side effects i am not aware of.

two alternative patches:
* running the video conversion in the foreground: [s3-video-preview.patch.txt](https://github.com/pimcore/pimcore/files/5775618/s3-video-preview.patch.txt)
* not unlinking temporary files: [s3-video-preview-nounlink.patch.txt](https://github.com/pimcore/pimcore/files/5775619/s3-video-preview-nounlink.patch.txt)

with the second patch it looks like var/tmp/asset-temporary has to be emptied by other means, or it will fill up with local copies of videos
* pdf thumbnails mostly work, but i have one case where it doesnt for unknown reasons
* when an error occurs, thumbnail generation is not retried even when emptying the cache. caused by pimcore/pimcore/models/Asset/Video/Thumbnail/Processor.php:process() "throw new \Exception('Unable to convert video, see logs for details.');". i currently dont know how to let it retry without re-uploading the asset or editing the code

it might need changes in S3EventListener.php. for example, i am using the following for `FrontendEvents::ASSET_VIDEO_THUMBNAIL => "onFrontendPathVideoThumbnail"`
~~~
    public function onFrontendPathVideoThumbnail(GenericEvent $event) {
        # for the preview on the backend object detail page.
        # example input path: "/Test/video-thumb__5681__pimcore-system-treepreview/file_example_MP4_640_3MG.mp4"
        $fsPath = $event->getSubject()->getFileSystemPath();
        $publicPath = str_replace($this->s3Api, $this->s3Public, $fsPath);
        $event->setArgument("frontendPath", $publicPath);
    }
~~~

<details>
  <summary>more detailed notes about the second patch</summary>

Ffmpeg.php:load()
* if !stream_is_local()
  * $tmpFile = $options['asset']->getTemporaryFile();
  * $this->tmpFiles[] = $tmpFile;
* the asset object and ffmpeg object will try to remove the temporary file at path on php object destroy
* Video\Thumbnail\Processor.php:convert() saves instance of itself, including Ffmpeg.php converter, in TmpStore
* destroy will happen because conversion is done in separate process
* workaround
  * disable tmpFile unlink in Ffmpeg.php and models/Asset.php. renaming the file did not work

code
~~~
foreach ($this->_temporaryFiles as $tempFile) {
  #@unlink($tempFile);
~~~

Asset\Video\ImageThumbnail.php:generate()
* calls Ffmpeg.php:load() without "asset" in options. load then wont call $options['asset']->getTemporaryFile()
* before generating the final resized thumbnail, overwrites $path with new getTemporaryFile() path that does not exist
* workaround
  * add "asset" to options
  * dont set path to a different path

code
~~~
$converter->load($this->asset->getFileSystemPath(), ["asset" => $this->asset]);
# ...
if (!stream_is_local($path)) {
  # $path = $this->asset->getTemporaryFile();
}
~~~

getPreviewVideoDisplay.html.php
* will set a /admin/asset/serve-video-preview url as the video src
* then AssetController.php:serveVideoPreviewAction() returns a symfony BinaryFileResponse() which for some reason does not work
* workaround
  * dont use serve-video-preview and instead use the public s3 http url
  * add code to getPreviewVideoDisplay.html.php

code
~~~
$serveVideoPreview = $this->thumbnail["formats"]["mp4"];
~~~
</details>

<details>
  <summary>about how video thumbnail generation works in the code</summary>

- starting from the pimcore:thumbnails:video console command
-   ThumbnailsVideoCommand.php triggers the video thumbnail generation
    with $video-&gt;getThumbnail($thumbnail)
-   then it calls getThumbnail() repeatedly until result is not
    "inprogress&quot;
    -   getThumbnail() returns an array with info about the thumbnail
        processing progress, with a status field
        "inprogress&quot;/&quot;error&quot;/&quot;finished&quot;
    -   it returns null if no thumbnails are configured or on error
-   vendor/pimcore/pimcore/models/Asset/Video.php getThumbnail() calls
    Video\\Thumbnail\\Processor::process($this, $thumbnail,
    $onlyFormats)
-   progress status information is stored in
    $this-&gt;getCustomSetting(?thumbnails?), where $this is the
    Asset\\Video object
-   vendor/pimcore/pimcore/models/Asset/Video/Thumbnail/Processor.php
    -   process() prepares
        -   it checks if there is already a progress status object with
            error or finished - it wont continue if there were errors
            from another run
        -   it stores an instance of itself in TmpStore (stored
            serialized in the database under tmp\_store)
        -   it calls vendor/pimcore/pimcore/lib/Video.php:getInstance()
            to get an Adapter, by default lib/Video/Adapter/Ffmpeg.php
        -   the Adapter is the $converter
        -   $converter-&gt;load()
            -   copies remote files to a local temp file in a pimcore
                temp directory
            -   it gets a temporary file path by calling
                Asset.php:getTemporaryFile(), which will be deleted when
                the asset php object is destroyed
            -   it sets $converter-&gt;file to the temporary path
        -   it initializes the progress status object ($customSettings)
            and saves it with the asset object ($asset-&gt;save())
        -   it then calls convert()
    -   convert() starts a background php process with an internal
        command internal:video-converter
        -   since this runs in a background process, there is no
            standard output (echo, var\_dump) available
        -   the process might have to be killed if something goes wrong
    -   execute() is the only thing called by internal:video-converter
        -   it loads the previously stored instance of Processor from
            TmpStore
        -   it tries to get a lock file and can hang there. i couldnt
            figure out where the lock file is stored (could not find it
            in filesystem or locks table)
        -   it then calls $converter-&gt;save(), which is
            Ffmpeg.php:save() by default
        -   $converter-&gt;save() will try to use $converter-&gt;file as
            input for conversion
        -   then it updates the progress status object, saves the asset
            object with the updated status object and returns
</details>

**Comment by pradeep-pimcore** [comment]
I am also facing this issue, is this resolved in any newer version ?
I don't see any activity here and the bug is still open since a long time.

**Comment by brusch** [comment]
Pimcore 6 is EOL, can this be still reproduced with Pimcore 10?

**Comment by pradeep-pimcore** [comment]
We have not upgraded to Pimcore 10 yet.

**Comment by ghost** [comment]
> Pimcore 6 is EOL, can this be still reproduced with Pimcore 10?

Hi @brusch , yes we can reproduce the same behaviour with v10.1.1
We would appreciate it very much if you could put this issue onto the agenda

![image](https://user-images.githubusercontent.com/68632142/136211086-8f9c8c82-a09d-4694-891f-3aa9a32df9a7.png)


![pimcore_video_preview](https://user-images.githubusercontent.com/68632142/136210925-8367d80e-e0e0-499e-acd3-5abfb7dc7133.png)

**Comment by brusch** [comment]
@Silverado2791 have you tried #8335 and #8377 ? Or just go on `10.1.x-dev` - Thanks!

**Comment by ghost** [comment]
hi @brusch , thank you. Video preview runs as expected with v10.1.5 and S3 storage. But currently there seems a preview issue with v10.2.1

Reproduced on https://demo.pimcore.com

![grafik](https://user-images.githubusercontent.com/68632142/138071728-82124a91-271a-48aa-a589-9e938c113cda.png)

**Comment by brusch** [comment]
@Silverado2791 fixed by #10629

Please note, that video transcoding has been moved to message queue in `10.2`, so it's now done via the maintenance job or by `messenger:consume`. This however isn't yet set up on our demos, that's why video transcoding is currently NOT working in our public demo.

**Comment by Silverado2791** [comment]
@brusch 

Videopreview ran as expected on identical pimcore 10.1.5 installations running on the same server - one with local asset storage, the other one with s3 asset storage.

Now after upgrade to 10.2.7 

**Videopreview runs as expected on pimcore 10.2.7 installation with local storage**

1. upload example.mov to assetfolder
2. manually run bin/console pimcore:maintenance --async
3. manually run bin/console messenger:consume --limit=100  pimcore_core pimcore_maintenance -vv

![image](https://user-images.githubusercontent.com/68632142/147261985-0093a657-aa63-4b99-a229-d9f47a9594ce.png)

![image](https://user-images.githubusercontent.com/68632142/147262195-c35a8127-f956-4987-8ac9-8055f20968b3.png)

![image](https://user-images.githubusercontent.com/68632142/147263325-23478ece-8296-4a41-b097-102289d1a931.png)


**Videopreview  fails on pimcore 10.2.7 installation with S3 storage**

1. upload example.mov to assetfolder
2. manually run bin/console pimcore:maintenance --async
3. manually run bin/console messenger:consume --limit=100  pimcore_core pimcore_maintenance -vv

No "VideoConvertMessage" at all!

![image](https://user-images.githubusercontent.com/68632142/147261080-088bd425-060c-40c9-bf16-4b35dc6a34ed.png)

![image](https://user-images.githubusercontent.com/68632142/147261769-b3b01c12-1c77-4949-be0e-8289a3a25f1d.png)

![image](https://user-images.githubusercontent.com/68632142/147263160-9b28a3e2-2e00-448e-b009-0bfdb6e0d041.png)


flysystem.yaml

![image](https://user-images.githubusercontent.com/68632142/147262989-ccb26589-a997-4635-ac56-488521c589db.png)

**Comment by shades3002** [comment]
I am having problems with the previews of the videos too, they are hosted on S3, I am using version 10.5 of pimcore. There is no problem with images, but with videos there is, here is a fragment of the log:  

pimcore.ERROR: Couldn't create thumbnail of  /videos/ Corporatiu Master EN - Qualitat 1080p.mp4 [] []
 pimcore.ERROR: Exception: Unable to convert video, see logs for details. in /var/www/html/vendor/pimcore/pimcore/models/Asset/Video/Thumbnail/Processor.php:120 Stack trace: #0 /var/www/html/vendor/pimcore/pimcore/models/Asset/Video.php(107): Pimcore\Model\Asset\Video\Thumbnail\Processor::process(Object(Pimcore\Model\Asset\Video), Object(Pimcore\Model\Asset\Video\Thumbnail\Config), Array) #1 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Asset/AssetController.php(146): Pimcore\Model\Asset\Video->getThumbnail(Object(Pimcore\Model\Asset\Video\Thumbnail\Config), Array) #2 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(163): Pimcore\Bundle\AdminBundle\Controller\Admin\Asset\AssetController->getDataByIdAction(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #4 /var/www/html/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /var/www/html/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #6 {main} [] []

Any ideas?
