### ISSUE TITLE
Permission denied for logs/prod.log

### ISSUE THREAD

**Issue by benhartwich** [pimcore/pimcore#5890]
# Bug Report

### Expected behavior
After an update no 500er php error should occur

### Actual behavior
Upgrading from 6.4.2 to 6.5.1 causes an 500er error when accessing the web interface

I´ve checked the permissions. The file has the same user and group like it had before and the php process is running as fotoarchiv and the file is owned by fotoarchiv (644). Nginx and php can write and access.

### Steps to reproduce
composer update within the root folder (no errors).

### Log
```
2020/02/24 10:22:12 [error] 3130#3130: *468300 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/pimcore/htdocs/fotodb/var/logs/prod.log" could not be opened: failed to open stream: Permission denied in /var/www/pimcore/htdocs/fotodb/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:108
Stack trace:
#0 /var/www/pimcore/htdocs/fotodb/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler->write(Array)
#1 /var/www/pimcore/htdocs/fotodb/vendor/monolog/monolog/src/Monolog/Handler/FingersCrossedHandler.php(116): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /var/www/pimcore/htdocs/fotodb/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handler\FingersCrossedHandler->handle(Array)
#3 /var/www/pimcore/htdocs/fotodb/vendor/monolog/monolog/src/Monolog/Logger.php(614): Monolog\Logger->addRecord(200, 'User Deprecated...', Array)
#4 /var/www/pimcore/htdocs/fotodb/vendor/symfony/symfony/src/Symfony/Component/ErrorHandler/Err" while reading response header from upstream, client: 91.114.81.36, server: fotoarchiv.liferadio.at, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm-pimcore.sock:", host: "fotoarchiv.xy.de", referrer: "https://fotoarchiv.xy.de"

```

**Comment by benhartwich** [comment]
Ah sorry, have used the wrong user.
