### ISSUE TITLE
table dependencies : Column not found: 1054 Unknown column 'id' in 'field list'

### ISSUE THREAD

**Issue by FredoVelcro** [pimcore/pimcore#6110]
[Pimcore dev-master branch]

When saving an objet in backend, i have got this : 
```
Status: 500 | Internal Server Error
URL: /admin/object/save?task=publish
Method: PUT
Message: An exception occurred while executing 'SELECT id, targetType, targetId FROM dependencies WHERE sourceType= ? AND sourceId = ?' with params ["object", 31874]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'field list'
Trace: 
in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60
#0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(166): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(146): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'An exception oc...')
#2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(912): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT id, targ...', Array)
#3 /var/www/html/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(93): Doctrine\DBAL\Connection->executeQuery('SELECT id, targ...', Array, Array, NULL)
#4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(844): Pimcore\Db\Connection->executeQuery('SELECT id, targ...', Array, Array)
#5 /var/www/html/vendor/pimcore/pimcore/models/Dependency/Dao.php(108): Doctrine\DBAL\Connection->fetchAll('SELECT id, targ...', Array)
#6 [internal function]: Pimcore\Model\Dependency\Dao->save()
#7 /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(247): call_user_func_array(Array, Array)
#8 /var/www/html/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(813): Pimcore\Model\AbstractModel->__call('save', Array)
#9 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Concrete.php(188): Pimcore\Model\DataObject\AbstractObject->update(true, Array)
#10 /var/www/html/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(652): Pimcore\Model\DataObject\Concrete->update(true, Array)
#11 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Concrete.php(736): Pimcore\Model\DataObject\AbstractObject->save(Array)
#12 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(1280): Pimcore\Model\DataObject\Concrete->save()
#13 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(158): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->saveAction(Object(Symfony\Component\HttpFoundation\Request))
#14 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#15 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /var/www/html/web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#17 {main}
```
Note : all migrations are up to date

**Comment by brusch** [comment]
> Note : all migrations are up to date
Doesn't seem so ... see https://github.com/pimcore/pimcore/blob/f5b02e99a581eaeef90b4122de94357a5d873d18/bundles/CoreBundle/Migrations/Version20200226102938.php#L16

**Comment by FredoVelcro** [comment]
ok, something was wrong in my migrations so...
nerver mind thanks !
Maybe this : 
if ($schema->getTable('dependencies')->hasIndex('sourceid')) ...
