### ISSUE TITLE
[Bug - Important] Migration 20191114123638 broken

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#6155]
Hello,

Wanting to update a Pimcore 6.0.5 to 6.6.0, we encountered a migration error for 20191114123638.

The SQL requests done in https://github.com/pimcore/pimcore/blob/master/bundles/CoreBundle/Migrations/Version20191114123638.php are not runned before the save document is done, making a save error.

I checked by running manually this migration and comparing the table structure of `dependencies` table and the change was not done (old structure). SQL requests are well parsed by PHP (checking with die/echo) so the script go well in the `if` condition, but requests are not effectivly run on the database. I am not expert in migrations, but SQL requests are maybe done in one row after the up method so database is not already modified when the second part of the migration (saving documents) is done... ? And so this migration should be splitted in two migrations ?

For those having this problem too, for now the solution is to run manually the two SQL requests on the database directly and after run manually `php bin/console pimcore:migrations:migrate -s pimcore_core -n` to finish the update.
All the others migration passed fluently, great, but this one is broken.

It think it should be fixed asap as many other could have the problem when migrating.

Best regards

Here the stack trace:

```
  ++ migrating 20191114123638

18:18:04 EMERGENCY [pimcore] PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'field list' in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121
Stack trace:
#0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(121): PDOStatement->execute()
#1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(906): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /var/www/html/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(93): Doctrine\DBAL\Connection->executeQuery()
#3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(844): Pimcore\Db\Connection->executeQuery()
#4 /var/www/html/vendor/pimcore/pimcore/models/Dependency/Dao.php(108): Doctrine\DBAL\Connection->fetchAll()
#5 [internal function]: Pimcore\Model\Dependency\Dao->save()
#6 /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(247): call_user_func_array()
#7 /var/www/html/vendor/pimcore/pimcore/models/Document.php(598): Pimcore\Model\AbstractModel->__call()
#8 /var/www/html/vendor/pimcore/pimcore/models/Document/Link.php(361): Pimcore\Model\Document->update()
#9 /var/www/html/vendor/pimcore/pimcore/models/Document.php(431): Pimcore\Model\Document\Link->update()
#10 /var/www/html/vendor/pimcore/pimcore/bundles/CoreBundle/Migrations/Version20191114123638.php(46): Pimcore\Model\Document->save()
#11 /var/www/html/vendor/pimcore/pimcore/lib/Migrations/Version.php(312): Pimcore\Bundle\CoreBundle\Migrations\Version20191114123638->up()
#12 /var/www/html/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php(172): Pimcore\Migrations\Version->execute()
#13 /var/www/html/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php(132): Doctrine\DBAL\Migrations\Migration->migrate()
#14 /var/www/html/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsMigrateDoctrineCommand.php(44): Doctrine\DBAL\Migrations\Tools\Console\Command\MigrateCommand->execute()
#15 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute()
#16 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(1019): Symfony\Component\Console\Command\Command->run()
#17 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(97): Symfony\Component\Console\Application->doRunCommand()
#18 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(271): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()
#19 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun()
#20 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(147): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
#21 /var/www/html/bin/console(26): Symfony\Component\Console\Application->run()
#22 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'field list' in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123
Stack trace:
#0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(906): Doctrine\DBAL\Driver\PDOStatement->execute()
#1 /var/www/html/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(93): Doctrine\DBAL\Connection->executeQuery()
#2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(844): Pimcore\Db\Connection->executeQuery()
#3 /var/www/html/vendor/pimcore/pimcore/models/Dependency/Dao.php(108): Doctrine\DBAL\Connection->fetchAll()
#4 [internal function]: Pimcore\Model\Dependency\Dao->save()
#5 /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(247): call_user_func_array()
#6 /var/www/html/vendor/pimcore/pimcore/models/Document.php(598): Pimcore\Model\AbstractModel->__call()
#7 /var/www/html/vendor/pimcore/pimcore/models/Document/Link.php(361): Pimcore\Model\Document->update()
#8 /var/www/html/vendor/pimcore/pimcore/models/Document.php(431): Pimcore\Model\Document\Link->update()
#9 /var/www/html/vendor/pimcore/pimcore/bundles/CoreBundle/Migrations/Version20191114123638.php(46): Pimcore\Model\Document->save()
#10 /var/www/html/vendor/pimcore/pimcore/lib/Migrations/Version.php(312): Pimcore\Bundle\CoreBundle\Migrations\Version20191114123638->up()
#11 /var/www/html/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php(172): Pimcore\Migrations\Version->execute()
#12 /var/www/html/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php(132): Doctrine\DBAL\Migrations\Migration->migrate()
#13 /var/www/html/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsMigrateDoctrineCommand.php(44): Doctrine\DBAL\Migrations\Tools\Console\Command\MigrateCommand->execute()
#14 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute()
#15 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(1019): Symfony\Component\Console\Command\Command->run()
#16 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(97): Symfony\Component\Console\Application->doRunCommand()
#17 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(271): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()
#18 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun()
#19 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(147): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
#20 /var/www/html/bin/console(26): Symfony\Component\Console\Application->run()
#21 {main}

Next Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT id, targetType, targetId FROM dependencies WHERE sourceType= ? AND sourceId = ?' with params ["document", 33]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'field list' in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60
Stack trace:
#0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(166): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException()
#1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(146): Doctrine\DBAL\DBALException::wrapException()
#2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(912): Doctrine\DBAL\DBALException::driverExceptionDuringQuery()
#3 /var/www/html/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(93): Doctrine\DBAL\Connection->executeQuery()
#4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(844): Pimcore\Db\Connection->executeQuery()
#5 /var/www/html/vendor/pimcore/pimcore/models/Dependency/Dao.php(108): Doctrine\DBAL\Connection->fetchAll()
#6 [internal function]: Pimcore\Model\Dependency\Dao->save()
#7 /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(247): call_user_func_array()
#8 /var/www/html/vendor/pimcore/pimcore/models/Document.php(598): Pimcore\Model\AbstractModel->__call()
#9 /var/www/html/vendor/pimcore/pimcore/models/Document/Link.php(361): Pimcore\Model\Document->update()
#10 /var/www/html/vendor/pimcore/pimcore/models/Document.php(431): Pimcore\Model\Document\Link->update()
#11 /var/www/html/vendor/pimcore/pimcore/bundles/CoreBundle/Migrations/Version20191114123638.php(46): Pimcore\Model\Document->save()
#12 /var/www/html/vendor/pimcore/pimcore/lib/Migrations/Version.php(312): Pimcore\Bundle\CoreBundle\Migrations\Version20191114123638->up()
#13 /var/www/html/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php(172): Pimcore\Migrations\Version->execute()
#14 /var/www/html/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php(132): Doctrine\DBAL\Migrations\Migration->migrate()
#15 /var/www/html/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsMigrateDoctrineCommand.php(44): Doctrine\DBAL\Migrations\Tools\Console\Command\MigrateCommand->execute()
#16 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute()
#17 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(1019): Symfony\Component\Console\Command\Command->run()
#18 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(97): Symfony\Component\Console\Application->doRunCommand()
#19 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(271): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()
#20 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun()
#21 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(147): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
#22 /var/www/html/bin/console(26): Symfony\Component\Console\Application->run()
#23 {main}
Migration 20191114123638 failed during Execution. Error An exception occurred while executing 'SELECT id, targetType, targetId FROM dependencies WHERE sourceType= ? AND sourceId = ?' with params ["document", 33]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'field list'

In AbstractMySQLDriver.php line 60:

  An exception occurred while executing 'SELECT id, targetType, targetId FROM
   dependencies WHERE sourceType= ? AND sourceId = ?' with params ["document"
  , 33]:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'field list'


In PDOStatement.php line 123:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'field list'


In PDOStatement.php line 121:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'field list'


```

**Comment by dvesh3** [comment]
@brusch what do you think about using postUp? ( https://www.doctrine-project.org/projects/doctrine-migrations/en/2.2/reference/migration-classes.html#postup) to execute document after sql changes.

**Comment by brusch** [comment]
Don't know if this fixes the issue, but we can try. 
It this doesn't help, we'd have to do: `\Pimcore\Db::get()->query()` which runs the SQL immediately. 
@dvesh3 can you investigate?

**Comment by dvesh3** [comment]
@brusch thanks for your suggestion and i'll create a PR accordingly 😉

**Comment by Yivan** [comment]
Whaow this is fast fix!! Seems good, thanks a lot.
