### ISSUE TITLE
classes:rebuild -d fails when trying to delete a class

### ISSUE THREAD

**Issue by beheist** [pimcore/pimcore#6640]
### Expected behavior
`bin/console pimcore:deployment:classes-rebuild -c -d` should delete class definitions that do not exist anymore.

### Actual behavior
Error message:
```
$ bin/console pimcore:deployment:classes-rebuild -c -d

 You are going to delete classes that don't have class-definitions anymore. This could lead to data loss! Do you want to continue? (yes/no) [no]:
 > yes

06:56:38 ERROR     [pimcore] Exception: Class definition with name ResearchArea or ID researcharea does not exist in C:\src\client\client-website\pimcore\vendor\pimcore\pimcore\models\DataObject\ClassDefinition.php:224
Stack trace:
#0 C:\src\client\client-website\pimcore\vendor\pimcore\pimcore\models\DataObject\Concrete.php(421): Pimcore\Model\DataObject\ClassDefinition::getById('researcharea')
#1 C:\src\client\client-website\pimcore\vendor\pimcore\pimcore\models\DataObject\Concrete\Dao.php(148): Pimcore\Model\DataObject\Concrete->getClass()
#2 C:\src\client\client-website\pimcore\vendor\pimcore\pimcore\models\DataObject\Concrete\Dao.php(58): Pimcore\Model\DataObject\Concrete\Dao->getData()
#3 C:\src\client\client-website\pimcore\vendor\pimcore\pimcore\models\DataObject\AbstractObject.php(299): Pimcore\Model\DataObject\Concrete\Dao->getById(2785)
#4 C:\src\client\client-website\pimcore\vendor\pimcore\pimcore\models\DataObject\Listing\Dao.php(94): Pimcore\Model\DataObject\AbstractObject::getById(2785)
#5 [internal function]: Pimcore\Model\DataObject\Listing\Dao->load()
#6 C:\src\client\client-website\pimcore\vendor\pimcore\pimcore\lib\Model\AbstractModel.php(247): call_user_func_array(Array, Array)
#7 C:\src\client\client-website\pimcore\vendor\pimcore\pimcore\models\DataObject\ClassDefinition.php(649): Pimcore\Model\AbstractModel->__call('load', Array)
#8 C:\src\client\client-website\pimcore\vendor\pimcore\pimcore\lib\Model\DataObject\ClassDefinition\ClassDefinitionManager.php(47): Pimcore\Model\DataObject\ClassDefinition->delete()
#9 C:\src\client\client-website\pimcore\vendor\pimcore\pimcore\bundles\CoreBundle\Command\ClassesRebuildCommand.php(82): Pimcore\Model\DataObject\ClassDefinition\ClassDefinitionManager->cleanUpDeletedClassDefinitions()
#10 C:\src\client\client-website\pimcore\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php(255): Pimcore\Bundle\CoreBundle\Command\ClassesRebuildCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 C:\src\client\client-website\pimcore\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(1019): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\src\client\client-website\pimcore\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php(97): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\ClassesRebuildCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 C:\src\client\client-website\pimcore\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(271): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\ClassesRebuildCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 C:\src\client\client-website\pimcore\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php(83): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 C:\src\client\client-website\pimcore\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(147): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 C:\src\client\client-website\pimcore\bin\console(36): Symfony\Component\Console\Application->run()
#17 {main}

In Dao.php line 148:

  Call to a member function getFieldDefinitions() on null


pimcore:deployment:classes-rebuild [-c|--create-classes] [-d|--delete-classes] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--ignore-maintenance-mode] [--maintenance-mode] [-e|--env ENV] [--no-debug] [--] <command>

```

### Steps to reproduce
* Install Pimcore
* Create a class definition
* Create an object
* Delete the object again (not sure if this is even necessary)
* Delete the class definition
* Run the command above.

Verified on Pimcore 6.2.x and 6.6.4.
Thanks!

**Comment by dvesh3** [comment]
Class definition error messages are regression of https://github.com/pimcore/pimcore/pull/4902
