### ISSUE TITLE
Video Conversion with FFMPEG broken in latest version

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#755]
# Bug Report
I'm using latest Pimcore (4.1.3) and latest ffmpeg (3.1.1) on a Debian System. The pimcore requirements check for ffmpeg is passed.
If I upload a video file to assets, a thumbnail image for the navigation tree is created. If I click on the asset I'll see a screenshot of the video and a rotating spinner - preview is being created for a second.

In this time, I can see a small video file is created in /var/system (by FTP access). The file is being moved to the var/tmp/video-thumbnails folder a second later but it is broken (not playable by download). The file size does vary slightly.

Error message in the backend:

> Preview not available
> Error unknown, please check the debug.log 

This is my debug log for this transaction:
http://pringuin.de/debuglog.txt

This is the ffmpeg error log which is created automatically in /var/logs of pimcore:
http://pringuin.de/ffmpeg.error.txt

If I run this command in my SSH, it'll create a perfectly working and bigger video file in /var/system:

> /usr/bin/nohup /usr/bin/nice -n 19 /usr/bin/ffmpeg -i /pimcorevhost/website/var/assets/test/shadow-of-mordor.mp4 -threads 0 -strict experimental -f mp4 -vcodec libx264 -acodec aac -g 100 -pix_fmt yuv420p -movflags faststart -ab 128k -vb 700k -vf "scale=500:trunc(ow/a/vsub)*vsub" /pimcorevhost/website/var/system/shadow-of-mordor.mp4 > /pimcorevhost/website/var/log/ffmpeg-578f7bb94dce0-mp4.log 2>&1 & echo $!

I think pimcore is moving the file from /var/system to var/tmp/video-thumbnails before ffmpeg finished the video conversion. Maybe Pimcore is not able to read the current ffmpeg state?

I'm happy to debug this further if needed. Any advice would be very welcome.

**Comment by brusch** [comment]
I recently did some refactoring on this topic: 
https://github.com/pimcore/pimcore/commit/08b3186ce8767bd172471b19ace0240cf6846f58 

Please try it again with the latest version of pimcore, if there are still issues, please come back on this issue. 

Thanks!

**Comment by Cruiser13** [comment]
This works fine with 4.2.0, thanks for the fast fix!

**Comment by Cruiser13** [comment]
@brusch I noticed one small thing - I have entries in my PHP error log like this: PHP Warning:  file_get_contents(/pimcorevhost/website/var/log/ffmpeg-5790a5d6d52a5-mp4.log): failed to open stream: No such file or directory in /pimcorevhost/pimcore/lib/Pimcore/Video/Adapter/Ffmpeg.php on line 190

The log is generated on each run but it has a different filename (at the error above it was ffmpeg-578e358ca00c7-mp4.error.log ). Video generation does work fine though.

**Comment by brusch** [comment]
@Cruiser13 this happens all the time, or just in some edge cases?

**Comment by Cruiser13** [comment]
@brusch it happened on 7 out of 7 for me.

**Comment by smaier** [comment]
is it possible, that the problem reappeared in Pimcore 4.4(.1) ? (build 4008)
We have got the exact same behaviour described in the original Bug-Report.
[thumbnail:video-output.txt](https://github.com/pimcore/pimcore/files/670417/thumbnail.video-output.txt)

Direct execution of the command generated in the debug.log succeeds.

`/usr/bin/timeout 60s /home/sussxcbq/bin/ffmpeg -i '/home/sussxcbq/www.suss.com/suess/www/website/var/assets/videos/schlitten.mp4' -vcodec png -vframes 1 -vf scale=iw*sar:ih -ss 2 '/home/sussxcbq/www.suss.com/suess/www/website/var/tmp/video-image-cache/video_66__thumbnail_2.png' 2> /dev/null`

**Comment by smaier** [comment]
Update: fault seems to have been on our side - we missplaced a Video-Thumbnail with a regular Image-Thumnail in the template which lead to this strange behaviour

**Comment by smaier** [comment]
Another Update - although we fixed our Setup the video-thumbnails cannot be generated.
I appended a log file with pimcores call and ffmpegs error - im totally stuck here.
[ffmpeg_wrapper_debug.txt](https://github.com/pimcore/pimcore/files/670838/ffmpeg_wrapper_debug.txt)

**Comment by alabady** [comment]
I'm using Version: 4.6.3 and Build: 4109
i have same issue here!
when processing on uploaded video done it's shows:
`No video with supported format and MIME type found.`
**NOTE** i'm using _S3_ locally, and i mount my bucket `test_dam` in my web server using _s3fs_
in my _debug.log_ file i have:
`
[2018-04-14 09:51:12] core.ERROR: Thumbnail with name 'auto_10d818d44b781d3f700d2fb0126abee5' doesn't exist {"origin":"Pimcore\\Controller\\Plugin\\Thumbnail->routeStartup() on line 111","memory":"  1 MB"} []
[2018-04-14 09:51:27] core.ERROR: Couldn't load document /home/test2_dam/assets/documents/example.docx only PDF documents are currently supported {"origin":"Pimcore\\Document\\Adapter\\Ghostscript->getPdf() on line 129","memory":"  3 MB"} []
[2018-04-14 09:51:27] core.ERROR: Couldn't load document /home/test2_dam/assets/documents/example-excel.xlsx only PDF documents are currently supported {"origin":"Pimcore\\Document\\Adapter\\Ghostscript->getPdf() on line 129","memory":"  3 MB"} []
[2018-04-14 09:51:28] core.ERROR: Couldn't convert document to PDF: /home/test2_dam/assets/documents/example.docx with the command: 'soffice --headless --nologo --nofirststartwizard --norestore --convert-to pdf:writer_web_pdf_Export --outdir '/var/www/pimcore/website/var/system' '/home/test2_dam/assets/documents/example.docx'' {"origin":"Pimcore\\Document\\Adapter\\LibreOffice->getPdf() on line 158","memory":"  3 MB"} []
[2018-04-14 09:51:28] core.ERROR: Couldn't create image-thumbnail of document /documents/example.docx {"origin":"Pimcore\\Model\\Asset\\Document\\ImageThumbnail->generate() on line 162","memory":"  3 MB"} []
[2018-04-14 09:51:28] core.ERROR: Exception: Couldn't convert document to PDF: /home/test2_dam/assets/documents/example.docx with the command: 'soffice --headless --nologo --nofirststartwizard --norestore --convert-to pdf:writer_web_pdf_Export --outdir '/var/www/pimcore/website/var/system' '/home/test2_dam/assets/documents/example.docx'' in /var/www/pimcore/pimcore/lib/Pimcore/Document/Adapter/LibreOffice.php:159 Stack trace: #0 /var/www/pimcore/pimcore/lib/Pimcore/Document/Adapter/LibreOffice.php(97): Pimcore\Document\Adapter\LibreOffice->getPdf('/home/test2_dam...') #1 /var/www/pimcore/pimcore/models/Asset/Document/ImageThumbnail.php(138): Pimcore\Document\Adapter\LibreOffice->load('/home/test2_dam...') #2 /var/www/pimcore/pimcore/models/Asset/Document/ImageThumbnail.php(114): Pimcore\Model\Asset\Document\ImageThumbnail->generate() #3 /var/www/pimcore/pimcore/modules/admin/controllers/AssetController.php(1150): Pimcore\Model\Asset\Document\ImageThumbnail->getFileSystemPath() #4 /var/www/pimcore/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): Admin_AssetController->getDocumentThumbnailAction() #5 /var/www/pimcore/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('getDocumentThum...') #6 /var/www/pimcore/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) #7 /var/www/pimcore/pimcore/lib/Pimcore.php(152): Zend_Controller_Front->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) #8 /var/www/pimcore/pimcore/lib/Pimcore.php(125): Pimcore::runDispatcher(Object(Zend_Controller_Front), false, NULL, NULL) #9 /var/www/pimcore/index.php(18): Pimcore::run() #10 {main} {"origin":"Pimcore\\Model\\Asset\\Document\\ImageThumbnail->generate() on line 163","memory":"  3 MB"} []
[2018-04-14 09:51:29] core.ERROR: Couldn't convert document to PDF: /home/test2_dam/assets/documents/example-excel.xlsx with the command: 'soffice --headless --nologo --nofirststartwizard --norestore --convert-to pdf:writer_web_pdf_Export --outdir '/var/www/pimcore/website/var/system' '/home/test2_dam/assets/documents/example-excel.xlsx'' {"origin":"Pimcore\\Document\\Adapter\\LibreOffice->getPdf() on line 158","memory":"  3 MB"} []
[2018-04-14 09:51:29] core.ERROR: Couldn't create image-thumbnail of document /documents/example-excel.xlsx {"origin":"Pimcore\\Model\\Asset\\Document\\ImageThumbnail->generate() on line 162","memory":"  3 MB"} []
[2018-04-14 09:51:29] core.ERROR: Exception: Couldn't convert document to PDF: /home/test2_dam/assets/documents/example-excel.xlsx with the command: 'soffice --headless --nologo --nofirststartwizard --norestore --convert-to pdf:writer_web_pdf_Export --outdir '/var/www/pimcore/website/var/system' '/home/test2_dam/assets/documents/example-excel.xlsx'' in /var/www/pimcore/pimcore/lib/Pimcore/Document/Adapter/LibreOffice.php:159 Stack trace: #0 /var/www/pimcore/pimcore/lib/Pimcore/Document/Adapter/LibreOffice.php(97): Pimcore\Document\Adapter\LibreOffice->getPdf('/home/test2_dam...') #1 /var/www/pimcore/pimcore/models/Asset/Document/ImageThumbnail.php(138): Pimcore\Document\Adapter\LibreOffice->load('/home/test2_dam...') #2 /var/www/pimcore/pimcore/models/Asset/Document/ImageThumbnail.php(114): Pimcore\Model\Asset\Document\ImageThumbnail->generate() #3 /var/www/pimcore/pimcore/modules/admin/controllers/AssetController.php(1150): Pimcore\Model\Asset\Document\ImageThumbnail->getFileSystemPath() #4 /var/www/pimcore/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): Admin_AssetController->getDocumentThumbnailAction() #5 /var/www/pimcore/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('getDocumentThum...') #6 /var/www/pimcore/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) #7 /var/www/pimcore/pimcore/lib/Pimcore.php(152): Zend_Controller_Front->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) #8 /var/www/pimcore/pimcore/lib/Pimcore.php(125): Pimcore::runDispatcher(Object(Zend_Controller_Front), false, NULL, NULL) #9 /var/www/pimcore/index.php(18): Pimcore::run() #10 {main} {"origin":"Pimcore\\Model\\Asset\\Document\\ImageThumbnail->generate() on line 163","memory":"  3 MB"} []
`
