### ISSUE TITLE
Paginator with addConditionParam cause SQL error

### ISSUE THREAD

**Issue by jansarmir** [pimcore/pimcore#780]
After installing 4.2 or latest 3900, i have following problem

I create object list like this:
```php
$this->list = new $this->list();
$this->list->setLocale($locale);
$this->list->addConditionParam("LENGTH(`title`)>0");
$this->list->addConditionParam("(`publishFrom` IS NULL OR `publishFrom`='' OR `publishFrom`<?)", time());
$this->list->addConditionParam("`project`=?", $project);
```
calling this ends with error: **mysqli_stmt::bind_param(): Number of variables doesn't match number of parameters in prepared statement**
```php
$paginator = \Zend_Paginator::factory($this->list);
$paginator->setCurrentPageNumber($page);
$paginator->setItemCountPerPage($itemCount);
```
there is duplication for variables with this scenario:
```php
Array (     [0] => 1470086961     [1] => project     [2] => 1470086961     [3] => project )
```
after transforming it into simple condition, it works
```php
$this->list = new $this->list();
$this->list->setLocale($locale);
$this->list->setCondition("LENGTH(`title`)>0 AND (`publishFrom` IS NULL OR `publishFrom`='' OR `publishFrom`<?) AND `project`=?", [
            time(),
            $project
]);
```
mixing setCondition and addConditionParam doesnt work either

little dump may helps
```
[2016-08-01 23:29:21] core.INFO: Exception in C:\Repository\tools\pimcore\lib\Pimcore\Model\Listing\AbstractListing.php:364 Stack trace: 

#0 C:\Repository\tools\pimcore\lib\Pimcore\Model\Listing\AbstractListing.php(274): Pimcore\Model\Listing\AbstractListing->setConditionVariables(Array) 
#1 C:\Repository\tools\pimcore\models\Object\Listing\Dao.php(168): Pimcore\Model\Listing\AbstractListing->getCondition() 
#2 C:\Repository\tools\pimcore\models\Object\Listing\Concrete\Dao.php(71): Pimcore\Model\Object\Listing\Dao->addConditions(Object(Zend_Db_Select)) 
#3 C:\Repository\tools\pimcore\models\Object\Listing\Dao.php(104): Pimcore\Model\Object\Listing\Concrete\Dao->getQuery() 
#4 [internal function]: Pimcore\Model\Object\Listing\Dao->getTotalCount() 
#5 C:\Repository\tools\pimcore\lib\Pimcore\Model\AbstractModel.php(256): call_user_func_array(Array, Array) 
#6 C:\Repository\tools\pimcore\models\Object\Listing.php(191): Pimcore\Model\AbstractModel->__call('getTotalCount', Array) 
#7 [internal function]: Pimcore\Model\Object\Listing->count() 
#8 C:\Repository\tools\vendor\zendframework\zendframework1\library\Zend\Paginator.php(534): count(Object(Pimcore\Model\Object\RsInfosNews\Listing)) 
#9 C:\Repository\tools\vendor\zendframework\zendframework1\library\Zend\Paginator.php(1081): Zend_Paginator->getTotalItemCount() 
#10 C:\Repository\tools\vendor\zendframework\zendframework1\library\Zend\Paginator.php(753): Zend_Paginator->_calculatePageCount() 
#11 C:\Repository\tools\vendor-rs\Rs\Core\Find\All.php(30): Zend_Paginator->setItemCountPerPage(10) 
#12 C:\Repository\tools\website\controllers\Rs\InfosController.php(34): Rs\Core\Find\All->paging(10, 0) 
#13 C:\Repository\tools\vendor\zendframework\zendframework1\library\Zend\Controller\Action.php(516): Rs_InfosController->genericListAction() 
#14 C:\Repository\tools\vendor\zendframework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('genericListActi...') 
#15 C:\Repository\tools\vendor\zendframework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) 
#16 C:\Repository\tools\pimcore\lib\Pimcore.php(265): Zend_Controller_Front->dispatch() 
#17 C:\Repository\tools\index.php(18): Pimcore::run() 
#18 {main} {"origin":"Pimcore\\Model\\Listing\\AbstractListing->setConditionVariables() on line 364","memory":" 10 MB"} []

[2016-08-01 23:29:21] core.INFO: Exception in C:\Repository\tools\pimcore\lib\Pimcore\Model\Listing\AbstractListing.php:364 Stack trace: 
#0 C:\Repository\tools\pimcore\lib\Pimcore\Model\Listing\AbstractListing.php(274): Pimcore\Model\Listing\AbstractListing->setConditionVariables(Array) 
#1 C:\Repository\tools\pimcore\models\Object\Listing\Dao.php(168): Pimcore\Model\Listing\AbstractListing->getCondition() 
#2 C:\Repository\tools\pimcore\models\Object\Listing\Concrete\Dao.php(71): Pimcore\Model\Object\Listing\Dao->addConditions(Object(Zend_Db_Select)) 
#3 C:\Repository\tools\pimcore\models\Object\Listing\Dao.php(139): Pimcore\Model\Object\Listing\Concrete\Dao->getQuery(true) 
#4 C:\Repository\tools\pimcore\models\Object\Listing\Concrete\Dao.php(97): Pimcore\Model\Object\Listing\Dao->loadIdList() 
#5 C:\Repository\tools\pimcore\models\Object\Listing\Dao.php(110): Pimcore\Model\Object\Listing\Concrete\Dao->loadIdList() 
#6 [internal function]: Pimcore\Model\Object\Listing\Dao->getTotalCount() 
#7 C:\Repository\tools\pimcore\lib\Pimcore\Model\AbstractModel.php(256): call_user_func_array(Array, Array) 
#8 C:\Repository\tools\pimcore\models\Object\Listing.php(191): Pimcore\Model\AbstractModel->__call('getTotalCount', Array) 
#9 [internal function]: Pimcore\Model\Object\Listing->count() 
#10 C:\Repository\tools\vendor\zendframework\zendframework1\library\Zend\Paginator.php(534): count(Object(Pimcore\Model\Object\RsInfosNews\Listing)) 
#11 C:\Repository\tools\vendor\zendframework\zendframework1\library\Zend\Paginator.php(1081): Zend_Paginator->getTotalItemCount() 
#12 C:\Repository\tools\vendor\zendframework\zendframework1\library\Zend\Paginator.php(753): Zend_Paginator->_calculatePageCount() 
#13 C:\Repository\tools\vendor-rs\Rs\Core\Find\All.php(30): Zend_Paginator->setItemCountPerPage(10) 
#14 C:\Repository\tools\website\controllers\Rs\InfosController.php(34): Rs\Core\Find\All->paging(10, 0) 
#15 C:\Repository\tools\vendor\zendframework\zendframework1\library\Zend\Controller\Action.php(516): Rs_InfosController->genericListAction() 
#16 C:\Repository\tools\vendor\zendframework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('genericListActi...') 
#17 C:\Repository\tools\vendor\zendframework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) 
#18 C:\Repository\tools\pimcore\lib\Pimcore.php(265): Zend_Controller_Front->dispatch() 
#19 C:\Repository\tools\index.php(18): Pimcore::run() 
#20 {main} {"origin":"Pimcore\\Model\\Listing\\AbstractListing->setConditionVariables() on line 364","memory":" 10 MB"} []
```

**Comment by mrudnicki** [comment]
Hi @jansarmir,
The proper way to add binding parameter to your query looks like below:

```
$list->addConditionParam("(`publishFrom` IS NULL OR `publishFrom`='' OR `publishFrom` < ?)", array(time()));
```

The example which you've presented generates SQL syntax error. 

Try bind the parameter in an array and let me know if it works well. I've already checked your case in my environment and looks fine.

**Comment by jansarmir** [comment]
check this:
Pimcore\Model\Listing\AbstractListing -> getCondition
*before* $params = [];
*now* $params = $this->getConditionVariables();
*all* $this->setConditionVariables($params);
calling getCondition multiple times cause bind_param duplication
that's why pagination cause problem for me (still in 4.3.0)

**Comment by brusch** [comment]
What do you mean by _before_, _now_ and _all_?

**Comment by brusch** [comment]
Just did the following test:
```php
        $list = new Object\News\Listing();
        $list->addConditionParam("length(title) > ?", 1);
        $list->addConditionParam("title like ?", "eget");

        echo $list->getCondition();
        echo "<br>";
        echo "<br>";
        echo $list->getCondition();

        $list->load();

        exit;
```
worked without problems. 

So please provide us a test case where we are able to reproduce the problem. 
Thanks!

**Comment by jansarmir** [comment]
i'll do more research

**Comment by brusch** [comment]
@jansarmir great, thanks for your feedback!
