### ISSUE TITLE
Commands that contain Parallelization fail

### ISSUE THREAD

**Issue by ayoob-lfc** [pimcore/pimcore#7917]
### Expected behavior

When i run the following command, im expecting the command to run without any errors (pimcore 6.8.6):

`sudo <path to project>/bin/console --env=prod ecommerce:indexservice:process-preparation-queue`

### Actual behavior

I get the following error:

```
In Assert.php line 2042:
                                   
  [InvalidArgumentException]       
  Expected a string. Got: boolean  
                                   

Exception trace:
  at /<path to project>/vendor/webmozart/assert/src/Assert.php:2042
 Webmozart\Assert\Assert::reportInvalidArgument() at /<path to project>/vendor/webmozart/assert/src/Assert.php:52
 Webmozart\Assert\Assert::string() at /<path to project>/vendor/webmozart/assert/src/Assert.php:1411
 Webmozart\Assert\Assert::fileExists() at /<path to project>/vendor/webmozarts/console-parallelization/src/Parallelization.php:359
 Pimcore\Bundle\EcommerceFrameworkBundle\Command\IndexService\ProcessPreparationQueueCommand->executeMasterProcess() at /<path to project>/vendor/webmozarts/console-parallelization/src/Parallelization.php:273
 Pimcore\Bundle\EcommerceFrameworkBundle\Command\IndexService\ProcessPreparationQueueCommand->execute() at /<path to project>/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /<path to project>/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:1027
 Symfony\Component\Console\Application->doRunCommand() at /<path to project>/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:97
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /<path to project>/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /<path to project>/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /<path to project>/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:149
 Symfony\Component\Console\Application->run() at /<path to project>/vendor/pimcore/pimcore/bin/console:36
```

### Possible solution

Replace **getcwd()** with **PIMCORE_PROJECT_ROOT** here:

https://github.com/webmozarts/console-parallelization/blob/master/src/Parallelization.php#L356

```
            ...
            $consolePath = realpath(PIMCORE_PROJECT_ROOT.'/bin/console');
            Assert::fileExists(
                $consolePath,
                sprintf('The bin/console file could not be found at %s', PIMCORE_PROJECT_ROOT))
            ;
            ...
```

However i'm not sure this is the correct way of fixing this issue.

Once I do get it working and run the command again:

`sudo <path to project>/bin/console --env=prod ecommerce:indexservice:process-preparation-queue`

I then get the following Error:

```
Failed to process "a:3:{s:2:"id";s:5:"54167";s:7:"tenants";a:1:{i:0;s:17:"ProductDataTenant";}s:10:"numTenants";s:1:"1";}": Argument 1 passed to Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Worker\ElasticSearch\AbstractElasticSearch::deleteFromIndex() must be an instance of Pimcore\Bundle\EcommerceFrameworkBundle\Model\IndexableInterface, null given, called in /<path to project>/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/Command/IndexService/ProcessPreparationQueueCommand.php on line 119
#0 /<path to project>/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/Command/IndexService/ProcessPreparationQueueCommand.php(119): Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Worker\ElasticSearch\AbstractElasticSearch->deleteFromIndex(NULL)
#1 /<path to project>/vendor/webmozarts/console-parallelization/src/Parallelization.php(479): Pimcore\Bundle\EcommerceFrameworkBundle\Command\IndexService\ProcessPreparationQueueCommand->runSingleCommand('a:3:{s:2:"id";s...', Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /<path to project>/vendor/webmozarts/console-parallelization/src/Parallelization.php(432): Pimcore\Bundle\EcommerceFrameworkBundle\Command\IndexService\ProcessPreparationQueueCommand->runTolerantSingleCommand('a:3:{s:2:"id";s...', Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /<path to project>/vendor/webmozarts/console-parallelization/src/Parallelization.php(268): Pimcore\Bundle\EcommerceFrameworkBundle\Command\IndexService\ProcessPreparationQueueCommand->executeChildProcess(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /<path to project>/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): Pimcore\Bundle\EcommerceFrameworkBundle\Command\IndexService\ProcessPreparationQueueCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /<path to project>/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /<path to project>/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(97): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\EcommerceFrameworkBundle\Command\IndexService\ProcessPreparationQueueCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /<path to project>/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(273): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\EcommerceFrameworkBundle\Command\IndexService\ProcessPreparationQueueCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /<path to project>/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /<path to project>/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /<path to project>/vendor/pimcore/pimcore/bin/console(36): Symfony\Component\Console\Application->run()
#11 {main}
```

Which happens if **$indexableObject** is NULL here:

https://github.com/pimcore/pimcore/blob/master/bundles/EcommerceFrameworkBundle/Command/IndexService/ProcessPreparationQueueCommand.php#L119

Now i'm not sure if this is related to this issue or if its a separate issue altogether.

**Comment by brusch** [comment]
@ayoob-lfc This doesn't seem to be a generic problem (I cannot reproduce it), looks more like a project-specific issue to me. 
Also `webmozarts/console-parallelization` is a third party package which cannot be individualized for Pimcore 😉
