### ISSUE TITLE
[BUG] Call to a member function supportsInheritance() on null

### ISSUE THREAD

**Issue by RuudvdvNB** [pimcore/pimcore#7967]
# Bug Report

### Expected behavior
When working with multiple languages i expect that i would be able to add localized fields in objectbricks, use Data Object variants and have the localized data inherited. 

### Actual behavior
Sometimes (not always) when saving a variant we receive the an error (see below).

First the object is saved, after the save the Advanced Search is processing the object for indexing. In this proces a localized field is called through it's getter in `Content.php` Objectbrick. Because we are working with multiple variant levels (3 or 4 levels for easier inheritance of specific data) the DataObject `Localizedfield.php` is looping through the parents to find a value (https://github.com/pimcore/pimcore/blob/master/models/DataObject/Localizedfield.php#L473). Looks like this error is related to the `setGetInheritedValue` that is set in the Advanced Object search, but can also be set in your own code.

But when the parentContainer is selected by containertype/key/fieldname the context is lost. So the first iteration the context is:
```php
$context = [
    'containerType' => 'objectbrick',
    'containerKey' => 'Content',
    'fieldname' => 'content',
];
```

When the second parentContainer is selected (still a variant) the context changes to:
```php
$context = [
    'containerType' => 'objectbrick',
    'containerKey' => 'Content',
];
```

After this, the third parentContainer is selected (the main product) and the context chagned to:
```php
$context = [
    'object' => DataObject,
];
```

Error:
```
Status: 500 |
URL: /admin/object/save?task=publish
Method: PUT
Message: Call to a member function supportsInheritance() on null
Trace: 
in /var/www/html/vendor/pimcore/pimcore/models/DataObject/Localizedfield.php:444
#0 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Localizedfield.php(482): Pimcore\Model\DataObject\Localizedfield->getLocalizedValue('inspirationalTe...', 'en', true)
#1 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Localizedfield.php(482): Pimcore\Model\DataObject\Localizedfield->getLocalizedValue('inspirationalTe...', 'en', true)
#2 /var/www/html/var/classes/DataObject/Objectbrick/Data/Content.php(89): Pimcore\Model\DataObject\Localizedfield->getLocalizedValue('inspirationalTe...', 'en')
#3 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data.php(1576): Pimcore\Model\DataObject\Objectbrick\Data\Content->getInspirationalText()
#4 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data.php(234): Pimcore\Model\DataObject\ClassDefinition\Data->getDataFromObjectParam(Object(Pimcore\Model\DataObject\Objectbrick\Data\Content), Array)
#5 /var/www/html/vendor/pimcore/advanced-object-search/src/Filter/FieldDefinitionAdapter/DefaultAdapter.php(126): Pimcore\Model\DataObject\ClassDefinition\Data->getForWebserviceExport(Object(Pimcore\Model\DataObject\Objectbrick\Data\Content))
#6 /var/www/html/vendor/pimcore/advanced-object-search/src/Filter/FieldDefinitionAdapter/DefaultAdapter.php(145): AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\DefaultAdapter->doGetIndexDataValue(Object(Pimcore\Model\DataObject\Objectbrick\Data\Content), false)
#7 /var/www/html/vendor/pimcore/advanced-object-search/src/Filter/FieldDefinitionAdapter/Localizedfields.php(102): AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\DefaultAdapter->getIndexData(Object(Pimcore\Model\DataObject\Objectbrick\Data\Content))
#8 /var/www/html/vendor/pimcore/advanced-object-search/src/Filter/FieldDefinitionAdapter/Objectbricks.php(160): AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\Localizedfields->getIndexData(Object(Pimcore\Model\DataObject\Objectbrick\Data\Content))
#9 /var/www/html/vendor/pimcore/advanced-object-search/src/Service.php(375): AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\Objectbricks->getIndexData(Object(Pimcore\Model\DataObject\Product))
#10 /var/www/html/vendor/pimcore/advanced-object-search/src/Service.php(414): AdvancedObjectSearchBundle\Service->getIndexData(Object(Pimcore\Model\DataObject\Product))
#11 /var/www/html/vendor/pimcore/advanced-object-search/src/EventListener/IndexUpdateListener.php(45): AdvancedObjectSearchBundle\Service->doUpdateIndexData(Object(Pimcore\Model\DataObject\Product))
#12 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(126): AdvancedObjectSearchBundle\EventListener\IndexUpdateListener->updateObject(Object(Pimcore\Event\Model\DataObjectEvent), 'pimcore.dataobj...', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#13 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(264): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Pimcore\Event\Model\DataObjectEvent), 'pimcore.dataobj...', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#14 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'pimcore.dataobj...', Object(Pimcore\Event\Model\DataObjectEvent))
#15 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'pimcore.dataobj...', Object(Pimcore\Event\Model\DataObjectEvent))
#16 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php(168): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Pimcore\Event\Model\DataObjectEvent), 'pimcore.dataobj...')
#17 /var/www/html/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(714): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(Object(Pimcore\Event\Model\DataObjectEvent), Object(Pimcore\Event\Model\DataObjectEvent))
#18 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Concrete.php(746): Pimcore\Model\DataObject\AbstractObject->save(Array)
#19 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(1313): Pimcore\Model\DataObject\Concrete->save()
#20 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(158): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->saveAction(Object(Symfony\Component\HttpFoundation\Request))
#21 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#22 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#23 /var/www/html/web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#24 {main}
```

**Comment by dvesh3** [comment]
@RuudvdvNB Pimcore version? looking at the stack trace, it seems that you are using older version.

**Comment by RuudvdvNB** [comment]
Tested this on 6.8.5, updated to 6.8.7 still same error and also tested it on 6.8.x-dev

**Comment by dvesh3** [comment]
Could you please share steps to reproduce the issue? thanks!

**Comment by RuudvdvNB** [comment]
Hard to find the right steps to reproduce, we are looking into that right now. Will report back in this issue.
