### ISSUE TITLE
Class 'ColorSpace' not found

### ISSUE THREAD

**Issue by blankse** [pimcore/pimcore#8036]
# Bug Report

I tried to execute `$document->generatePdf(['disableBackgroundExecution' => true]);` via command. 

```
Error: Class 'ColorSpace' not found in /vendor/pimcore/pimcore/lib/Web2Print/Processor/PdfReactor8.php:132
Stack trace:
#0 /vendor/pimcore/pimcore/lib/Web2Print/Processor.php(113): Pimcore\Web2Print\Processor\PdfReactor8->buildPdf(Object(Pimcore\Model\Document\Printcontainer), Object(stdClass))
#1 /vendor/pimcore/pimcore/lib/Web2Print/Processor.php(88): Pimcore\Web2Print\Processor->startPdfGeneration(525)
#2 /vendor/pimcore/pimcore/models/Document/PrintAbstract.php(114): Pimcore\Web2Print\Processor->preparePdfGeneration(525, Array)
```

**Comment by brusch** [comment]
Fixed by #8053
