### ISSUE TITLE
 [Document] Link document cannot be opened anymore after target got deleted

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#8067]
Steps to reproduce:

* Create link document
* Assign an asset
* Save
* Delete the Asset
* Clear the cache
* Reload the document

Stack trace:

Message: Asset with ID 3 doesn't exists
Trace: 
in /home/josef/www/dev/pimcore/pimcore/models/Asset/Dao.php:74
#0 /home/josef/www/dev/pimcore/pimcore/models/Asset.php(283): Pimcore\Model\Asset\Dao->getById(3)
#1 /home/josef/www/dev/pimcore/pimcore/models/Document/Link.php(331): Pimcore\Model\Asset::getById(3)
#2 /home/josef/www/dev/pimcore/pimcore/models/Document/Link.php(242): Pimcore\Model\Document\Link->setObjectFromId()
#3 /home/josef/www/dev/pimcore/pimcore/lib/Model/AbstractModel.php(201): Pimcore\Model\Document\Link->setInternal('3')
#4 /home/josef/www/dev/pimcore/pimcore/lib/Model/AbstractModel.php(183): Pimcore\Model\AbstractModel->setValue('internal', '3')
#5 /home/josef/www/dev/pimcore/pimcore/lib/Model/Dao/DaoTrait.php(41): Pimcore\Model\AbstractModel->setValues(Array)
#6 /home/josef/www/dev/pimcore/pimcore/models/Document/Link/Dao.php(49): Pimcore\Model\Dao\AbstractDao->assignVariablesToModel(Array)
#7 /home/josef/www/dev/pimcore/pimcore/models/Document.php(297): Pimcore\Model\Document\Link\Dao->getById(202)
#8 /home/josef/www/dev/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/LinkController.php(74): Pimcore\Model\Document::getById(202)
#9 /home/josef/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(157): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\LinkController->getDataByIdAction(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\Serializer\Serializer))
#10 /home/josef/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(79): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#11 /home/josef/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(195): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /home/josef/www/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}

**Comment by weisswurstkanone** [comment]
Not an issue on 6.8, just on master.

Side effect of https://github.com/pimcore/pimcore/pull/7579

Will be fixed together with https://github.com/pimcore/pimcore/issues/8030
