### ISSUE TITLE
DocumentRenderer::render() broken

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#8140]
# Bug Report
When calling `DocumentRenderer::render`, GlobalTemplateVariablesListener throws exception "Unable to add global "document" as the runtime or the extensions have already been initialized."

```php
Message: Unable to add global "document" as the runtime or the extensions have already been initialized.
Trace: 
in ../vendor/twig/twig/src/Environment.php:907
#0 ../dev/pimcore/pimcore/bundles/CoreBundle/EventListener/Frontend/GlobalTemplateVariablesListener.php(88): Twig\Environment->addGlobal('document', Object(Pimcore\Model\Document\Email))
#1 ../vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(117): Pimcore\Bundle\CoreBundle\EventListener\Frontend\GlobalTemplateVariablesListener->onKernelController(Object(Symfony\Component\HttpKernel\Event\ControllerEvent), 'kernel.controll...', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#2 ../vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(230): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\ControllerEvent), 'kernel.controll...', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#3 ../vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'kernel.controll...', Object(Symfony\Component\HttpKernel\Event\ControllerEvent))
#4 ../vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php(151): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\ControllerEvent), 'kernel.controll...')
#5 ../vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(145): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\ControllerEvent), 'kernel.controll...')
#6 ../vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(79): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 2)
#7 ../vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/SubRequestHandler.php(85): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 2, false)
#8 ../vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Fragment/InlineFragmentRenderer.php(80): Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle(Object(Symfony\Component\HttpKernel\HttpKernel), Object(Symfony\Component\HttpFoundation\Request), 2, false)
#9 ../dev/pimcore/pimcore/lib/Document/Renderer/DocumentRenderer.php(145): Symfony\Component\HttpKernel\Fragment\InlineFragmentRenderer->render('/_fragment?_pat...', Object(Symfony\Component\HttpFoundation\Request), Array)
#10 ../dev/pimcore/pimcore/models/Document/Service.php(88): Pimcore\Document\Renderer\DocumentRenderer->render(Object(Pimcore\Model\Document\Email), Array, Array, Array)
```
https://github.com/pimcore/pimcore/blob/master/bundles/CoreBundle/EventListener/Frontend/GlobalTemplateVariablesListener.php#L88

**Comment by brusch** [comment]
Seems to happen just under certain circumstances, e.g. the following code snippet works for me: 
```php
    /**
     * @Route("/bernie/test")
     *
     * @param Request $request
     */
    public function testAction(Request $request) {
        $snippet = Document::getById(35);
        $foo = Document\Service::render($snippet);
    }
```

**Comment by dvesh3** [comment]
@brusch 
Steps to reproduce:
 1. open Newsletter Document (`/en/newsletter/Sample Newsletter`).
 2. click Send Test Email.
 3. Add details(To, Subject) and click send.
