### ISSUE TITLE
Cannot save QuantityValues in ClassificationStore

### ISSUE THREAD

**Issue by mugge6** [pimcore/pimcore#8188]
# Bug Report

Since upgrade to Pimcore 6.8.9 it's impossible to save DataObject with ClassificationStore items from type QuantityValue. Perhaps has something to do with issue #8116

```
Timestamp: Tue Feb 16 2021 14:38:55 GMT+0100 (Central European Standard Time)
Status: 500 | Internal Server Error
URL: /admin/object/save?task=publish
Method: PUT
Message: Cannot use object of type stdClass as array
Trace: 
in /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/QuantityValue.php:682
#0 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/Classificationstore/Service.php(90): Pimcore\Model\DataObject\ClassDefinition\Data\QuantityValue::__set_state(Object(Pimcore\Model\DataObject\ClassDefinition\Data\QuantityValue))
#1 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Classificationstore.php(1006): Pimcore\Model\DataObject\Classificationstore\Service::getFieldDefinitionFromJson(Object(stdClass), 'quantityValue')
#2 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/Concrete.php(127): Pimcore\Model\DataObject\ClassDefinition\Data\Classificationstore->checkValidity(Object(Pimcore\Model\DataObject\Classificationstore), false)
#3 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(659): Pimcore\Model\DataObject\Concrete->update(true, Array)
#4 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/Concrete.php(748): Pimcore\Model\DataObject\AbstractObject->save(Array)
#5 /var/www/pimcore/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(1260): Pimcore\Model\DataObject\Concrete->save()
#6 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(158): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->saveAction(Object(Symfony\Component\HttpFoundation\Request))
#7 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#8 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 /var/www/pimcore/web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#10 {main}
```

**Comment by brusch** [comment]
Resolved by #8193
