### ISSUE TITLE
[Pimcore X] Warning: Undefined array key "versions"

### ISSUE THREAD

**Issue by themreza** [pimcore/pimcore#8883]
# Bug Report

**Pimcore version: v10.0.0-BETA3**

### Expected behavior
Similar to version 6.x, I should be able to create new Data Objects after defining them.

### Actual behavior
An error message prevents creating a new object: Failed to create new item, please try again.
Details:  Warning: Undefined array key "versions"

The same issue happens when creating a blank document:

```
Timestamp: Sun Apr 25 2021 08:14:14 GMT+0200 (Central European Summer Time)
Status: 500 | Internal Server Error
URL: /admin/document/add
Method: POST
Message: Warning: Undefined array key "versions"
Trace: 
in /var/www/html/vendor/pimcore/pimcore/models/Document/PageSnippet.php:158
#0 /var/www/html/vendor/pimcore/pimcore/models/Document/PageSnippet.php(121): Pimcore\Model\Document\PageSnippet->saveVersion(false, false, NULL)
#1 /var/www/html/vendor/pimcore/pimcore/models/Document.php(423): Pimcore\Model\Document\PageSnippet->update(Array)
#2 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/DocumentController.php(279): Pimcore\Model\Document->save()
#3 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(157): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\DocumentController->addAction(Object(Symfony\Component\HttpFoundation\Request))
#4 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(79): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(195): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/html/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#7 {main}
```

Screencast:

https://user-images.githubusercontent.com/5465057/115983014-1378d080-a59f-11eb-9fb6-17c09630301b.mp4

### Steps to reproduce
Follow the guide on https://github.com/pimcore/skeleton to install Pimcore using Docker

Installation summary:

```bash
mkdir pimcore && cd pimcore
wget https://github.com/pimcore/skeleton/blob/master/docker-compose.yml
docker-compose up -d
docker exec -it --user=www-data pimcore-debug-php /bin/bash
rm docker-compose.yml # emptying the directory to install Pimcore
COMPOSER_MEMORY_LIMIT=-1 composer create-project pimcore/skeleton:10.0.x-dev .
./vendor/bin/pimcore-install
```

Define a new simple Data Object with a panel and input field.

Add a new object by right clicking on the Home item within the Data Objects accordion panel, type a name, and click add.

This error also happens when creating a new document in the Document accordion, Home, Add Page, > Blank.

**Comment by weisswurstkanone** [comment]
regression of https://github.com/pimcore/pimcore/pull/8577
