### ISSUE TITLE
[Documents] Translations can cause errors on document creation

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#8992]
if you do something like this 
```php
$result = $translator->trans('some_new_key', [], 'admin');
```
in your controller, this can cause following error when creating new documents that uses this controller, when the translation key does not exist yet. 

```
Timestamp: Tue May 04 2021 13:16:46 GMT+0200 (Central European Summer Time)
Status: 500 | 
URL: /admin/document/add
Method: POST
Message: There is no active transaction
Trace: 
in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1774
#0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1774): PDO->commit()
#1 /var/www/html/dev/pimcore/pimcore/lib/Model/Dao/AbstractDao.php(53): Doctrine\DBAL\Connection->commit()
#2 [internal function]: Pimcore\Model\Dao\AbstractDao->commit()
#3 /var/www/html/dev/pimcore/pimcore/lib/Model/AbstractModel.php(243): call_user_func_array(Array, Array)
#4 /var/www/html/dev/pimcore/pimcore/models/Document.php(430): Pimcore\Model\AbstractModel->__call('commit', Array)
#5 /var/www/html/dev/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/DocumentController.php(285): Pimcore\Model\Document->save()
#6 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(157): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\DocumentController->addAction(Object(Symfony\Component\HttpFoundation\Request))
#7 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(79): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#8 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(195): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 /var/www/html/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#10 {main}
```

Reason for that is, that when creating the document Pimcore 
1) checks for missing required editables **within the transaction**
2) for doing so it renders the document
3) and when rendering the document, it tries to create the translation key
4) and when saving the translation key it checks if database table exists with a DDL statement, see [here](https://github.com/pimcore/pimcore/blob/c2b5b40217a6d3fcfe7bbf18ba65745d28ebc213/models/Translation/Dao.php#L136)
--> and this makes an implicit commit what results in the error above when trying to commit the document add transation.

**Comment by fashxp** [comment]
From my point of view ... This rendering needs to happen outside of saving transaction. We never know what happens in controllers of documents...
