### ISSUE TITLE
Create customview - Warning: Undefined array key "form"

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#9040]
# Bug Report

I'm trying to create a custom view for project objects. The empty view shows up, but an error message is triggered:

```URL: /admin/object/tree-get-childs-by-id?_dc=1620300324037
Method: GET
Message: Warning: Undefined array key "form"
Trace: 
in /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:1136
#0 /app/vendor/pimcore/pimcore/models/Element/Service.php(963): Doctrine\DBAL\Query\QueryBuilder->getQueryPart('form')
#1 /app/vendor/pimcore/pimcore/lib/Model/Listing/Dao/QueryBuilderHelperTrait.php(53): Pimcore\Model\Element\Service::Pimcore\Model\Element\{closure}(Object(Doctrine\DBAL\Query\QueryBuilder))
#2 /app/vendor/pimcore/pimcore/models/DataObject/Listing/Dao.php(55): Pimcore\Model\DataObject\Listing\Dao->applyListingParametersToQueryBuilder(Object(Doctrine\DBAL\Query\QueryBuilder))
#3 /app/vendor/pimcore/pimcore/models/DataObject/Listing/Dao.php(117): Pimcore\Model\DataObject\Listing\Dao->getQueryBuilder(Array)
#4 /app/vendor/pimcore/pimcore/models/DataObject/Listing/Dao.php(69): Pimcore\Model\DataObject\Listing\Dao->loadIdList()
#5 [internal function]: Pimcore\Model\DataObject\Listing\Dao->load()
#6 /app/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(243): call_user_func_array(Array, Array)
#7 /app/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(210): Pimcore\Model\AbstractModel->__call('load', Array)
#8 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(157): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->treeGetChildsByIdAction(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#9 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(79): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(195): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /app/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#12 {main}


return [
    "views" => [
        [
            "treetype" => "object",
            "name" => "Projects",
            "icon" => "/bundles/pimcoreadmin/img/flat-color-icons/reading.svg",
            "id" => 1,
            "rootfolder" => "/projects",
            "showroot" => FALSE,
            'classes' => [
                "projects" => 1,
            ],
            "position" => "right",
            "sort" => "1",
            "expanded" => TRUE,
            "having" => "",
            "joins" => "",
            "where" => ""
        ]
    ]
];
```

Version: dev-master|ae9d4daf3245241968e25f8294b60c523bc55bef

**Comment by brusch** [comment]
Already fixed by #9038
