### ISSUE TITLE
RegEx validation throws ErrorException when trying to throw ErrorException

### ISSUE THREAD

**Issue by iidaloiki** [pimcore/pimcore#9673]
# Bug Report

### Expected behavior

When input if validated with regular expression, error should be thrown for invalid input.

### Actual behavior

Error is thrown when creating wanted error.

Error:

`ErrorException::__construct(): Argument #3 ($severity) must be of type int, ErrorException given`

Stacktrace:
```
Status: 500 | Internal Server Error
URL: /admin/object/save?task=publish
Method: PUT
Message: ErrorException::__construct(): Argument #3 ($severity) must be of type int, ErrorException given
Trace: 
in /vendor/pimcore/pimcore/models/DataObject/Concrete.php:168
#0 /vendor/pimcore/pimcore/models/DataObject/Concrete.php(168): ErrorException->__construct('Warning: preg_m...', 0, Object(ErrorException))
#1 /vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(708): Pimcore\Model\DataObject\Concrete->update(true, Array)
#2 /vendor/pimcore/pimcore/models/DataObject/Concrete.php(777): Pimcore\Model\DataObject\AbstractObject->save(Array)
#3 /vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(1359): Pimcore\Model\DataObject\Concrete->save()
#4 /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(157): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->saveAction(Object(Symfony\Component\HttpFoundation\Request))
#5 /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(79): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#6 /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(199): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
```
### Steps to reproduce

1. Create Input field in object
2. Set Regular Expression Validation (for example, HEX color: `#[0-9A-F]{6}$`)
3. Create object and add a value to Input field
4. Error is thrown

### Code example
No code required

**Comment by dvesh3** [comment]
@iibs please see notice on classdefinition, it says delimiter is # so you can't directly use your regex. Either escape it or put in braces
![image](https://user-images.githubusercontent.com/5137917/124487346-e02c9c00-ddae-11eb-82d6-ac936466dc1d.png)
